### ISSUE TITLE
Has problems with playing video

### ISSUE THREAD

**Issue by VikingGeorge** [catsout/wallpaper-engine-kde-plugin#10]
All the requirements are fulfilled. All modules enabled and GStreamer installed. It started playing the video once and when I closed KDE Desktop Wallpaper properties, the video stalled to an image. Please, investigate the issue.

**Helpful Information:** This system is running on an NVIDIA Optimus laptop.

**Comment by catsout** [comment]
So it's could play video, but always pause.  
You can change the `Pause` mode to `Maximized window`, and see if it works.

**Comment by VikingGeorge** [comment]
The thing is, I already did that and it still pauses.

**Comment by catsout** [comment]
Put your kde version.  
Try `journalctl /usr/bin/plasmashell` or `killall plasmashell && kstart5 plasmashell` to see log.  

The useful log may appear when you:
Apply the plugin from another wallpaper plugin.  
Set `Maximized window`, and maximize your any window repeatedly

**Comment by catsout** [comment]
Close, as no reply.
