### ISSUE TITLE
No options for wallpapers

### ISSUE THREAD

**Issue by Sancoraa** [catsout/wallpaper-engine-kde-plugin#100]
**Describe the bug**
I don't have any options about fps, aspect ratio etc...

**Workshop link**
No matter the wallpaper I get the issue

**Kde version**
- Kde: 5.21.4
- Qt: 5.15.2
- OS: Pop_Os

**Additional context**
![Options Bug](https://i.imgur.com/B760V3t.png)

**Comment by zeroruka** [comment]
same problem, using pop os

**Comment by CoreyWarren** [comment]
Same issue here. I do believe this issue only occurred after I installed all the requirements/dependencies needed by the plugin. I should also add, however, that webpage display options and certain video wallpapers provided by the workshop still do not work--as well as some video wallpapers provided by Wallpaper Engine to begin with.

**Comment by Freddyv2356** [comment]
Ok eventually, I actually founded out a way to fix it's actually a visual bug that kinda block or hidden the Wallpaper button and Setting button away.
So I don't really know how I actually fix it but here. I could explain to you.
When I was messing around with the wallpaper page. I press the tab key few times around the whole tabs. Then suddenly I founded a new gui named Wallpaper so i click on it and press right arrow keys or tab button then press enter. And then the whole plasma desktop closed and I opened it again and found it.
![image](https://user-images.githubusercontent.com/95528120/146585258-a2018c25-db9e-4542-b35b-0212e80f6c97.png)
![image](https://user-images.githubusercontent.com/95528120/146585302-40776d5b-82e2-443e-a6b0-f57860009f20.png)
Yes it's just a weird visual bug that block or hidden the settings away but I think that is how I founded the way to fix it. I guess?

**Comment by Sancoraa** [comment]
I tried pressing tab 4 to 7 seven times but whenever I pressed enter the window would just close.
However, when I tried using the arrow keys, I could access the settings and about tab.
I still can't see the tabs name anywhere but I can access them which is the most important, thanks for the detailed steps !

**Comment by Freddyv2356** [comment]
Well about that I don't really know how but i think i kept trying to clicking near the corner and re-sizing where the wallpaper button should be and it's did show up but it's kinda bug that make the text look huge or being only able to see the selected line.
But I think this is depending on Linux distro that you are using displaying tho.

**Comment by Sancoraa** [comment]
I'll try later with my EndavourOS laptop, I'll let you know

**Comment by Sancoraa** [comment]
Tried on EndeavourOS and tabs are right where they should be.
For anyone using Pop_OS or any other distro where tabs are not showing, try pressing tab a couple of times then use your arrow keys as @Freddyv2356 mentioned. That seems to be the only workaround for now.

**Comment by serenovah** [comment]
So I thought I didn't have the tabs for settings, etc, but it turns out the text was white. And I had a theme applied that was a light-mode theme. As soon as I switched to a dark theme that had dark windows I could see the text of the Wallpapers/Settings/About

**Comment by catsout** [comment]
Please try newest commit.

**Comment by Sancoraa** [comment]
All the tabs are now working with the newest commit, thanks for the fix !
