### ISSUE TITLE
module "com.github.catsout.wallpaperEngineKde" is not installed

### ISSUE THREAD

**Issue by davitgog** [catsout/wallpaper-engine-kde-plugin#101]
**Describe the bug**
plasma.log: 
`file:///home/user/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/inline:1:1: module "com.github.catsout.wallpaperEngineKde" is not installed`

after little tinkering, fixed issue by copying `libWallpaperEngineKde.so` `qmldir` to other folder

`# mkdir -p /usr/lib64/qt5/qml/com/github/catsout/wallpaperEngineKde/ ` 
`# cp * /usr/local/lib64/qml/com/github/catsout/wallpaperEngineKde/ /usr/lib64/qt5/qml/com/github/catsout/wallpaperEngineKde/`

**Kde version**
- Kde: [e.g. 5.23.4]
- Qt: [e.g. 5.15.2]
- OS: [e.g. Opensuse]

**Comment by duzhaokun123** [comment]
com.github.casout.wallpaperEngineKd

**Comment by catsout** [comment]
Did you run `sudo make install`?

**Comment by catsout** [comment]
Please go https://github.com/catsout/wallpaper-engine-kde-plugin/issues/133 to continue.
