### ISSUE TITLE
Most video wallpapers have stopped working (Kubuntu 21.10)

### ISSUE THREAD

**Issue by OneSons** [catsout/wallpaper-engine-kde-plugin#103]
**Describe the bug**
Most video wallpapers have stopped working.

**Workshop link** 
Here's one that used to work but now doesn't:
[866364323](https://steamcommunity.com/sharedfiles/filedetails/?id=866364323)

**Kde version**
- Kde: 5.22.90
- Qt: 5.15.2
- OS: Kubuntu 21.10

**Additional context**
Most of my video wallpapers stopped working recently. When I apply them, they play for about half a second and then they freeze. A few still work however. [Here's a video showing the issue](https://streamable.com/21tyja). The first wallpaper works correctly, but the rest do not.

**Comment by serenovah** [comment]
I'm about 50/50 working vs not-working. I'm on the same Kubuntu and Qt versions as you but my KDE Plasma version is 5.22.5 instead.

I knew using the plugin was going to be hit or miss because _Wallpaper Engine_ itself is NOT built for Linux. I'm just happy at least SOME of the wallpapers work.

**Comment by AngelSherry** [comment]
I'm also in the same issue.

#105 

It seems to be caused by the update of PlasmaShell.

```
$ plasmashell

Icon theme "gnome" not found.
kf.plasma.quick: Applet preload policy set to 1
qml: JSON.parse: Parse error
qml: load backend: backend/QtMultimedia.qml
qml: JSON.parse: Parse error
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:134:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:134:19: QML Loader: Binding loop detected for property "height"
Plasma Shell startup completed
qml: JSON.parse: Parse error
Error: cannot change the containment to AppletsLayout
QProcess: Destroyed while process ("/bin/sh") is still running.
qml: ----python helper connected----

** (plasmashell:129388): CRITICAL **: 05:56:35.190: gst_gl_context_new_wrapped: assertion 'available_apis != GST_GL_API_ANY' failed
Could not create wrappped context for platform: 2
```

**Comment by catsout** [comment]
Duplicated https://github.com/catsout/wallpaper-engine-kde-plugin/issues/105
