### ISSUE TITLE
Fedora Kinoite install issue

### ISSUE THREAD

**Issue by KingKrouch** [catsout/wallpaper-engine-kde-plugin#106]
When I attempt to install the plugin using the KDE Plugins page, the plugin lib directory shows up as empty.

But when I attempt to compile from source (I managed to install the correct dependencies using rpm-ostree) and to get it to output the binaries in the right place by changing the cmake output directories for the libraries from /lib64 and /usr to "/var/lib64" (I've even tried doing /var/lib without much luck, as there wasn't a lib64 directory beforehand) and "/var/usrshare" respectively (due to using a distribution where these directories are changed for an immutable root filesystem), the plugin library is still undetected by the plugin (despite being installed correctly).

I attempted to change the directories as listed here in the "libostree" section: https://insujang.github.io/2020-07-15/fedora-silverblue/

**Comment by catsout** [comment]
Installing on fedora kinoite needs to package to rpm.

**Comment by catsout** [comment]
Fixed, please follow the readme.
