### ISSUE TITLE
Closing a window keeps wallpaper paused.

### ISSUE THREAD

**Issue by IslandNolan** [catsout/wallpaper-engine-kde-plugin#107]
When you close an application, Wallpaper engine does not start the wallpaper again until you perform some other action like minimizing another app, or interacting with the Plasma Shell. 

The functionality between the minimize and close buttons should be the same. Ex, when I close my browser and get back to desktop, Wallpaper should not freeze but resume the playback as it does when minimizing an app.

This happens in all wallpapers afaik. 

- Kde: [5.23.5-2]
- Qt: [5.15.2]
- Kernel: [5.15-lts]

**Comment by catsout** [comment]
Fixed.

**Comment by IslandNolan** [comment]
> Fixed.

Thanks!
