### ISSUE TITLE
Installing via KDE Wallpaper Plugins only enables displaying video scenes. Missleading README

### ISSUE THREAD

**Issue by PanZWarzywniaka** [catsout/wallpaper-engine-kde-plugin#108]
I installed KDE WE plugin via Wallpaper Plugins page. This only enabled me using video wallpapers not e.g scene onces. It took me a while that I should install it again directly from repo and follow your all GH readme instructions. There is no information about that. I looked at KDE page of the plugin, and some peaople were also struggling with that.

My ideas of How to Fix:

1. Write in your read me that you should not install plugin via KDE GUI for that, otherwise scene wallpapers will not be supported. In about page of the plugin it should be also mentioned that, beacouse this will be the first thing user sees after installed your plugin via GUI.
2. Or make KDE GUI install fully with plugin lib, so everything works out of the box.

It's great plugin but instructions could me more clear.
Cheers

**Comment by cathaysia** [comment]
maybe this can help you: https://github.com/catsout/wallpaper-engine-kde-plugin/issues/102

**Comment by catsout** [comment]
Closed, as already in readme.
