### ISSUE TITLE
Wallpapers don't scale and crop on non-uniform screens

### ISSUE THREAD

**Issue by dman926** [catsout/wallpaper-engine-kde-plugin#111]
**Describe the bug**
Wallpapers don't scale and crop on non-uniform screens. I am using a 2560x1080 screen and wallpapers are defaulted to `Centered` positioning without a way to change to `Scaled and Cropped`.

**Workshop link**
[833227004](https://steamcommunity.com/sharedfiles/filedetails/?id=833227004)
[837681768](https://steamcommunity.com/sharedfiles/filedetails/?id=837681768)

**Kde version**
- Kde: 5.20.5
- Qt: 5.15.2
- OS: Debian 11

**Additional context**
I've seen in issue #98 setting the positioning to `Scaled and Cropped` fixes it, but that option is missing in the `Wallpaper Engine for KDE` wallpaper type. I'm not sure if it's supposed to be there or is in a config file somewhere.

**Comment by dman926** [comment]
I still can't get the settings or about tab working, but I did find a new bug. The plugin is installed to `~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde` and not `~/.local/share/plasma/wallpapers/com.github.catsout.wallpaperEngineKde` (`catsout` misspelled). Small issue but I doubt this is affecting the issue. Here is what my view looks like
![wallpaper_engine_kde_plugin](https://user-images.githubusercontent.com/13112544/150188614-a87da6e9-476a-4b67-8fbc-6f9db54b7c12.png)

**Comment by Jelgnum** [comment]
Did you build from source or did you install from the KDE Wallpaper plugins?
I've only had this when missing dependencies, not entering all the commands for install or not logging out and back in after installing.

**Comment by dman926** [comment]
I am building from source. Haven't tried using the kde store version but I will see. Perhaps just a bug with the latest commit? I am sure I have the listed dependencies and have completely rebooted (not just restart kde) after install and uninstall. Maybe a Debian 11 issue? It's still pretty new to stable.

I'm not smart enough to dig into the code for this project, so I'll fall back to a stable release or store version and watch the repo for changes.
