### ISSUE TITLE
Plugin lib not installed

### ISSUE THREAD

**Issue by WildGamma** [catsout/wallpaper-engine-kde-plugin#117]
When compiling the package, however, despite having installed MPV, cmake does not detect it.

Please, provide plugin lib binaries (or be more specific)

**Comment by StarOnTheSky** [comment]
Binaries does NOT work for all distros & releases.
Please specify your build environment (distro, version, CMake version, mpv library version, etc.) so that we can locate the problem.

**Comment by WildGamma** [comment]
I am using up-to-date openSUSE Tumbleweed. I am currently not on my Linux machine so I cannot check my CMake and mpv versions currently.

**Comment by catsout** [comment]
Please go https://github.com/catsout/wallpaper-engine-kde-plugin/issues/133 to continue.
