### ISSUE TITLE
Issue compiling on OpenSUSE TW

### ISSUE THREAD

**Issue by Bens0** [catsout/wallpaper-engine-kde-plugin#118]
➜  build git:(main) make -j8
[  3%] Automatic MOC and UIC for target mpvbackend
[  5%] Built target glad
[  8%] Built target wpAudio
[  8%] Built target mpvbackend_autogen
Consolidate compiler generated dependencies of target mpvbackend
[ 67%] Built target wallpaper
[ 68%] Building CXX object src/backend/mpv/CMakeFiles/mpvbackend.dir/mpvbackend.cpp.o
[ 70%] Automatic MOC and UIC for target scenebackend
[ 70%] Built target scenebackend_autogen
[ 75%] Built target scenebackend
[ 77%] Automatic MOC and UIC for target scenebackend-qml
[ 77%] Built target scenebackend-qml_autogen
[ 87%] Built target scenebackend-qml
/home/ember/work/wallpaper-engine-kde-plugin/src/backend/mpv/mpvbackend.cpp: In function ‘int {anonymous}::CreateMpvContex(mpv_handle*, mpv_render_context**)’:
/home/ember/work/wallpaper-engine-kde-plugin/src/backend/mpv/mpvbackend.cpp:60:85: error: too many initializers for ‘mpv_opengl_init_params’
   60 |         mpv_opengl_init_params gl_init_params{get_proc_address_mpv, nullptr, nullptr};
      |                                                                                     ^
make[2]: *** [src/backend/mpv/CMakeFiles/mpvbackend.dir/build.make:90: src/backend/mpv/CMakeFiles/mpvbackend.dir/mpvbackend.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:276: src/backend/mpv/CMakeFiles/mpvbackend.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by catsout** [comment]
Fixed.
