### ISSUE TITLE
Puppet warp not suppoted, cause terrible wallpaper

### ISSUE THREAD

**Issue by StarOnTheSky** [catsout/wallpaper-engine-kde-plugin#120]
**Describe the bug**
As you see, the girls are not rendered properly and seem terrible.
![Screenshot_20220206_123030](https://user-images.githubusercontent.com/51866924/152667920-8faead38-6427-443c-bea4-606f2a45ce57.png)
![Screenshot_20220206_123003](https://user-images.githubusercontent.com/51866924/152667935-634ed49b-dbe5-45a7-ac2c-2913898c0ba8.png)

**Workshop link**
[2572528403](https://steamcommunity.com/sharedfiles/filedetails/?id=2572528403)
[2597983718](https://steamcommunity.com/sharedfiles/filedetails/?id=2597983718)

**Kde version**
- Kde: 5.22.5
- Qt: 5.15
- OS: Ubuntu 21.10

**Additional context**
Idk.

**Comment by catsout** [comment]
This probably is part of `Puppet warp`, currently not supported.

**Comment by StarOnTheSky** [comment]
Does this wallpaper use puppet warp? I found it works properly. [2569621489](https://steamcommunity.com/sharedfiles/filedetails/?id=2569621489)

**Comment by catsout** [comment]
not use.

**Comment by catsout** [comment]
Supported, currently in offsreen brance.  
Welcome to test.

**Comment by StarOnTheSky** [comment]
Okay.

> Supported, currently in offsreen brance. Welcome to test.

**Comment by StarOnTheSky** [comment]
Not working now
I'm on the latest commit 5bbb4d8c

**Comment by catsout** [comment]
You need to switch to offcreen branch and update git submodule.

**Comment by StarOnTheSky** [comment]
> You need to switch to offcreen branch and update git submodule.

Okay.

**Comment by StarOnTheSky** [comment]
![Screenshot_20220315_161237](https://user-images.githubusercontent.com/51866924/158334415-969d5e54-a42e-4e1a-ad67-52da11105368.png)
This wallpaper is working now.
![Screenshot_20220315_161252](https://user-images.githubusercontent.com/51866924/158334468-5ac003b9-a85d-4357-b44a-038db5424971.png)
But this one isn't.

**Comment by StarOnTheSky** [comment]
Also, it cannot play the audio in the wallpaper.

**Comment by catsout** [comment]
Closed.  
Please open a new issue for https://steamcommunity.com/sharedfiles/filedetails/?id=2572528403

**Comment by catsout** [comment]
@StarOnTheSky 
Could you give me your gpu info?

**Comment by StarOnTheSky** [comment]
> @StarOnTheSky 
> Could you give me your gpu info?  

Nvidia RTX2060M

**Comment by catsout** [comment]
Do you use the intel card + nvidia prime, or nviida directly?

**Comment by StarOnTheSky** [comment]
> Do you use the intel card + nvidia prime, or nviida directly?

Intel only & Nvidia only. I don't (or can't) use prime.

**Comment by StarOnTheSky** [comment]
> Do you use the intel card + nvidia prime, or nviida directly?

Intel only & Nvidia only. I don't (or can't) use prime.

**Comment by catsout** [comment]
If you have time, please test this plugin both on intel and nvidia only, as some people currently can't see the property result.  
I want to figure out if only the amd card has that problem.

**Comment by StarOnTheSky** [comment]
> 

Okay, I'll test it later. Do you need logs or just screenshots?

**Comment by catsout** [comment]
No need logs, just to make sure that it works.
