### ISSUE TITLE
Won't show NSFW content

### ISSUE THREAD

**Issue by Snowball-programm-dev** [catsout/wallpaper-engine-kde-plugin#123]
**Bug/Limitation**
i'm not sure if it was planed like this, but i can't select or see the NSFW wallpaper i downloaded.
i'd like to get an answer on how i coul'd fix it on my system an if it was on purpes

**version**
- Plasma: 5.24.1
-  OS: Arch Linux

**Comment by Jelgnum** [comment]
You have to check that box yourself, it's filtered out by default
![image](https://user-images.githubusercontent.com/86729439/154805696-aee9eb79-a595-48ef-bfc8-315e9f593704.png)
