### ISSUE TITLE
System 76 problem with installation

### ISSUE THREAD

**Issue by AnoirsGit** [catsout/wallpaper-engine-kde-plugin#13]
Hello, i installed kde by sudo aptinstall kde-plasma-desktop
1) I don't have steam dir in ~/.local/share/Steam instead mine is ~/.steam/steam
2) I cant choose dir of steam

**Comment by catsout** [comment]
Just choose ~/.steam/steam. 
Make sure:. 
1. install qt-labs-folderlistmodel, you can use apt search to find exact package.   
2. wallpaper engine is installed at ~/.steam/steam. 

If you mean you select it, but it can't be saved.  
Debug with [this](https://community.kde.org/Plasma/Debugging#Check_widgets_dynamically).  
Then put the log here.

**Comment by AnoirsGit** [comment]
how can i set folder path by code? because kde plasma debug gives empty list and also every time when i set folder path and press ok button, it resets
![Uploading image.png…]()

**Comment by catsout** [comment]
Choose ~/.steam/steam, and press ok  
I don't recommend to set by code, as there may be some error. Need to solve them to make the plugin work, and setting by code mostly will not work.  
For debug, try:  
`killall plasmashell && kstart5 plasmashell`, this restart plasmashell in terminal with log output, do it when you are in free time

**Comment by AnoirsGit** [comment]
QQmlEngine::setContextForObject(): Object already has a QQmlContext
file:///home/noir/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/config.qml:55:17: QML ComboBox: Cannot anchor to an item that isn't a parent or sibling.
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:85:9: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
Model size of -33 is less than 0
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"
kf.kio.widgets.kdirmodel: protocol mismatch: "" vs "file"

**Comment by catsout** [comment]
Can you put result of
`ls -l ~/.steam/steam/steamapps/workshop/content/431960`
and  
`apt show qml-module-qt-labs-folderlistmodel`

**Comment by AnoirsGit** [comment]
![image](https://user-images.githubusercontent.com/49281851/115135476-8e3f6a00-a03a-11eb-8a89-f13647c276f9.png)

**Comment by catsout** [comment]
Try latest commit with `kquitapp5 plasmashell && kstart5 plasmashell`
