### ISSUE TITLE
No Backgrounds after selected one 

### ISSUE THREAD

**Issue by Gorkemkaratas50** [catsout/wallpaper-engine-kde-plugin#130]
- [ fix this bug please ]![2022-03-06_20-53](https://user-images.githubusercontent.com/77190341/156935509-46a73487-ddef-42ba-aa2f-7b2badb6d2e8.png)

Hey i am having this problem any one could help?

**Comment by IcyFeather233** [comment]
I have the same problem, I don't know why

**Comment by IcyFeather233** [comment]
> Please supply the information from the template:
> 
> KDE: [e.g. 5.20] Qt: [e.g. 5.15] OS: [e.g. Debian]

KDE Frameworks 5.68.0
Qt 5.12.8
The xcb windowing system
OS: linux mint 20.3
KDE Plasma Version 5.18.8
Kernel Version: 5.4.0-104-generic

**Comment by IcyFeather233** [comment]
![image](https://user-images.githubusercontent.com/56245435/158016571-34325360-5d58-48cc-8a62-407d8f69c52d.png)
![image](https://user-images.githubusercontent.com/56245435/158016577-7427ce1f-3359-479b-940d-9016fdbf5a95.png)

after I use once this plugin, I cannot use it anymore.
![image](https://user-images.githubusercontent.com/56245435/158016618-d9ae55b5-fccb-4d6c-8427-860739f56cdc.png)

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/125

**Comment by catsout** [comment]
I'm working on switching to vulkan, so this will be delayed.

**Comment by catsout** [comment]
BTW, better to provide log by `kquitapp5 plasmashell && kstart5 plasmashell`

**Comment by Gorkemkaratas50** [comment]
thanks

**Comment by Gorkemkaratas50** [comment]
so any ways i can fix this? uninstall does not work. @catsout

**Comment by Gorkemkaratas50** [comment]
Omitting both --window and --windowclass arguments is not recommended
Icon theme "gnome" not found.
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/8x8/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/16x16/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/16x16/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/22x22/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/24x24/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/24x24/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/32x32/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/32x32/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/48x48/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/48x48/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/64x64/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/64x64/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/96x96/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/96x96/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/256x256/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/512x512/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/scalable/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/scalable/ui/"
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
(base) gorkem@Gorkemlaptop:~$ Icon theme "gnome" not found.
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/8x8/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/16x16/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/16x16/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/22x22/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/24x24/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/24x24/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/32x32/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/32x32/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/48x48/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/48x48/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/64x64/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/64x64/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/96x96/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/96x96/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/256x256/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/512x512/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/scalable/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/scalable/ui/"
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
org.kde.plasmaquick: Applet preload policy set to 1
qml: JSON.parse: Parse error
qml: load backend: backend/Scene.qml
qml: JSON.parse: Parse error
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
Plasma Shell startup completed
INFO  SoundManager.cpp:109: muted, not init sound device
INFO  WPPkgFs.cpp:22: pkg version: PKGV0001
INFO  WPMaterial.cpp:96: read json "blending" not a key at FromJson
INFO  WPMaterial.cpp:97: read json "cullmode" not a key at FromJson
ERROR WPSceneParser.cpp:369: ShaderValue: Power not found in glsl
ERROR WPSceneParser.cpp:369: ShaderValue: Alpha not found in glsl
ERROR WPSceneParser.cpp:590: ShaderValue: Power not found in glsl
ERROR WPSceneParser.cpp:590: ShaderValue: Alpha not found in glsl
QProcess: Destroyed while process ("/bin/sh") is still running.
qml: Traceback (most recent call last):
  File "/home/gorkem/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py", line 4, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'

qml: 
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:306:17: QML QQuickText: Binding loop detected for property "width"
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:306:17: QML QQuickText: Binding loop detected for property "width"
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:306:17: QML QQuickText: Binding loop detected for property "width"
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:306:17: QML QQuickText: Binding loop detected for property "width"
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:306:17: QML QQuickText: Binding loop detected for property "width"
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:306:17: QML QQuickText: Binding loop detected for property "width"
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:306:17: QML QQuickText: Binding loop detected for property "width"
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:306:17: QML QQuickText: Binding loop detected for property "width"
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:306:17: QML QQuickText: Binding loop detected for property "width"
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
trying to show an empty dialog
trying to show an empty dialog
libkcups: CUPS-Get-Printers last error: 0 successful-ok
libkcups: Create-Printer-Subscriptions last error: 0 successful-ok
libkcups: Get-Jobs last error: 0 successful-ok
libkcups: Get-Jobs last error: 0 successful-ok
QQuickItem::stackAfter: Cannot stack StatusNotifierItem_QMLTYPE_313(0x55b8519cb670, parent=0x55b851629a60, geometry=0,0 0x0) after StatusNotifierItem_QMLTYPE_313(0x55b8519cde20), which must be a sibling
QQuickItem::stackAfter: Cannot stack StatusNotifierItem_QMLTYPE_313(0x55b8519c8260, parent=0x55b851629a60, geometry=0,0 0x0) after StatusNotifierItem_QMLTYPE_313(0x55b8519cb670), which must be a sibling
QQuickItem::stackAfter: Cannot stack StatusNotifierItem_QMLTYPE_313(0x55b8519e30d0, parent=0x55b851629a60, geometry=0,0 0x0) after StatusNotifierItem_QMLTYPE_313(0x55b8519c8260), which must be a sibling
QQuickItem::stackAfter: Cannot stack StatusNotifierItem_QMLTYPE_313(0x55b8519e5490, parent=0x55b851629a60, geometry=0,0 0x0) after StatusNotifierItem_QMLTYPE_313(0x55b8519e30d0), which must be a sibling
libkcups: 3 "EPSON_L210_Series"
libkcups: 3 "HP-LaserJet-Professional-P1102"
libkcups: 0
libkcups: 0
Both point size and pixel size set. Using pixel size.
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
qml: QQuickGridView_QML_139(0x55b850a54320)
KAStatsFavoritesModel::setFavorites is ignored
trying to show an empty dialog 
Log after kquitapp5 plasmashell && kstart5 plasmashell

**Comment by catsout** [comment]
Please go https://github.com/catsout/wallpaper-engine-kde-plugin/issues/125 to continue.
