### ISSUE TITLE
Can I use this plugin without mpv?

### ISSUE THREAD

**Issue by j1g5awi** [catsout/wallpaper-engine-kde-plugin#134]
I don't want to install mpv, but sounds like it must need mpv when building and loading.

README said it's optional, but actually i can't load this plugin if uninstall mpv.

**Comment by catsout** [comment]
No, it's not easy to separate scene and mpv.

**Comment by catsout** [comment]
@j1g5awi 
Why do you want to remove mpv?

**Comment by j1g5awi** [comment]
Just because I don't like to install a dependency I do not need, make it really optional.
