### ISSUE TITLE
Package 'vulkan-devel' not found in repository pool.

### ISSUE THREAD

**Issue by jayp0521** [catsout/wallpaper-engine-kde-plugin#136]
**Describe the bug**<br/>
Package 'vulkan-devel' not found in repository pool.

**Workshop link**<br/>
[e.g. 1139304621](https://steamcommunity.com/sharedfiles/filedetails/?id=1139304621)

**System Information**
- Kde: [e.g. 5.20] kde5-5.23.0_1
- Qt: [e.g. 5.15] qt5-5.15.3+20220222_1
- OS: [e.g. Debian] void linux
- Installation Source: [e.g. KDE Plugins or git] git

**Additional context**<br/>
Add any other context about the problem here. [e.g. screenshots/logs]

I have all repos here except debug https://docs.voidlinux.org/xbps/repositories/index.html

**Comment by jayp0521** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/commit/71fcc422511eef850ca8bb20efed537bdbcea93b

I just saw this. unsure if it is related

**Comment by catsout** [comment]
I'm not using void linux.  
Could you search the repo to find the similar package?

**Comment by Rippanda12** [comment]
vulkan devel is a combination of packages that include vulkan libs 
```:: There are 7 members in group vulkan-devel:
:: Repository extra
   1) spirv-tools  2) vulkan-extra-layers  3) vulkan-extra-tools  4) vulkan-headers  5) vulkan-html-docs  6) vulkan-tools  7) vulkan-validation-layers
```

**Comment by Rippanda12** [comment]
@catsout i may have mislead you with that PR request i think i was missing vulkan-headers but not sure (it was stuck on vulkan libs missing)

**Comment by catsout** [comment]
@jayp0521 
You need to install [vulkan-headers](https://archlinux.org/packages/?name=vulkan-headers).
