### ISSUE TITLE
Scene type wallpapers dont work (linear noise)

### ISSUE THREAD

**Issue by Rippanda12** [catsout/wallpaper-engine-kde-plugin#137]
**Describe the bug**<br/>
scene type wallpapers appear as "screen garbage" 

**Workshop link**<br/>
[e.g. 1962910096](https://steamcommunity.com/sharedfiles/filedetails/?id=1962910096)
Any that use the .scene type
**System Information**
- Kde: 5.24.3
- Qt: 5.15.3
- OS: Arch Linux
- Installation Source: github

**Additional context**<br/>
Add any other context about the problem here. [e.g. screenshots/logs]
![2022-03-22_12-48](https://user-images.githubusercontent.com/59401553/159442284-16d5293f-cebb-41a6-8b91-5845a287c204.png)

**Comment by catsout** [comment]
Please go https://github.com/catsout/wallpaper-engine-kde-plugin/tree/main/src/backend_scene/standalone_view.  
run  
```
mkdir build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_QML=ON
```
Require glfw to build.  

Test with  
```
./sceneviewer steamapps/common/wallpaper_engine/assets steamapps/workshop/content/431960/1962910096/scene.pkg

./sceneviewer-qml steamapps/common/wallpaper_engine/assets steamapps/workshop/content/431960/1962910096/scene.pkg
```
`steamapps` normally is in your steam installed folder.   

Also, please give your gpu info.

**Comment by arbobendik** [comment]
> Please go https://github.com/catsout/wallpaper-engine-kde-plugin/tree/main/src/backend_scene/standalone_view. run
> 
> ```
> mkdir build && cd build
> cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_QML=ON
> make
> ```
> 
> Require glfw to build.
> 
> Test with
> 
> ```
> ./sceneviewer steamapps/common/wallpaper_engine/assets steamapps/workshop/content/431960/1962910096/scene.pkg
> 
> ./sceneviewer-qml steamapps/common/wallpaper_engine/assets steamapps/workshop/content/431960/1962910096/scene.pkg
> ```
> 
> `steamapps` normally is in your steam installed folder.
> 
> Also, please give me your gpu info.

I have the same problem with a Vega 8 on a Ryzen 5700u running the vulkan-radeon driver for mesa on Arch. I've already switched drivers, because with the amdvlk driver I used previously the background was just black for all scene backgrounds.

The first test command opens crashes with "ERROR VulkanRender.cpp:67 init vulkan failed"
and the second test produces the same "screen garbage" result like the one above.

**Comment by catsout** [comment]
@arbobendik 
Install `vulkan-validation-layers`, and try `./sceneviewer -V ...`, and put the log here.  
Need to make sure `sceneviewer` works first, then test on `sceneviewer-qml`

**Comment by catsout** [comment]
Unfortunately, I don't have a amd card to test with.

**Comment by j1g5awi** [comment]
> 

```log
INFO render looper started
INFO main looper started
INFO set swapchain image size: 1280x720
INFO source: /home/jigsaw/.steam/steam/steamapps/workshop/content/431960/2513488428/scene.pkg
INFO vulkan valid layer "VK_LAYER_KHRONOS_validation" enabled
ERROR VulkanRender.cpp:67 init vulkan failed
INFO render handler deleted
INFO render looper stopped
INFO main looper stopped
```
failed again

**Comment by j1g5awi** [comment]
> @arbobendik Install `vulkan-validation-layers`, and try `./sceneviewer -V ...`, and put the log here. Need to make sure `sceneviewer` works first, then test on `sceneviewer-qml`

> ```
> INFO render looper started
> INFO main looper started
> INFO set swapchain image size: 1280x720
> INFO source: /home/jigsaw/.steam/steam/steamapps/workshop/content/431960/2513488428/scene.pkg
> INFO vulkan valid layer "VK_LAYER_KHRONOS_validation" enabled
> ERROR VulkanRender.cpp:67 init vulkan failed
> INFO render handler deleted
> INFO render looper stopped
> INFO main looper stopped
> ```
> 
> failed again

**Comment by Rippanda12** [comment]
i have a AMD Radeon R7 370 (amdgpu driver) i have tried radeon aswell but same issue
```
[panda@panda build]$ ./sceneviewer ~/steamlibrary/steamapps/common/wallpaper_engine/assets ~/steamlibrary/steamapps/workshop/content/431960/1664782848/scene.pkg
INFO main looper started
INFO render looper started
INFO set swapchain image size: 1280x720
INFO source: /home/panda/steamlibrary/steamapps/workshop/content/431960/1664782848/scene.pkg
WARNING: radv is not a conformant Vulkan implementation, testing use only.
INFO vulkan device: AMD RADV PITCAIRN
INFO new buffer block, size: 2097152, index: 0
INFO new buffer block, size: 2097152, index: 0
INFO sound device inited
INFO pkg version: PKGV0002
INFO read json "id" not a key at FromJson
INFO new buffer block, size: 2097152, index: 0
INFO new buffer block, size: 2097152, index: 0
ERROR VulkanRender.cpp:236 VkResult is " Timeout "
sceneviewer: /home/panda/wallpaper-engine-kde-plugin/src/backend_scene/wallpaper/VulkanRender/VulkanRender.cpp:236: void wallpaper::vulkan::VulkanRender::drawFrameSwapchain(): Assertion `res == vk::Result::eSuccess' failed.
Aborted (core dumped)
```
```
[panda@panda build]$ ./sceneviewer-qml ~/steamlibrary/steamapps/common/wallpaper_engine/assets ~/steamlibrary/steamapps/workshop/content/431960/1664782848/scene.pkg
INFO main looper started
INFO render looper started
INFO source: /home/panda/steamlibrary/steamapps/workshop/content/431960/1664782848/scene.pkg
OpenGL Version 4.6 loaded
GL EXT loaded
INFO set swapchain image size: 1280x720
WARNING: radv is not a conformant Vulkan implementation, testing use only.
INFO vulkan device: AMD RADV PITCAIRN
INFO new buffer block, size: 2097152, index: 0
INFO new buffer block, size: 2097152, index: 0
INFO sound device inited
INFO pkg version: PKGV0002
INFO read json "id" not a key at FromJson
INFO new buffer block, size: 2097152, index: 0
INFO new buffer block, size: 2097152, index: 0
wekde.scene: receive external texture(1280x720) from fd: 20
wekde.scene: receive external texture(1280x720) from fd: 19
wekde.scene: receive external texture(1280x720) from fd: 17
```
![2022-03-23_09-31](https://user-images.githubusercontent.com/59401553/159646633-330eb9e3-741b-4ee0-9cea-50c6a67919f8.png)

**Comment by arbobendik** [comment]
> @arbobendik Install `vulkan-validation-layers`, and try `./sceneviewer -V ...`, and put the log here. Need to make sure `sceneviewer` works first, then test on `sceneviewer-qml`

This is the log I'm getting with the -V argument:
`./sceneviewer -V /home/bendik/.steam/steam/steamapps/common/wallpaper_engine/assets /home/bendik/.steam/steam/steamapps/workshop/content/431960/2554178089/scene.pkg
INFO INFO main looper started
render looper started
INFO set swapchain image size: 1280x720
INFO vulkan valid layer "VK_LAYER_KHRONOS_validation" enabled
INFO source: /home/bendik/.steam/steam/steamapps/workshop/content/431960/1664782848/scene.pkg
ERROR VulkanRender.cpp:67 init vulkan failed
`
and

`./sceneviewer-qml -V /home/bendik/.steam/steam/steamapps/common/wallpaper_engine/assets /home/bendik/.steam/steam/steamapps/workshop/content/431960/2554178089/scene.pkg
INFO render looper started
INFO main looper started
INFO source: /home/bendik/.steam/steam/steamapps/workshop/content/431960/1664782848/scene.pkg
Icon theme "Numix-Circle-Light" not found.
OpenGL Version 4.6 loaded
GL EXT loaded
INFO set swapchain image size: 1280x720
INFO vulkan valid layer "VK_LAYER_KHRONOS_validation" enabled
INFO vulkan device: AMD RADV RENOIR
INFO new buffer block, size: 2097152, index: 0
INFO new buffer block, size: 2097152, index: 0
INFO sound device inited
INFO pkg version: PKGV0013
INFO new buffer block, size: 2097152, index: 0
INFO new buffer block, size: 2097152, index: 0
wekde.scene: receive external texture(1280x720) from fd: 19
wekde.scene: receive external texture(1280x720) from fd: 18
wekde.scene: receive external texture(1280x720) from fd: 17
wekde.scene: Destroy sceneobject
wekde.scene: Destroy texnode
INFO Destory instance
INFO render handler deleted
INFO render looper stopped
INFO main looper stopped
INFO uninit sound device`

**Comment by arbobendik** [comment]
I've asked a friend who compiled this plugin a few weeks ago to send me the source. I've followed the installation steps and the scenes works now... This is the file he sent me:
[wallpaper-engine-kde-plugin.tar.gz](https://github.com/catsout/wallpaper-engine-kde-plugin/files/8331639/wallpaper-engine-kde-plugin.tar.gz)
I

**Comment by j1g5awi** [comment]
> I've asked a friend who compiled this plugin a few weeks ago to send me the source. I've followed the installation steps and the scenes works now... This is the file he sent me: [wallpaper-engine-kde-plugin.tar.gz](https://github.com/catsout/wallpaper-engine-kde-plugin/files/8331639/wallpaper-engine-kde-plugin.tar.gz) (As a quickfix for everyone having this issue right now)

It just because your friend doesn't merge the newest Pull Request of this repo.

If anyone want to compile a **more stable version**, just checkout the 02a6b516033c8960be8152eaca108272c1fe2040 commit.

**Comment by catsout** [comment]
Please try the new commit.  
Test with `./sceneviewer --valid-layer ...`

**Comment by catsout** [comment]
Maybe related: https://gitlab.freedesktop.org/mesa/mesa/-/issues/2456  
Should be fixed on https://github.com/catsout/wallpaper-engine-kde-plugin/commit/0a0137b85dabbbcd6f31303c05f3480534c8a3ef if so.

**Comment by Rippanda12** [comment]
> Maybe related: https://gitlab.freedesktop.org/mesa/mesa/-/issues/2456 Should be fixed on [0a0137b](https://github.com/catsout/wallpaper-engine-kde-plugin/commit/0a0137b85dabbbcd6f31303c05f3480534c8a3ef) if so.

so now if i build i shouldnt have the issue anymore or only with the sceneviewer?

**Comment by Rippanda12** [comment]
yup still doesnt work

**Comment by catsout** [comment]
I need to see the log.

**Comment by Rippanda12** [comment]
its animated and its not bugged out (./sceneviewer)

**Comment by catsout** [comment]
Try to insert   
`m_tiling = wallpaper::TexTiling::LINEAR;`
to  
https://github.com/catsout/wallpaper-engine-kde-plugin/blob/0a0137b85dabbbcd6f31303c05f3480534c8a3ef/src/backend_scene/glExtra.cpp#L98

Then build and test again.

**Comment by Rippanda12** [comment]
It works fine
how can i implement this to the plugin or should i build and install it?

**Comment by catsout** [comment]
May need to add `-DCMAKE_BUILD_TYPE=Release` to cmake to get best performance.

**Comment by Rippanda12** [comment]
okay the plugin works but the paralax effect and xray is messed up

**Comment by catsout** [comment]
@Rippanda12 
>okay the plugin works but the paralax effect and xray is messed up

Paralax effect and xray are both supported, you need to enable mouse input on setting page.  
But i can't be sure that these works on all wallpapers.

**Comment by catsout** [comment]
@j1g5awi @arbobendik 
Does it work now?

**Comment by j1g5awi** [comment]
Fine



发件人: catsout
发送时间: 2022年3月24日 15:17
收件人: catsout/wallpaper-engine-kde-plugin
抄送: Jigsaw; Mention
主题: Re: [catsout/wallpaper-engine-kde-plugin] Scene type wallpapers dontwork (noise) (Issue #137)

@j1g5awi @arbobendik
Does it work now?

**Comment by user8171** [comment]
I have GTX1060 and installed driver 515,then the output this error again and again
![image](https://user-images.githubusercontent.com/90666894/187026111-8613f614-2777-49b3-a497-ed4abd273cbb.png)
