### ISSUE TITLE
Pausing on Maximized Window pauses the wallpaper with dual monitors

### ISSUE THREAD

**Issue by DracoDragon93** [catsout/wallpaper-engine-kde-plugin#14]
If you have it set to the Pause on Maximize Window option, it counts all of your monitors. If monitor 1 has a wallpaper from Wallpaper Engine with no windows open, but monitor 2 has a window that's maximized, it will pause monitor 1's wallpaper anyway.

**Comment by no95typem** [comment]
@DracoDragon93 
It's working with mpv backend normally for me. I can maximize windows on one monitor and video on another one doesn't stop.

**Comment by no95typem** [comment]
@DracoDragon93 

I suggested a patch #19. But I think that someone should test it besides me before it can be merged to master.

**Comment by DracoDragon93** [comment]
> @DracoDragon93
> 
> I suggested a patch #19. But I think that someone should test it besides me before it can be merged to master.

Tested it, it looks like it works perfectly fine and fixes the issue.

**Comment by D3SOX** [comment]
I still have this issue as of ffd6dfbcb5f1eb32e0a097352757be9e3cc453e9

**Comment by catsout** [comment]
@D3SOX
Try new commit.

**Comment by D3SOX** [comment]
@catsout Thank you, it's working now!
