### ISSUE TITLE
Plugin lib not found.

### ISSUE THREAD

**Issue by TheSwedenGuy** [catsout/wallpaper-engine-kde-plugin#141]
**Describe the bug**<br/>
Very few wallpapers work, keep getting the message of plugin lib not found on many of my wallpapers

**System Information**
- Kde: 5.24.3
- Qt: 5.15.3
- OS: Arch Manjaro
- Installation Source: Git

**Additional context**<br/>
Running a 5700XT if that is of any help, tried reinstalling all dependencies and the plugin to no avail.

**Comment by catsout** [comment]
Please go https://github.com/catsout/wallpaper-engine-kde-plugin/issues/133 to continue.
