### ISSUE TITLE
Support change standalone viewer's resolution

### ISSUE THREAD

**Issue by Rippanda12** [catsout/wallpaper-engine-kde-plugin#144]
In another thread i tried /src/backend_scene/standalone_view and it worked i wonder if theres a way to change the resolution so i can use xwinwrap to set the wallpaper on i3 (and more)

**Comment by catsout** [comment]
As I wrote the standalone view mainly for test, I just hard-coded the resolution.  
It requires some extra codes to support change resolution.

**Comment by Rippanda12** [comment]
this can be a possibility to port it to different DE's

**Comment by Rippanda12** [comment]
> As I wrote the standalone viewer mainly for testing, I just hard coded the resolution. It requires some extra codes to support changing resolution.

Editing [main.qml](https://github.com/catsout/wallpaper-engine-kde-plugin/blob/main/src/backend_scene/standalone_view/main.qml) And adding a resolution (1920x1080) then compiling allows you to do so! not so easy but you dont change resolutions that often so it doesnt matter

**Comment by Rippanda12** [comment]
![2022-04-05_08-26](https://user-images.githubusercontent.com/59401553/161684902-8222eeb0-4670-4109-877d-aab2954eae90.png)
Using xwinwrap and devilspie i managed to get wallpaper engine on xfce 
```cat $HOME/.devilspie/wallpaper.ds 
(if (is (window_name) "sceneviewer-qml")
    (begin
        (below)
        (stick)
	(geometry "1920x1080+1280+0")
        (skip_pager)
        (maximize)
        (undecorate)
    )
)
```
`xwinwrap -g 1920x1080+1280+0 -ni -un -fdt -debug -nf -- sceneviewer-qml ~/steamlibrary/steamapps/common/wallpaper_engine/assets ~/steamlibrary/steamapps/workshop/content/431960/test/scene.pkg
`

**Comment by catsout** [comment]
supported.
