### ISSUE TITLE
Can not get the right wallpaper setting dialogue box

### ISSUE THREAD

**Issue by Gourmentic** [catsout/wallpaper-engine-kde-plugin#15]
Dear Catsout,

I installed the plugin but can not get the right setting dialogue box, and get the error info from terminal as below. My system is ubuntu 20.04 and KDE shell. Please help me how to fix this issue, thanks a lot.

![image](https://user-images.githubusercontent.com/23225921/114537539-e82fe080-9c84-11eb-8b4b-e51693658937.png)

![image](https://user-images.githubusercontent.com/23225921/114537597-f978ed00-9c84-11eb-93be-142a82a1f873.png)

**Comment by catsout** [comment]
I have updated,   
git pull, update plugin and try again.

**Comment by Gourmentic** [comment]
Thanks Catsout.
Now the error changed.
![image](https://user-images.githubusercontent.com/23225921/114541929-e583ba00-9c89-11eb-8f17-168e6f0ac66f.png)

**Comment by catsout** [comment]
What's your kde version?

**Comment by Gourmentic** [comment]
> What's your kde and qt version?

![image](https://user-images.githubusercontent.com/23225921/114544954-ed455d80-9c8d-11eb-962f-ae46d63521e8.png)

**Comment by catsout** [comment]
Try again.

**Comment by Gourmentic** [comment]
Thanks a lot. After delete the valueRole in config.qml, the dialogue box is show.
![image](https://user-images.githubusercontent.com/23225921/114552720-77de8a80-9c97-11eb-846b-101e3abdb428.png)
![image](https://user-images.githubusercontent.com/23225921/114553043-ce4bc900-9c97-11eb-92ec-714bd2836166.png)


But another issue show, and the wallpaper does not work.
![image](https://user-images.githubusercontent.com/23225921/114552561-4f569080-9c97-11eb-9be9-8661554bf978.png)

**Comment by catsout** [comment]
Sorry, I forget to remove valueRole. 
Wait again, I need to check all qml import version.  
By the way, from the log, seems you are not install the plugin lib.

**Comment by Gourmentic** [comment]
> Sorry, I forget to remove valueRole.
> Wait again, I need to check all qml import version.
> By the way, from the log, seems you are not install the plugin lib.

I install the plugin lib as you list in README as shown below, Is there any other lib to install?

![image](https://user-images.githubusercontent.com/23225921/114555318-27b4f780-9c9a-11eb-936f-e4dd7b615d96.png)

**Comment by catsout** [comment]
Down version done.
Try again, apply wallpaper, and see what are shown on the screen.

**Comment by catsout** [comment]
No, my fault.
This time should work for you.

**Comment by catsout** [comment]
Works?  
Qtmultimedia need qt 5.13 for this plugin, you need use mpv to play video.

**Comment by Gourmentic** [comment]
It works now, Thanks very much.
