### ISSUE TITLE
Standalone viewer crash

### ISSUE THREAD

**Issue by Rippanda12** [catsout/wallpaper-engine-kde-plugin#150]
**Describe the bug**<br/>
I have a script that relaunches the standalone viewer every 30mins
```
while true
do
        randwall=$(shuf -n1 -e ~/steamlibrary/steamapps/workshop/content/431960/*)
        printf $randwall
        sceneviewer-qml ~/steamlibrary/steamapps/common/wallpaper_engine/assets $randwall/scene.pkg &
        sleep 30 && echo 'kill' 
        pkill sceneviwer
done
```
but every other time i get 
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x1600004
  Serial number of failed request:  99
  Current serial number in output stream:  99

**Additional context**<br/>
kill
/home/panda/steamlibrary/steamapps/workshop/content/431960/2762290420_cat_lumine
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x5800004
  Serial number of failed request:  395
  Current serial number in output stream:  396
kill
/home/panda/steamlibrary/steamapps/workshop/content/431960/2533542185_hu_tao_lumine
Window Title: 'Untitled window'; Application Name: 'Untitled window'; Class: ''; Geometry: 1920x1080+1280+0
INFO main looper started
INFO render looper started
INFO source: /home/panda/steamlibrary/steamapps/workshop/content/431960/2533542185_hu_tao_lumine/scene.pkg
Window Title: 'sceneviewer-qml'; Application Name: 'sceneviewer-qml'; Class: 'sceneviewer-qml'; Geometry: 1920x1050+1280+30
INFO gl: OpenGL version 4.6 loaded
INFO gl: OpenGL vendor string: AMD
INFO gl: external tex using linear tiling
INFO set swapchain image size: 1920x1022
WARNING: radv is not a conformant Vulkan implementation, testing use only.
INFO new buffer block, size: 2097152, index: 0
INFO new buffer block, size: 2097152, index: 0
INFO sound device inited
INFO pkg version: PKGV0013
INFO new buffer block, size: 2097152, index: 0
INFO new buffer block, size: 2097152, index: 0
wekde.scene: receive external texture(1920x1022) from fd: 25
wekde.scene: receive external texture(1920x1022) from fd: 23
wekde.scene: receive external texture(1920x1022) from fd: 24
kill
/home/panda/steamlibrary/steamapps/workshop/content/431960/2010303541_nakano_nino_go_toubun_no_hanayome_the_quintessential_quintuplets
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x5800004
  Serial number of failed request:  395
  Current serial number in output stream:  396
kill 
```

**Comment by Rippanda12** [comment]
oh right 
DE XFCE
Distro ARCH

**Comment by catsout** [comment]
No idea.  
As I say, the standalone is only for testing, so I will close this.
