### ISSUE TITLE
particles/shader displaying with a transparent white background over wallpaper

### ISSUE THREAD

**Issue by Jelgnum** [catsout/wallpaper-engine-kde-plugin#151]
**Describe the bug**<br/>
The fog and particles seem to display over the actual background art, art is still animated

**Workshop link**<br/>
[1447282515](https://steamcommunity.com/sharedfiles/filedetails/?id=1447282515)

**System Information**
- Kde: 5.24.4
- Qt: 5.15.3
- OS: Manjaro
- Installation Source: Git

**Additional context**<br/>
![hmm yes](https://user-images.githubusercontent.com/86729439/162526665-2c0f42d0-bc60-4e19-8af7-d8533345731b.png)

**Comment by Jelgnum** [comment]
From looking through my library of wallpapers I have found that every other wallpaper with the petals and smoke is just fine, but I don't have another wallpaper with the godrays like this one has, so that effect might be part of what is causing the problem.

**Comment by catsout** [comment]
Fixed.  
https://github.com/catsout/wallpaper-engine-kde-plugin/commit/77a69cd6be2113b60a300dd62c33f82352717f3f
