### ISSUE TITLE
Wallpapers from workshop not showing in list.

### ISSUE THREAD

**Issue by OsoaGH** [catsout/wallpaper-engine-kde-plugin#152]
**Describe the bug**<br/>
All wallpapers from the workshop do not appear on the list, leaving only the pre-installed ones shown.

**System Information**
- Kde: 5.22.5
- Qt: 5.15.2
- OS: Pop!_OS 21.10
- Installation Source: KDE Plugins

**Additional context**<br/>
![image](https://user-images.githubusercontent.com/33041004/162588675-b5d96c71-3971-4949-aabe-930e321687c0.png)
![image](https://user-images.githubusercontent.com/33041004/162588712-7ffb7d4f-9c6e-4499-b804-b239692d7c56.png)

**Comment by catsout** [comment]
1. Check if your wallpaper is at the same steam library as you selected in plugin.  
2. Run `plasmashell --replace` to get log
Please choose the log after you open the wallpaper plugin setting.  

You need to re-login to run plasmashell normally after test.  

Depends on your system, if you can get log from `journalctl /usr/bin/plasmashell -f`  
you don't need the step `2` and re-login.

**Comment by OsoaGH** [comment]
> 1. Check if your wallpaper is at the same steam library as you selected in plugin.
> 
>     2. Run `plasmashell --replace` to get log
>        Please choose the log after you open the wallpaper plugin setting.
> 
> 
> You need to re-login to run plasmashell normally after test.
> 
> Depends on your system, if you can get log from `journalctl /usr/bin/plasmashell -f` you don't need the step `2` and re-login.

Here's the log:
`kf.coreaddons: "Could not load plugin from "
Error loading KCM: ""
qml: ---check lib 'com.github.catsout.wallpaperEngineKde 1.1' failed---
qml: Error: Qt.createQmlObject(): failed to create object: 
    file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/inline:1:1: module "com.github.catsout.wallpaperEngineKde" is not installed
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/SettingPage.qml:246:21: QML DoubleSpinBox: Binding loop detected for property "implicitWidth"
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/SettingPage.qml:246:21: QML DoubleSpinBox: Binding loop detected for property "implicitWidth"
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/SettingPage.qml:246:21: QML DoubleSpinBox: Binding loop detected for property "implicitHeight"
kf.kirigami: Units.devicePixelRatio is deprecated (since 5.86 ): This returns 1 when using Qt HiDPI scaling.
kf.kirigami: Previous message repeats 331 times.
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/SettingPage.qml:155:25: QML SpinBox: Binding loop detected for property "implicitHeight"
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/SettingPage.qml:119:25: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/SettingPage.qml:119:25: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/SettingPage.qml:119:25: QML SpinBox: Binding loop detected for property "implicitHeight"
qml: JSON.parse: Parse error
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/SettingPage.qml:246:21: QML DoubleSpinBox: Binding loop detected for property "implicitWidth"
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/SettingPage.qml:119:25: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/WallpaperPage.qml:329:22: QML Flickable: Binding loop detected for property "contentWidth"
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/config.qml:9:1: QML ColumnLayout: StackView has detected conflicting anchors. Transitions may not execute properly.
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:90:13: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
qml: require: file:///home/osoa/.steam/steam/steamapps/workshop/content/431960, but get: file:///home/osoa
qml: require: file:///home/osoa/.steam/steam/steamapps/workshop/content/431960, but get: file:///home/osoa
qml: scan folder: file:///home/osoa/.steam/steam/steamapps/common/wallpaper_engine/projects/myprojects, found 0 subdir
qml: scan folder: file:///home/osoa/.steam/steam/steamapps/common/wallpaper_engine/projects/defaultprojects, found 19 subdir
qml: show the first: file:///home/osoa/.steam/steam/steamapps/common/wallpaper_engine/projects/defaultprojects/arsenal
QProcess: Destroyed while process ("/bin/sh") is still running.
qml: ----python helper connected----
qml: filtered, filter: 01111111011111111111111111111111111, from 0 to 0
qml: filtered, filter: 01111111011111111111111111111111111, from 19 to 16
file:///home/osoa/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/page/WallpaperPage.qml:465:28: QML ListModel: append: value is not an object
`

**Comment by catsout** [comment]
Please check if `/home/osoa/.steam/steam/steamapps/workshop/content/431960` exists.

**Comment by OsoaGH** [comment]
> Please check if `/home/osoa/.steam/steam/steamapps/workshop/content/431960` exists.

Fixed it. For some reason the workshop and content folders were capitalized. Thanks for the help.
