### ISSUE TITLE
make error wont allow plugin lib to install

### ISSUE THREAD

**Issue by notabot27** [catsout/wallpaper-engine-kde-plugin#153]
Hi, i am receiving an error when running make, I will get 99% through then the console spits out this:
Install the project...
-- Install configuration: "Release"
CMake Error at src/cmake_install.cmake:62 (file):
  file INSTALL cannot find
  "/home/overlord/wallpaper-engine-kde-plugin/build/src/libWallpaperEngineKde.so":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)

I am on Kubuntu 21.10 with an amd rx5500xt. according to libcheck in the plugin about page I have everything but plugin lib.

**Comment by catsout** [comment]
Closed, as no reply.
