### ISSUE TITLE
Module "QtMultiMedia" Version 5.13 is not installed "QtWebChannel" version 1.10 is not installed

### ISSUE THREAD

**Issue by crystalPepsi** [catsout/wallpaper-engine-kde-plugin#157]
I'm running Linux Mint. I copied all of the dependency commands for Debian from this project but web type and video type wallpapers don't work for me and give me this error. Scene ones work fine, though. If I switch video backend to Mpv then videos work.

**Comment by catsout** [comment]
You may have a too low qt version.
