### ISSUE TITLE
Wallpaper not detected

### ISSUE THREAD

**Issue by TheFlomax** [catsout/wallpaper-engine-kde-plugin#158]
**Describe the bug**<br/>
The plugin does not detect the wallpaper contained in the file "/home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/".
I have reinstalled the plugin and rebooted my PC but nothing happens.

**System Information**
- Kde: 5.24.4
- Qt: 5.15.3
- OS: Linux Garuda
- Installation Source: KDE Plugins

**Comment by catsout** [comment]
1. Check if your wallpaper is at the same steam library as you selected in plugin.
2.  Run plasmashell --replace to get log
    Please choose the log after you open the wallpaper plugin setting.

You need to re-login to run plasmashell normally after test.

Depends on your system, if you can get log from journalctl /usr/bin/plasmashell -f
you don't need the step 2 and re-login.

**Comment by TheFlomax** [comment]
I don't understand why it fails.
The files exsists TwT



Icon theme "adwaita" not found.
Icon theme "ubuntu-mono" not found.
Icon theme "yaru" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
kf.plasma.quick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/ShortcutMenuItem.qml:17:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 10. Use 'sequences: [ <key> ]' to bind to all of them.
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/ShortcutMenuItem.qml:17:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 9. Use 'sequences: [ <key> ]' to bind to all of them.
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/ShortcutMenuItem.qml:17:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 8. Use 'sequences: [ <key> ]' to bind to all of them.
qml: JSON.parse: Parse error
qml: JSON.parse: Parse error
qml: PlasmaExtras.ScrollArea is deprecated. Use PlasmaComponents3.ScrollView instead.
Plasma Shell startup completed
qml: JSON.parse: Parse error
Error: cannot change the containment to AppletsLayout
QProcess: Destroyed while process ("/bin/sh") is still running.
qml: ----python helper connected----
Qt: Session management error: networkIdsList argument is NULL
Icon theme "adwaita" not found.
Icon theme "ubuntu-mono" not found.
Icon theme "yaru" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
qml: QQuickGridView_QML_268(0x559e28bcdf70)
QQmlEngine::setContextForObject(): Object already has a QQmlContext
file:///usr/lib/qt/qml/org/kde/kirigami.2/ApplicationItem.qml:151:9: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 13. Use 'sequences: [ <key> ]' to bind to all of them.
file:///usr/lib/qt/qml/org/kde/kirigami.2/ApplicationItem.qml:147:9: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 14. Use 'sequences: [ <key> ]' to bind to all of them.
QQmlEngine::setContextForObject(): Object already has a QQmlContext
kf.coreaddons: "Could not find plugin org.kde.desktopcontainment"
Error loading KCM: "Could not find plugin org.kde.desktopcontainment"
kf.coreaddons: "Could not find plugin org.kde.plasma.folder"
Error loading KCM: "Could not find plugin org.kde.plasma.folder"
kf.coreaddons: "Could not find plugin org.kde.plasma.folder"
Error loading KCM: "Could not find plugin org.kde.plasma.folder"
kf.coreaddons: "Could not find plugin com.github.casout.wallpaperEngineKde"
Error loading KCM: "Could not find plugin com.github.casout.wallpaperEngineKde"
kf.coreaddons: "Could not find plugin com.github.casout.wallpaperEngineKde"
Error loading KCM: "Could not find plugin com.github.casout.wallpaperEngineKde"
qml: JSON.parse: Parse error
qml: JSON.parse: Parse error
Error: cannot change the containment to AppletsLayout
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:190:17: QML ConfigCategoryDelegate: Binding loop detected for property "implicitHeight"
file:///home/theflomax/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/components/OptionItem.qml:96:9: QML Control: Binding loop detected for property "implicitHeight"
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/workshop/content/431960, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/workshop/content/431960, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/defaultprojects, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/defaultprojects, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/myprojects, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/myprojects, but get: file:///home/theflomax
qml: JSON.parse: Parse error
Error: cannot change the containment to AppletsLayout
QProcess: Destroyed while process ("/bin/sh") is still running.
qml: ----python helper connected----
kf.coreaddons: "Could not find plugin com.github.zren.inactiveblur"
Error loading KCM: "Could not find plugin com.github.zren.inactiveblur"
file:///home/theflomax/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/config.qml:9:1: QML ColumnLayout: StackView has detected conflicting anchors. Transitions may not execute properly.
file:///home/theflomax/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/Pyext.qml:65: TypeError: Cannot read property 'jrpc' of null
QProcess: Destroyed while process ("/bin/sh") is still running.
kf.coreaddons: "Could not find plugin com.github.casout.wallpaperEngineKde"
Error loading KCM: "Could not find plugin com.github.casout.wallpaperEngineKde"
qml: JSON.parse: Parse error
file:///home/theflomax/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/config.qml:9:1: QML ColumnLayout: StackView has detected conflicting anchors. Transitions may not execute properly.
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/workshop/content/431960, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/workshop/content/431960, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/defaultprojects, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/defaultprojects, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/myprojects, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/myprojects, but get: file:///home/theflomax
QProcess: Destroyed while process ("/bin/sh") is still running.
qml: ----python helper connected----
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/workshop/content/431960, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/defaultprojects, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/workshop/content/431960, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/defaultprojects, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/myprojects, but get: file:///home/theflomax
qml: require: file:///home/theflomax/.local/share/Steam/steamapps/workshop/content/431960/steamapps/common/wallpaper_engine/projects/myprojects, but get: file:///home/theflomax

**Comment by catsout** [comment]
Please choose the folder `/home/theflomax/.local/share/Steam`  
Also check if `/home/theflomax/.local/share/Steam/steamapps/workshop/content/431960` exists.

**Comment by TheFlomax** [comment]
I have checked it exists

**Comment by TheFlomax** [comment]
After ".local" is not displayed, the plugin may not have the right to access it?

![image](https://user-images.githubusercontent.com/69845574/163578694-f854a68e-26a9-41b0-91f7-05ade5869226.png)

**Comment by TheFlomax** [comment]
Oh it works!
You just had to enter the `/home/theflomax/.local/share/Steam `by hand.
