### ISSUE TITLE
Plugin is unable to see wallpapers

### ISSUE THREAD

**Issue by wedgevic** [catsout/wallpaper-engine-kde-plugin#159]
First I want to thank you a million times over for this as wallpaper engine was one of the last things still keeping me in windows, so thank you so much for making this amazing plugin. However, as title suggests, I have not been able to get this to show the wallpapers at all, I tried the main steam directory, the steamapps directory and even the workshop directory but it still shows "There are no wallpapers in steam's workshop directory"
![image](https://user-images.githubusercontent.com/53971909/163648671-0e763bf6-f95c-40f2-8543-15c2cb5f4dc6.png)
![image](https://user-images.githubusercontent.com/53971909/163648694-38ddbfea-940d-47de-b5a0-95a5195030db.png)

I'm sorry if this is just something stupid that I am missing as I am still relatively new to KDE and this plugin in general.

System info:
![image](https://user-images.githubusercontent.com/53971909/163648834-62b17fde-6fd9-4ca9-a473-603aa329f73f.png)

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/152

**Comment by wedgevic** [comment]
thank you very much

**Comment by wedgevic** [comment]
> #152

thank you very much
