### ISSUE TITLE
High CPU usage with HW Decoding

### ISSUE THREAD

**Issue by no95typem** [catsout/wallpaper-engine-kde-plugin#16]
**Describe the bug**
High CPU utilization even with hw decoding (mpv backend). For example "Smart video wallpaper" plugin loaded my cpu by 7% without hardware decoding, (needless to say, with specially encoded video for easy decoding with CPU) . This plugin consumes ~8% CPU with mpv backend and hw decoding. Without hw decoding ~ 16%. So I think there is a problem. For some reason, this plugin consumes 2 times more resources than it could. I think it can be optimized if we find the reason why this is happening. This is not critical, but it would make this great plugin better and almost perfect!

**Kde version**
- Kde: [5.21.4]
- Qt: [5.15.2]
- OS: [Manjaro]

**Additional context**
I compiled the plugin, leaving only the backend mpv (disabled everything else). It's because I don't like redundant things.

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/blob/6eee9a43ee5361596c13ba295b7e516337839492/plugin/contents/ui/backend/Mpv.qml#L33

Add `player.command(["script-binding","stats/display-stats-toggle"]);` below that line.  
Add update plugin, restart plasmashell  
You will see the mpv stats show  
Please put the screenshot to here

**Comment by catsout** [comment]
> Without hw decoding ~ 16%

How you use mpv without hwdecode?
Also What's the usage when using QtMultimedia?

**Comment by no95typem** [comment]
@catsout 
Thank you for your quick response!

First, when I wrote "without hw decoding" it's about gstreamer (qtmultimedia). So all the beauty of your plugin is in mpv backend for me. It's really "killer-feature".

But back to the purpose. It's interesting. My specially encoded video:

![Screenshot_20210424_113300](https://user-images.githubusercontent.com/50191552/115951469-e91d0980-a4f1-11eb-82ac-27fc617d8957.png)

There is no information about the decoder for some reason, but nvidia-smi shows 10% gpu utilization.

And it's for normal video (one from workshop):

![Screenshot_20210424_113322](https://user-images.githubusercontent.com/50191552/115951519-300aff00-a4f2-11eb-9321-b6a5f111c46f.png)

So your plugin is perfectly functional. I would take the CPU consumption as the normal value, not knowing that "Smart Video Wallpaper" consumes less ceteris paribus (using qtmultimedia without hw decoding support). I just want to say that it means that somewhere you can optimize cpu utilization. But even so, your plugin looks much better due to the ability to use a video card. And finally I shouldn't compress the video for myself. I've found an idea that additional consumption comes from the ability to limit the number of frames. I would gladly say that I will check it myself, but now I do not have time, unfortunately, to do this.

**Comment by catsout** [comment]
> There is no information about the decoder for some reason, but nvidia-smi shows 10% gpu utilization.

This is not about decoder, the gpu is used by mpv render.  

> I would take the CPU consumption as the normal value, not knowing that "Smart Video Wallpaper" consumes less ceteris paribus (using qtmultimedia without hw decoding support).

You should get the same cpu usage as "Smart Video Wallpaper", if you don't use mpv.  

> I've found an idea that additional consumption comes from the ability to limit the number of frames.
No, limit fps only works on scene wallpaper.  

I also don't know why there is more cpu consumption on mpv.   
I will try optimizing, and I think the hwdecoder maybe more efficient if you play 4k video.

**Comment by catsout** [comment]
Hi, If you have free time, you can test cpu usage of mpv with [hotspot](https://github.com/KDAB/hotspot).  
I added a mpv-viewer, you can find it at `src/backend/mpv/viewer`  
Just `mkdir build && cd build && cmake .. && make`, you will get `mpvbackend-viewer`  
Use it like, `mpvbackend-viewer <video file>`  
And run it through hotspot to get a flamegraph  
Like this: 
![flamegraph](http://brendangregg.com/FlameGraphs/cpu-bash-flamegraph.png)

**Comment by catsout** [comment]
You need [Installing the debugging symbols](https://wiki.debian.org/HowToGetABacktrace#Installing_the_debugging_symbols) of your system package  
On debian, it's like `sudo apt install libmpv1-dbgsym libqt5quick5-dbgsym libqt5core5a-dbgsym`

**Comment by no95typem** [comment]
Thank you! You have put in a lot of effort. But I can't give you a detailed hotspot report because I'm on an arch-based distribution - we don't have dbgsym out of the box here. The first minus that I found in this distribution! But don't bother! In practice, the load on the CPU is not felt. Htop shows the loading, but apparently it is not entirely correct to look at it. With this level of constant loading in other applications, I very quickly hear the roar of the cooler (yes, the pc is old already). But this does not happen in idle with your plugin enabled. I think htop is just showing peaks.
So, thanks for your attention and responsiveness! But I think you shouldn't waste your time on this. I raised the topic in vain, I had to test first on practice, sorry.
By the way, mpv-viewer consumes about 10-12% according to htop. Even slightly higher than the mpv plugin. So it's not about the plugin anyway.
And, you, I suppose, misunderstood me, I use a plugin with mpv - I like everything, including the load on the cpu. I was only comparing the CPU load of your plugin with a "smart video wallpaper" plugin with QtMultimedia backend (gstreamer) enabled. And only with a special video that I processed for easy playback without hw decoding. But who needs a gstreamer without hardware acceleration when you wrote the wonderful mpv backend? Exactly not me. By the way, I don't know why on my system gstreamer doesn't use hw decoding by default. But now I don't need to find out, thank's to you. I think you may close this issue.
![1](https://user-images.githubusercontent.com/50191552/116128050-93a35100-a6d9-11eb-86d6-4b67eaea2112.png)
