### ISSUE TITLE
Dependencies for opensuse?

### ISSUE THREAD

**Issue by ItzRivalBTW** [catsout/wallpaper-engine-kde-plugin#160]
What dependencies would I need for opensuse tumbleweed?
I get this error while compiling 

CMake Error at CMakeLists.txt:28 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by catsout** [comment]
Try to find the dependencies depend on other distribution package names.  
And pr welcome.

**Comment by LuisArtDavila** [comment]
Did you ever manage to figure this out?
