### ISSUE TITLE
Python 3.10 support needed

### ISSUE THREAD

**Issue by StarOnTheSky** [catsout/wallpaper-engine-kde-plugin#161]
**Describe the bug**<br/>
![Screenshot_20220422_132818](https://user-images.githubusercontent.com/51866924/164609517-bcf6ff72-6f02-4308-8cc7-58c3fee8a29f.png)

**System Information**
- Kde: [e.g. 5.20] 5.24.4
- Qt: [e.g. 5.15] 5.15.3
- OS: [e.g. Debian] Ubuntu 22.04
- Installation Source: [e.g. KDE Plugins or git] git
- Python version: 3.10.4

**Comment by catsout** [comment]
I have fixed this on previous commit.  
Please run `make install_pkg` again.

**Comment by StarOnTheSky** [comment]
> I have fixed this on previous commit. Please run `make install_pkg` again.

![Screenshot_20220422_135823](https://user-images.githubusercontent.com/51866924/164612675-75f1a5c7-12b1-401d-ae16-2eff8cf6bb07.png)

**Comment by catsout** [comment]
Please try to re-login.

**Comment by catsout** [comment]
It seems that you install this plugin in `/usr/share/plasma/wallpaper`  
You need to update via the way you install this plugin before.  
Also remove the one in home, `plasmapkg2 -r ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde`

**Comment by catsout** [comment]
You can also update through:  
```
cmake .. -DUSE_PLASMAPKG=OFF
make
sudo make install
```
This will install to `/usr/share/plasma/wallpaper`

**Comment by StarOnTheSky** [comment]
> You can also update through:
> 
> ```
> cmake .. -DUSE_PLASMAPKG=OFF
> make
> sudo make install
> ```
> 
> This will install to `/usr/share/plasma/wallpaper`

Still not working.
I have removed the one in `/usr/share/plasma/wallpapers` and reinstalled it in `~/.local/share/plasma/wallpapers`.

**Comment by StarOnTheSky** [comment]
![Screenshot_20220422_143217](https://user-images.githubusercontent.com/51866924/164616794-e48386d3-ddc8-49f7-a330-b7a94bee9b06.png)
The plugin can't find `python3-websockets`, but I'm sure that I have installed it.

**Comment by catsout** [comment]
Try  
```
cd ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents
python3 ./pyext.py -h
```
I need the output.

**Comment by StarOnTheSky** [comment]
> Try
> 
> ```
> cd ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents
> python3 ./pyext.py -h
> ```
> 
> I need the output.

```
❯  python3 pyext.py -h
usage: pyext.py [-h] URL

qml localfile helper

positional arguments:
  URL         a websocket url

options:
  -h, --help  show this help message and exit
```

**Comment by catsout** [comment]
I think you don't clean the old one.  
Please check `/usr/share/plasma/wallpaper` and `/usr/local/share/plasma/wallpaper`  
Also the log on `wallpapers` page.

**Comment by catsout** [comment]
Here is the script to run `pyext`  
```qml
    readonly property string file: "plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py"

        const sh = [
            `EXT=${file}`,
            `WKD="no_pyext_file_found"`,
            "[ -f \"$XDG_DATA_HOME/$EXT\" ] && WKD=\"$XDG_DATA_HOME/$EXT\"", 
            "[ -f \"$HOME/.local/share/$EXT\" ] && WKD=\"$HOME/.local/share/$EXT\"",
            "[ -f /usr/share/$EXT ] && WKD=/usr/share/$EXT",
            "[ -f /usr/local/share/$EXT ] && WKD=/usr/local/share/$EXT",
            `exec python3 "$WKD" "${ws_server.url}"`
```

**Comment by StarOnTheSky** [comment]
> I think you don't clean the old one. Please check `/usr/share/plasma/wallpaper` and `/usr/local/share/plasma/wallpaper` Also the log on `wallpapers` page.

I'm sure that I had removed this plugin from `/usr/share/plasma/wallpapers`. No such directory called `/usr/local/plasma`.

**Comment by StarOnTheSky** [comment]
> Here is the script to run `pyext`
> 
> ```qml
>     readonly property string file: "plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py"
> 
>         const sh = [
>             `EXT=${file}`,
>             `WKD="no_pyext_file_found"`,
>             "[ -f \"$XDG_DATA_HOME/$EXT\" ] && WKD=\"$XDG_DATA_HOME/$EXT\"", 
>             "[ -f \"$HOME/.local/share/$EXT\" ] && WKD=\"$HOME/.local/share/$EXT\"",
>             "[ -f /usr/share/$EXT ] && WKD=/usr/share/$EXT",
>             "[ -f /usr/local/share/$EXT ] && WKD=/usr/local/share/$EXT",
>             `exec python3 "$WKD" "${ws_server.url}"`
> ```

I can only give you screenshots because I can't copy the log to clipboard.

**Comment by StarOnTheSky** [comment]
> Here is the script to run `pyext`
> 
> ```qml
>     readonly property string file: "plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py"
> 
>         const sh = [
>             `EXT=${file}`,
>             `WKD="no_pyext_file_found"`,
>             "[ -f \"$XDG_DATA_HOME/$EXT\" ] && WKD=\"$XDG_DATA_HOME/$EXT\"", 
>             "[ -f \"$HOME/.local/share/$EXT\" ] && WKD=\"$HOME/.local/share/$EXT\"",
>             "[ -f /usr/share/$EXT ] && WKD=/usr/share/$EXT",
>             "[ -f /usr/local/share/$EXT ] && WKD=/usr/local/share/$EXT",
>             `exec python3 "$WKD" "${ws_server.url}"`
> ```

How to run it? Is it a valid shell script?

**Comment by catsout** [comment]
You don't need to run it.  
Just let me see the log on `Wallpaper ` page.

**Comment by StarOnTheSky** [comment]
> You don't need to run it. Just let me see the log on `Wallpapers ` page.

![Uploading Screenshot_20220422_150303.png…]()

**Comment by catsout** [comment]
`python-websockets` support `python 3.10` after `10.0`  
https://tracker.debian.org/news/1314526/accepted-python-websockets-102-1-source-into-unstable/  

But Ubuntu's newest `python-websockets` is at `9.1`, as your info, the python is at `3.10`, so it's broken   
https://launchpad.net/ubuntu/+source/python-websockets

No idea, please report bug to ubuntu, or switch to another distribution

**Comment by StarOnTheSky** [comment]
> Having same issue with Ubuntu 22, possible to make it downward compatible?

No, just run `sudo pip install websockets -U` to upgrade `python3-websockets`, then reload the plasma.
