### ISSUE TITLE
All wallpapers don't pause when set condition is met

### ISSUE THREAD

**Issue by Jelgnum** [catsout/wallpaper-engine-kde-plugin#166]
**Describe the bug**<br/>
When you have wallpapers set to pause for focused/maximized/any window it only pauses for the screen with that window.

This might be a design choice now that I think about. If it is could we have a setting that looks for any maximized or any focused window to pause all the wallpapers on all screens? Otherwise then the additional context maybe useful for determining this bug.

**System Information**
- Kde: 5.24.4
- Qt:  5.15.3
- OS: Arch
- Installation Source: Git

**Additional context**<br/>
I am running Wayland instead of x11

**Comment by catsout** [comment]
A new option is added for this.  
Please check if it works, if not, just reopen this issue.

**Comment by Jelgnum** [comment]
It works, thank you!

**Comment by Jelgnum** [comment]
That would probably be because gamescope is its own compositor that runs on top of kde instead of just being a normal kde window

**Comment by zany130** [comment]
![image](https://user-images.githubusercontent.com/25832539/171729755-f1a62f99-0a2c-4eb7-8c10-2a7175501fbd.png)
 I dont seem to have that option?  which is strange as im running the latest version as seen above

**Comment by zany130** [comment]
Oh is there an up to date aur version? The other ones where out of date for a while

**Comment by Jelgnum** [comment]
I would recommend uninstalling that package and using the instructions from the readme for installation, it's pretty easy as far as installations go.

**Comment by zany130** [comment]
the install instructions don't work for me that's why I was using the aur. that and so that I don't have to build it everytime there's an update (which takes about 30 minutes on my machine)
