### ISSUE TITLE
Plugin does not detect that python3-websockets is installed

### ISSUE THREAD

**Issue by tysiekert** [catsout/wallpaper-engine-kde-plugin#167]
**Describe the bug**<br/>
When attempting to configure the wallpapers, there is a python error displayed, and under the about tab the lib checking appears to state that python3-websockets is not installed. However, the latest version of python3-websockets (9.1-1) is already installed.

**System Information**
- Kde: 5.24
- Qt: 5.15.3
- OS: Pop!_OS
- Installation Source: git

**Additional context**<br/>
![image](https://user-images.githubusercontent.com/80056852/165217279-5db15369-b9d4-4697-9122-a43d2452cea0.png)
![image](https://user-images.githubusercontent.com/80056852/165217306-9a6aa744-8bcc-428e-96c9-f1251361780f.png)
![image](https://user-images.githubusercontent.com/80056852/165217336-9a14eb56-48b7-4cfe-b777-25d7b2a51314.png)

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/162
