### ISSUE TITLE
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

### ISSUE THREAD

**Issue by Impasse52** [catsout/wallpaper-engine-kde-plugin#168]
**Describe the bug**<br/>
I've installed this on Kubuntu by following the steps in the readme, but when I go into the "Wallpaper Engine for Kde" page, I am greeted by "TypeError: As of 3.10, the \*loop\* parameter was removed from Lock() since it is no longer necessary". Also, the about page doesn't tick the "python3-websockets" library, which is weird since I've installed websockets both via pip and via apt.

**System Information**
- Kde: 5.24.4
- Qt: 5.15.3
- OS: Kubuntu 22.04
- Installation Source: git

**Additional context**<br/>
![](https://i.imgur.com/TjDoBwY.png)
![](https://i.imgur.com/3iXXKEZ.png)

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/162
