### ISSUE TITLE
Python helper run failed

### ISSUE THREAD

**Issue by xgamecodes12** [catsout/wallpaper-engine-kde-plugin#169]
Hi 
i was wondering what to do because i recently came to linux and kubuntu i was confused and i dont know what is going on so i hope i can get help here for the python issue and since im lazy and copy paste the error i took a screenshot
![crop](https://user-images.githubusercontent.com/31537592/167958041-062f676b-b961-4dc6-8238-7063f2d7d134.png)

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/162
