### ISSUE TITLE
Gif type wallpapers don't work

### ISSUE THREAD

**Issue by eyalmazuz** [catsout/wallpaper-engine-kde-plugin#170]
**Describe the bug**<br/>
I just installed the engine and gif type wallpapers result in a black screen but mp4 type wallpapers work

**Workshop link**<br/>
https://steamcommunity.com/sharedfiles/filedetails/?id=1845706469
https://steamcommunity.com/sharedfiles/filedetails/?id=2806240713

**System Information**
- Kde: 5.24
- Qt: 5.15
- OS: Manjaro
- Installation Source: git

**Additional context**<br/>
![Screenshot_20220513_123522](https://user-images.githubusercontent.com/34383384/168256480-4c0c87d0-afca-4068-a46c-2228984702bf.png)

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/147

https://github.com/catsout/wallpaper-engine-kde-plugin/blob/main/DEBUG.md

**Comment by catsout** [comment]
Please get me the log of `vulkaninfo --summary`.

**Comment by eyalmazuz** [comment]
> #147
> 
> https://github.com/catsout/wallpaper-engine-kde-plugin/blob/main/DEBUG.md

> Please give me the log of `vulkaninfo --summary`.

#147 seemed to fix the issue

I guess I skipped this issue when search cause I search for gif specific related issues cause video-based wallpapers did work for me without the vulkan-intel package
thank you.
