### ISSUE TITLE
[old device] Black screen when using scene wallpaper. With video and web all okay..

### ISSUE THREAD

**Issue by Bendy3192** [catsout/wallpaper-engine-kde-plugin#171]
Hello! When I'm using "scene" wallpapers, I've got black screen. 
Kubuntu 22.04 LTS, CPU: AMD Athlon II P360 (2) @ 2.300GHz/GPU: AMD ATI Mobility Radeon HD 4225/4250.
P.S. I have very old temporarily laptop.

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/147

https://github.com/catsout/wallpaper-engine-kde-plugin/blob/main/DEBUG.md

Please give me the log of `vulkaninfo --summary`.

**Comment by Bendy3192** [comment]
> `vulkaninfo --summary`

vulkaninfo --summary
ERROR: [../src/amd/vulkan/radv_device.c:597] Code 0 : Device '/dev/dri/renderD128' is not using the AMDGPU kernel driver: Invalid argument (VK_ERROR_INCOMPATIBLE_DRIVER)
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.204


Instance Extensions: count = 19
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6

Instance Layers: count = 6
--------------------------
VK_LAYER_MESA_device_select       Linux device selection layer 1.2.73   version 1
VK_LAYER_MESA_overlay             Mesa Overlay layer           1.2.199  version 1
VK_LAYER_VALVE_steam_fossilize_32 Steam Pipeline Caching Layer 1.2.136  version 1
VK_LAYER_VALVE_steam_fossilize_64 Steam Pipeline Caching Layer 1.2.136  version 1
VK_LAYER_VALVE_steam_overlay_32   Steam Overlay Layer          1.2.136  version 1
VK_LAYER_VALVE_steam_overlay_64   Steam Overlay Layer          1.2.136  version 1

Devices:
========
GPU0:
        apiVersion         = 4202700 (1.2.204)
        driverVersion      = 1 (0x0001)
        vendorID           = 0x10005
        deviceID           = 0x0000
        deviceType         = PHYSICAL_DEVICE_TYPE_CPU
        deviceName         = llvmpipe (LLVM 13.0.1, 128 bits)
        driverID           = DRIVER_ID_MESA_LLVMPIPE
        driverName         = llvmpipe
        driverInfo         = Mesa 22.0.1 (LLVM 13.0.1)
        conformanceVersion = 0.0.0.0
        deviceUUID         = 00000000-0000-0000-0000-000000000000
        driverUUID         = 00000000-0000-0000-0000-000000000000

here it is..

**Comment by Bendy3192** [comment]
> #147
> 
> https://github.com/catsout/wallpaper-engine-kde-plugin/blob/main/DEBUG.md
> 
> Please give me the log of `vulkaninfo --summary`.

Video-example of black screen [https://youtu.be/GRiDjr9X3E0](url)

**Comment by catsout** [comment]
Does your gpu support vulkan?

**Comment by Bendy3192** [comment]
> Does your gpu support vulkan?

Sorry, but I don't know

**Comment by catsout** [comment]
It seems not.  
Try this https://github.com/catsout/wallpaper-engine-kde-plugin/tree/02a6b516033c8960be8152eaca108272c1fe2040.  
It's an old opengl implementation.  
it's not maintained, but may work on your device.
