### ISSUE TITLE
Pls Help me to fix PKG 

### ISSUE THREAD

**Issue by otaku771** [catsout/wallpaper-engine-kde-plugin#172]
So try install pkg  everythink whas good but for somen reason  somthink fail  kf.package: Invalid metadata for package structure "Plasma/Wallpaper"
Package type "Plasma/Wallpaper" not found
kf.package: Invalid metadata for package structure "Plasma/Wallpaper"
kf.package: Cannot set a path in a package without structure "/home/matos/wallpaper-engine-kde-plugin/plugin"
kf.package: Invalid metadata for package structure "Plasma/Wallpaper"
Error: Plugin com.github.casout.wallpaperEngineKde is not installed.
make[3]: *** [CMakeFiles/install_pkg.dir/build.make:70: CMakeFiles/install_pkg] Error 2
make[2]: *** [CMakeFiles/Makefile2:592: CMakeFiles/install_pkg.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:599: CMakeFiles/install_pkg.dir/rule] Error 2
make: *** [Makefile:247: install_pkg] Error 2
So would have help from you guys im new bi linux so pls guys help me :c I  do me effor just get Wallpaper  Engine

**Comment by otaku771** [comment]
![image](https://user-images.githubusercontent.com/105669206/169102375-73a3d352-60a2-4d5a-8ae0-7a54c4761c6c.png)
JUst watch!

**Comment by catsout** [comment]
No way.  
This plugin is for kde.  
https://github.com/catsout/wallpaper-engine-kde-plugin#about-integrating-into-other-desktop-environments
