### ISSUE TITLE
Error text in journalctl when refreshing 

### ISSUE THREAD

**Issue by Weroxig** [catsout/wallpaper-engine-kde-plugin#173]
**Describe the bug*
Error text in journalctl when refreshing 
```
plasmashell[383306]: file:///usr/lib/qt/qml/org/kde/kirigami.2/PlaceholderMessage.qml:235:5: QML Heading: Binding loop detected for property "verticalAlignment"
plasmashell[383306]: qml: filtered, filter: , from 22 to 18
```
**Workshop link**<br/>
I think n/a for this problem

**System Information**
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.94.0
Qt Version: 5.15.4
Graphics Platform: Wayland
AMD graphics
Installed this program through kde store+AUR package

**Comment by catsout** [comment]
It's expected behavior.  
Dose it cause some problems?
