### ISSUE TITLE
White screen when using "Web" wallpapers on arch

### ISSUE THREAD

**Issue by remivamp** [catsout/wallpaper-engine-kde-plugin#178]
**Describe the bug**<br/>
White Screen when using "Web" wallpapers

**Workshop link**<br/>
Any "Web" ones, including the preinstalled "Corsair Collection" one

**System Information**
- Kde: 5.24.5
- Qt:  5.15.4
- OS: Arch
- Installation Source: Both

**Additional context**<br/>
I've used both rendering options. the only one that works is MPV rendering ONLY on video file backgrounds

**Comment by catsout** [comment]
Maybe this issue https://github.com/catsout/wallpaper-engine-kde-plugin/issues/44
