### ISSUE TITLE
Bug trying to compile the newest version on debian 11 (fixed myself)

### ISSUE THREAD

**Issue by gv3sys** [catsout/wallpaper-engine-kde-plugin#179]
It gives me this two errors
[CMakeOutput.log](https://github.com/catsout/wallpaper-engine-kde-plugin/files/8749181/CMakeOutput.log)
[CMakeError.log](https://github.com/catsout/wallpaper-engine-kde-plugin/files/8749183/CMakeError.log)

**Comment by catsout** [comment]
If you find a required dependency, please open a pr or note at here.
