### ISSUE TITLE
Wallpapers won't load, wall of text on kde desktop settings instead.

### ISSUE THREAD

**Issue by Ginxchan** [catsout/wallpaper-engine-kde-plugin#181]
Title. I install all the dependencies, followed the installations steps, error appears at make install_pkg, didn't realize that this was for kde desktop environment only, so I went on to install it, now error appears on sudo make install, missing plasma-wallpaper-addons, make sure to uninstall everything, install it again, no errors appear, but wall of text appears instead of wallpapers, yes the library is pointed towards the steam library where wallpaper engine is, uninstall everything, restart every time, I install it from get new plugins now, same thing.

**System Information**
- Kde: 5.24.4
- Qt: 5.15.3
- OS: Pop OS
- Hardware: Ryzen 5600x, Radeon 6700xt
- Installation Source: both plugin and git

**Additional context**
https://imgur.com/a/EQaPxu8

**Comment by Latrolage** [comment]
#162

**Comment by Ginxchan** [comment]
Thank you, that helped. 
For those that have the same issue run `apt install python3-pip` to run the pip command.
