### ISSUE TITLE
Ocean painting crashes plasmashell

### ISSUE THREAD

**Issue by CalivTPC** [catsout/wallpaper-engine-kde-plugin#182]
**Describe the bug**<br/>
When ever this image is applied plasmashell crashes.
Since wallpapers get loaded on login, plasmashell is unusable unless you somehow change the wallpaper.

**Workshop link**<br/>
[2607105555](https://steamcommunity.com/sharedfiles/filedetails/?id=2607105555)

**System Information**
- Kde: 5.24.5
- Qt: 5.15.4
- OS: Manjaro (Arch)
- Installation Source: git 

**Additional context**<br/>
![image](https://user-images.githubusercontent.com/55995344/171333041-5048d42f-8fc1-4f9b-bf9b-45a765eb043c.png)

**Comment by catsout** [comment]
As readme:  
Some scene wallpapers may crash your KDE.
Remove `WallpaperSource` line in `~/.config/plasma-org.kde.plasma.desktop-appletsrc` and restart KDE to fix.

**Comment by catsout** [comment]
Fixed.  
But this scene don't contains any shader file, maybe broken.
