### ISSUE TITLE
Remove limits on FPS limit value

### ISSUE THREAD

**Issue by SohryuLangleyAsuka** [catsout/wallpaper-engine-kde-plugin#183]
A fairly simple quality-of-life improvement for this program could be allowing the user to set arbitrary FPS limits.

At this point in time, the option only presents you with a 5-60 slider. However, some users, particularly those with more expensive hardware (for instance - a 120 Hz monitor), might want to reach higher frame-rates on scene-based wallpapers.

I propose that there should be an input box beside the slider to input out-of-range numeric values for the limit.

**Comment by catsout** [comment]
The scene fps is not the fps of your system.  
The scene is rendered in off-screen, it's not affect the desktop rendering. Just like you can get 120fps with a static image as background.  
'ultra high' setting in wallpaper engine is only 30fps, I think current 5-60fps is enough.

**Comment by Zoarial94** [comment]
@SohryuLangleyAsuka, I have felt similarly and just changed the source myself. If you are compiling it yourself, you can edit `plugin/contents/ui/page/SettingPage.qml` line 321 to whatever value you would like. I have been using like this for a few months at 175hz, and I have noticed no issues.
