### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by HIKKIAN** [catsout/wallpaper-engine-kde-plugin#187]
![Screenshot_20220615_191627](https://user-images.githubusercontent.com/107559147/173836298-b9ac3e9b-bffe-4621-b851-27b69e82ea6a.png)

**Comment by Jelgnum** [comment]
please add your system details (distro, KDE version, etc.) but from the way it looks that you are missing the websockets dependency. Please read over the README again to see how to acquire websockets for your distro

**Comment by AnaxMorden** [comment]
you can solve that issue by installing websockets

You can do this in Arch with: 'pacman -Syu python-websockets' 

Or with pip: 'pip install websockets'
