### ISSUE TITLE
screen timeout or lock crashes

### ISSUE THREAD

**Issue by zany130** [catsout/wallpaper-engine-kde-plugin#189]
**Describe the bug**<br/>
KDE crashes when wallpaper is set to wallpaper-engine and energy-saving settings kick in

**Workshop link**<br/>
any wallpaper

**System Information**
Operating System: Garuda Linux
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.95.0
Qt Version: 5.15.4
Kernel Version: 5.18.3-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 2600X Six-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT

- Installation Source: AUR  EDIT: specificly this one https://aur.archlinux.org/packages/plasma5-wallpapers-wallpaper-engine so the latest release 

**Additional context**<br/>
Add any other context about the problem here. [e.g. screenshots/logs]
[Journal06-15-22.log](https://github.com/catsout/wallpaper-engine-kde-plugin/files/8914671/Journal06-15-22.log)

**Comment by catsout** [comment]
What's the meaning of "energy-saving settings kick in"?  
The log is not helpful.

**Comment by zany130** [comment]
so as the title says there are energy saving settings in kde where after a user configurable time  has passed it will either lock the screen (and prompt the user to put in there password to login) or put the display to sleep or both if they are both 

when this happens kde crashes. I was capturing the log while I waited for the 1 minute screenlocker to take effect.

Running the same test with the wallpaper set to a solid color does not crash

**Comment by zany130** [comment]
Retested on kde 5.25 and a similar issue happens here. When the screen times out or is locked. When you get back in you do see your selected wallpaper (before it was just a black screen) but none of your open apps restore they are all missing (there still running as confirmation by an htop)

Not using wallpaper engine plugin (by selecting a ide built in wallpaper instead for example) does not cause this issue

**Comment by zany130** [comment]
Can no longer reproduce this issue on KDE 5.27
