### ISSUE TITLE
Only black wallpaper on Laptop with optimus manager.

### ISSUE THREAD

**Issue by Trqhxrd** [catsout/wallpaper-engine-kde-plugin#197]
**Describe the bug**<br/>
I only get a back wallpaper when trying to use the plugin.

**Workshop link**<br/>
[this](https://steamcommunity.com/sharedfiles/filedetails/?id=2389560319),
[this](https://steamcommunity.com/sharedfiles/filedetails/?id=1634002549) and
[this](https://steamcommunity.com/sharedfiles/filedetails/?id=2534352251)

**System Information**
- Kde: 5.25.1
- Qt: 5.15.5
- OS: Arch Linux
- Installation Source: Git Readme

**Additional context**<br/>
My Laptop has integrated graphics a(AMD Ryzen 5 5600H) and an NVIDIA RTX 3050 Ti Mobile. I set up optimus manager to switch between them when I want to play a game or render a scene in blender. I use the proprietary driver for nvidia (nvidia, nvidia-utils) and have amdvlk for vulkan installed (note that I just searched for "AMD vulkan" so I don't have any optional dependencies or other packages related to the amd-vulkan-driver installed)

**Comment by MarioCraftLP** [comment]
Same problem here.

**Comment by FuckingToasters** [comment]
Try to set a wallpaper with some white in it. I'm sure it'll be color inverted.

**Comment by Jelgnum** [comment]
can you not use the opensource vulkan-radeon drivers with optimus? If you can i would recommend trying to use it it over amdvlk

**Comment by Trqhxrd** [comment]
@Jelgnum I just ran `yay vulkan` and picked the first driver that was for AMD cards and that happened to be `amdvlk`. I can check if the other driver works.
