### ISSUE TITLE
When using the scene wallpaper, the wallpaper is blank, and switching to video wallpaper is normal

### ISSUE THREAD

**Issue by xiguayuyichao** [catsout/wallpaper-engine-kde-plugin#199]
**Describe the bug**<br/>

**Workshop link**<br/>
[e.g. 1139304621](https://steamcommunity.com/sharedfiles/filedetails/?id=1139304621)

**System Information**
- Kde: 5.25.2
- Qt: [e.g. 5.15]
- OS:Archlinux
- Installation Source: AUR

**Additional context**<br/>
Add any other context about the problem here. [e.g. screenshots/logs]

**Comment by xiguayuyichao** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **Workshop link** [e.g. 1139304621](https://steamcommunity.com/sharedfiles/filedetails/?id=1139304621)
> 
> **System Information**
> 
> * Kde:5.25.2
> * Qt: [e.g. 5.15]
> * OS: Arch Linux
> 
> **Additional context** Add any other context about the problem here. [e.g. screenshots/logs]

**Comment by xiguayuyichao** [comment]
![Uploading image.png…]()

**Comment by xiguayuyichao** [comment]
![image](https://user-images.githubusercontent.com/89023086/176589770-210f04bb-a73d-4e2e-9c17-7b64d5495a05.png)

**Comment by xiguayuyichao** [comment]
![Uploading image.png…]()

**Comment by xiguayuyichao** [comment]
![Uploading image.png…]()

**Comment by xiguayuyichao** [comment]
![image](https://user-images.githubusercontent.com/89023086/176589953-1d67cc0d-bd31-4ff9-959f-bc1fe67af996.png)

**Comment by xiguayuyichao** [comment]
![image](https://user-images.githubusercontent.com/89023086/176590156-f08520fd-85b9-4a88-8c58-cbe599ac9063.png)

**Comment by Jelgnum** [comment]
which aur package did you install?

**Comment by OstojaOfficial** [comment]
Apparently scenes do not work, but videos or images should work. I have similar or even same issue on my installation.

**Comment by OstojaOfficial** [comment]
This is definitely related to #193.

**Comment by OstojaOfficial** [comment]
Found a fix. #197

**Comment by xiguayuyichao** [comment]
> 您安装了哪个 aur 软件包？

Used  plasma5-wallpapers-wallpaper-engine But I later tried to use git, and the result was the same
我一开始使用了 plasma5-wallpapers-wallpaper-engine  但是我后来试了试git结果还是一个样子

**Comment by xiguayuyichao** [comment]
因为我的笔记本电脑是NVIDIA和Intel图形卡，所以我只安装了NVIDIA utils。事实上，我还需要安装vulkan intel，这就解决了这个问题

**Comment by xiguayuyichao** [comment]
Because my notebook is NVIDIA and Intel graphics card, I only installed  nvidia-utils . In fact, I also need to install  vulkan-intel , which solves the proble

**Comment by J4ckTh3R1pper** [comment]
I'm on Gentoo Linux with Intel Arc A750, got same issue and having vulkan-loader installed doesn't help.
