### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by ShayBox** [catsout/wallpaper-engine-kde-plugin#2]
I have the directory set and tried a few wallpapers but nothing loads, also compiled and installed the mpv video support but didn't change anything.

**Comment by catsout** [comment]
Please put your system info.  
Make sure you select video or web type wallpaper.  
And debug with [this](https://community.kde.org/Plasma/Debugging#Check_widgets_dynamically).  
Then put the log here.

**Comment by ShayBox** [comment]
[System](https://paste.nomsy.net/raw/hoqunuxuna)
None of them work, even picture ones
`file:///home/shaybox/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:109: TypeError: Cannot call method 'pause' of null` is the error

**Comment by catsout** [comment]
> None of them work, even picture ones  

Actually, there are not picture ones, the picture is scene type, which is not supported by this plugin currently.  

> TypeError: Cannot call method 'pause' of null

Seems like this error is caused by not select video or web type wallpaper.    
Or the backend not load correctly, and should have a error before this.  
I update the plugin, may help fix this.  
Try:
``` sh
git clone https://github.com/catsout/wallpaper-engine-kde-plugin.git
plasmapkg2 -u wallpaper-engine-kde-plugin/plugin
```
And put more log here, the log appeared after you click apply.

**Comment by ShayBox** [comment]
Updated, this is the entire log
[j.log](https://github.com/catsout/wallpaper-engine-kde-plugin/files/5985855/j.log)

**Comment by ShayBox** [comment]
And here's a different wallpaper that outputs the original error
[j.log](https://github.com/catsout/wallpaper-engine-kde-plugin/files/5985859/j.log)

**Comment by catsout** [comment]
> QML Image: Error decoding: file:///home/shaybox/.local/share/Steam/steamapps/workshop/content/431960/867791634/preview.jpg: Unsupported image format

Your qt doesn't supported jpg, or this file is broken?

**Comment by ShayBox** [comment]
When I turned my computer on today it started working, it showd the unsupported scene text and switching to a supported one works, I guess the update didn't apply from just the plasmapkg command

**Comment by catsout** [comment]
Yes, need restart plasmashell after update plugin. 

 >get to the setting menu

Just long press mouse left. You will see a toolbar apear, the "set desktop" is there.
