### ISSUE TITLE
Can't build with GCC11 on Fedora

### ISSUE THREAD

**Issue by Midniight12** [catsout/wallpaper-engine-kde-plugin#20]
Hello, 
the plugin does not compile with gcc11.
However, should I add #include <thread> or #include <cstddef>, it can be built, but the plugin still does not load. Without one of the includes it can only be built to this point:

> [13%] Build CXX object src/backend/scene/src/wallpaper/CMakeFiles/wallpaper.dir/SceneIndexArray.cpp.o                                               
> In file mounted from /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.cpp:1:
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:9:61: Error: "size_t" does not indicate a type
>     9 | SceneIndexArray(const uint32_t* data, const size_t count):m_pData(data),
>       | ^~~~~~
> 
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:4:1: Note: "size_t" is defined in the "<cstddef>" header; did you forget "#include <cstddef>"?
>     3 | #include <cstdint>
>   +++ |+#include <cstddef>
>     4 | 
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:26:17: Error: "size_t" does not indicate a type
>    26 | size_t DataSize() const { return m_count * sizeof(uint32_t); }
>       | ^~~~~~
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:26:17: Note: "size_t" is defined in header "<cstddef>"; did you forget "#include <cstddef>"?
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:28:17: Error: "size_t" does not indicate a type
>    28 | size_t DataCount() const { return m_count; }
>       | ^~~~~~
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:28:17: Note: "size_t" is defined in header "<cstddef>"; did you forget "#include <cstddef>"?
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:32:23: error: "size_t" does not denote a type
>    32 | const size_t m_count;
>       | ^~~~~~
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:32:23: Note: "size_t" is defined in header "<cstddef>"; did you forget "#include <cstddef>"?
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h: In constructor "wallpaper::SceneIndexArray::SceneIndexArray(const uint32_t*, int)":
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:10:129: Error: Class "wallpaper::SceneIndexArray" does not have field name "m_count".
>    10 | m_count(count) {
>       | ^~~~~~~
> 
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h: In constructor "wallpaper::SceneIndexArray::SceneIndexArray(wallpaper::SceneIndexArray&&)":
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:16:97: Error: class "wallpaper::SceneIndexArray" has no field name "m_count
>    16 | m_count(other.m_count) {
>       | ^~~~~~~
> 
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.h:16:111: Error: "class wallpaper::SceneIndexArray" has no element named "m_count".
>    16 | m_count(other.m_count) {
>       | ^~~~~~~
> 
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.cpp: In constructor "wallpaper::SceneIndexArray::SceneIndexArray(const std::vector<unsigned int>&)":
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.cpp:6:69: Error: class "wallpaper::SceneIndexArray" has no field name "m_count".
>     6 | ray::SceneIndexArray(const std::vector<uint32_t>& data):m_count(data.size()) {
>       | ^~~~~~~
> 
> /home/maokoe96/wallpaper-engine-kde-plugin/src/backend/scene/src/wallpaper/SceneIndexArray.cpp:9:35: Error: "DataSize" was not declared in this scope; did you mean "dataSize"?
>     9 | memcpy(newdata, &data[0], DataSize());
>       | ^~~~~~~~
>       | dataSize
> make[2]: *** [src/backend/scene/src/wallpaper/CMakeFiles/wallpaper.dir/build.make:199: src/backend/scene/src/wallpaper/CMakeFiles/wallpaper.dir/SceneIndexArray.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:454: src/backend/scene/src/wallpaper/CMakeFiles/wallpaper.dir/all] Error 2
> MAKE: *** [Makefile:149: all] Error 2
> 

**Kde version**
- Kde: 5.21.4
- Qt: 5.15
- OS: Fedora

**Comment by catsout** [comment]
Try latest commit.  
Need to restart plasmashell

**Comment by Midniight12** [comment]
This work with build, but libWallpaperEngineKde.so has still a segmentation fault (core dumped). :)

**Comment by catsout** [comment]
You mean it has segfault when you restart plasma?  
Or load a scene wallpaper?

**Comment by Midniight12** [comment]
It has only a segfault when i load the lib manually. It shows, when i load a scene wallpaper the Errormessage: plugin lib not found, scene support require to compile and install it. 

(the lib is installed to /com/github/catsout/wallpaperEngineKde/)

**Comment by catsout** [comment]
> It has only a segfault when i load the lib manually.

How do you load lib manually?

**Comment by catsout** [comment]
> /com/github/catsout/wallpaperEngineKde/

Is it full path?  
This shouldn't be under `/`  
Run `cat install_manifest.txt`, and put the result here.

**Comment by Midniight12** [comment]
i load the lib with ./
Here is the result:

[maokoe96@MAXIMUS build]$ cat install_manifest.txt
/com/github/catsout/wallpaperEngineKde/libWallpaperEngineKde.so
/com/github/catsout/wallpaperEngineKde/qmldir[maokoe96@MAXIMUS build]$

**Comment by catsout** [comment]
I think you need to install qmake  
And run `qmake -query QT_INSTALL_QML`, also put the result here.

**Comment by Midniight12** [comment]
[maokoe96@MAXIMUS build]$ qmake-qt5 -query QT_INSTALL_QML
/usr/lib64/qt5/qml

**Comment by catsout** [comment]
move `/com/github/catsout/wallpaperEngineKde`  
to `/usr/lib64/qt5/qml/com/github/catsout/wallpaperEngineKde`  
Should fix your problem  

The cmake need `qmake` to get install dir, but Fedora use `qmake-qt5`, so it's broken

**Comment by Midniight12** [comment]
Yes, it works :) Thanks :)

**Comment by Midniight12** [comment]
I change the execute_process from qmake to qmake-qt5. Fedora can recognize the right path and install it correctly. :)
