### ISSUE TITLE
HOW DO I INSTALL THE PLUGIN LIB?

### ISSUE THREAD

**Issue by birbrunner** [catsout/wallpaper-engine-kde-plugin#202]
please explain it to me as if i know nothing about linux or command lines -- because i don't. i just got a steam deck and I've been copying and pasting the commands from the instructions here and I've gotten far enough for my wallpapers to show up in the library list but they all just make my desktop say "plugin lib not found, please compile and install," with no information regarding to how to actually do that. so, how do i do that?

**Comment by catsout** [comment]
This plugin is not ready for steam deck, and probably keep this state for a long time.  
If you are not familiar with linux, I don't recommend you to try this plugin.

**Comment by birbrunner** [comment]
> This plugin is not ready for steam deck

oh okay. I just figured since it ran KDE on an Arch-based platform that it would be enough but like I said, I know very little about the inner workings of Linux or it's different variations, so fair enough lol. i appreciate the response, I'll definitely have to get some real educating about Linux before I try to start messing with it like this :)

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/177
