### ISSUE TITLE
fatal error when running make command

### ISSUE THREAD

**Issue by twurtleowo** [catsout/wallpaper-engine-kde-plugin#204]
![2022-07-21_19-22](https://user-images.githubusercontent.com/109772810/180349218-17e4c2ef-6010-4584-a7dc-3dd2d69b7964.png)
I'm sorry if this seems a bit dumb, but I'm new to linux and this stuff.
So when trying to run the `make` command, the things shown in the screenshot as seen above had occured. I don't know what else to say, sorry.

OS: Linux Mint 20.3 x86_64
Kernel: 5.4.0-122-generic
DE: Plasma
WM: Kwin
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
GPU: NVIDIA GeForce RTX 2070 Rev. A
Memory: 15927MiB

**Comment by Jelgnum** [comment]
Have you checked and made sure you had all the [Dependencies](https://github.com/catsout/wallpaper-engine-kde-plugin#dependencies) for Debian, if you are unsure running the Debian install command again won't hurt anything.
The only thing coming to mind is that you might be missing one.
If you have already tried my solution then you will probably have to wait for the dev to take a look

Thank you for coming and asking, this was a beautiful First Issue report with all the details you provided!

**Comment by catsout** [comment]
What's your gcc version?
You can get from `gcc --version`.

**Comment by twurtleowo** [comment]
![image](https://user-images.githubusercontent.com/109772810/180590068-080e56a6-1766-4d6f-a709-8a98b82e2fc4.png)
I'm actually about to perform a reinstall though for other reasons, but I'm going to try to reinstall this and see if its successful or not.

**Comment by twurtleowo** [comment]
![image](https://user-images.githubusercontent.com/109772810/180596082-53fe13c2-6c46-4494-bb31-f09c3600c24c.png)
after installing manjaro, i was able to go through all the steps perfectly fine with nothing going wrong.
