### ISSUE TITLE
Effect->Animation->Water Wave not working on my own creations

### ISSUE THREAD

**Issue by oweztrozoi** [catsout/wallpaper-engine-kde-plugin#209]
**Describe the bug**<br/>
Unable to display Effect->Animation->Water Wave, but only on my own creations. 
- Wallpapers I downloaded from the steamcommunity that (I think) use the same effect such as mine work just fine. 
- All Wallpapers work on Windows, however only [2172240292](https://steamcommunity.com/sharedfiles/filedetails/?id=2172240292) and [1827936575](https://steamcommunity.com/sharedfiles/filedetails/?id=1827936575) work on linux.
- [2841087493](https://steamcommunity.com/sharedfiles/filedetails/?id=2841087493) and [2841175631](https://steamcommunity.com/sharedfiles/filedetails/?id=2841175631)(created on Windows with only the Water Wave Effect for testing) do not work on linux. The first one just leaves out the effect, the second one leaves out the image with the effect altogether. I also tried out the versions I uploaded onto the Workshop on every OS.
- I tried restarting, reinstalling and clearing cache.

Could also be that the Water Wave Animation isn't supported, I am stupid, and the creators of the other wallpapers just used a different Animation, as it isn't listed in the [#supported](https://github.com/catsout/wallpaper-engine-kde-plugin/#supported) section, but it's neither listed as implemented, nor as not implemented.

**Workshop links**<br/>
- Not working#1: [2841087493](https://steamcommunity.com/sharedfiles/filedetails/?id=2841087493) (animated on linux)
- Not working#2: [2841175631](https://steamcommunity.com/sharedfiles/filedetails/?id=2841175631) (animated on windows)
- Working Example#1: [2172240292](https://steamcommunity.com/sharedfiles/filedetails/?id=2172240292)
- Working Example#2: [1827936575](https://steamcommunity.com/sharedfiles/filedetails/?id=1827936575)

**System Information**
- Kde: 5.24.4 
- Qt: 5.15.3
- OS: Kubuntu 22.04 LTS
- Installation Source: git

**Additional context**<br/>
Videos of the Wallpapers:

- Not working#1: [2841087493](https://steamcommunity.com/sharedfiles/filedetails/?id=2841087493)

- Working Example#1: [2172240292](https://steamcommunity.com/sharedfiles/filedetails/?id=2172240292)

https://user-images.githubusercontent.com/110124097/181348685-73331290-f64d-42ab-97e1-f532e0999147.mp4

- Working Example#2: [1827936575](https://steamcommunity.com/sharedfiles/filedetails/?id=1827936575)

https://user-images.githubusercontent.com/110124097/181348691-78e5909a-f853-4c0c-bd98-365c9e958825.mp4

**Comment by catsout** [comment]
Fixed.

**Comment by oweztrozoi** [comment]
Thanks a lot! Really appreciate this fast fix! Everything works now.

Thank you!
