### ISSUE TITLE
Found 124 wallpapers,but none of them matched filters

### ISSUE THREAD

**Issue by PFBZSC** [catsout/wallpaper-engine-kde-plugin#210]
**Describe the bug**<br/>
Found 124 wallpapers,but none of them matched filters

**System Information**
- Kde: [5.25.2]
- Qt: [5.15.5]
- OS: [Arch Linux x86_64]
- Installation Source: [Tried both]

**Additional context**<br/>*
(Sorry, my English is very poor. All the English below is machine translation. Please forgive me)

At first, I used git to install it once, and it could detect the wallpaper normally, but he prompted that there was no plugin lib, so I reinstalled it. This time, he prompted that there was plugin lib, but it could not detect the wallpaper normally,prompting "Found 124 wallpapers,but none of them matched filters". Later, I uninstalled and reinstalled it in the Discover of Arch,but it is still undetectable

By the way, there will be some problems with the normal downloaded version of my steam for some reasons. Later, I changed to the flatpak version. The directory of my steam has also changed from "/home/pfbzsc/.local/share/steam/" to "/home/pfbzsc/.var/app/com.valvesoftware.steam/.local/share/ steam/". I also changed it when I configured the plug-in. When I could detect the wallpaper normally at the beginning, I still used the normal version, However, I also tried to switch back to the normal version when there were problems later, but it was useless. I don't know whether it had anything to do with this

最开始我装用git装过一次，能正常检测到壁纸，但他提示我没有plugin lib,导致我只能播放视频和图片，pkg文件没法放，就重装了一次，重装之后就提示装上了，但选完steam文件夹之后没看到壁纸列表，只显示"Found 124 wallpapers,but none of them matched filters",重新卸载用git和arch的Discover(软件中心)安装都试了几次，全部以失败告终

顺带一提，我的steam因为某些原因正常下载的版本会出一些问题，后面我换成了flatpak的版本的，steam的目录也从"/home/pfbzsc/.local/share/Steam/"变到"/home/pfbzsc/.var/app/com.valvesoftware.Steam/.local/share/Steam/"，在我配置插件的时候我也跟着改了，在我最开始能正常检测到壁纸的时候用的还是正常版本，不过在后面出问题的时候我也试过换回正常版本，但没有用，不知道跟这有没有什么关系

![20220728195126](https://user-images.githubusercontent.com/64630558/181498658-81b00e90-abda-42ad-bcf3-acdae88c5778.png)

**Comment by catsout** [comment]
Please uncheck `favorite` filter

**Comment by PFBZSC** [comment]
The problem has been solved. Thank you very much. I didn't expect to make such a low-level mistake
