### ISSUE TITLE
Plugin Lib is not found

### ISSUE THREAD

**Issue by bacta-holic** [catsout/wallpaper-engine-kde-plugin#215]
**Describe the bug**<br/>
"Plugin lib not found" error on every single last scene I have
Upon installation I get the error...

```
Install the project...
-- Install configuration: "Release"
CMake Error at src/cmake_install.cmake:70 (file):
  file INSTALL cannot find
  "/home/myname/wallpaper-engine-kde-plugin/build/src/libWallpaperEngineKde.so":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)

```

**Workshop link**<br/>
Irrelevant, all scenes

**System Information**
- Kde: 5.20.5
- Qt: 5.15.2
- OS: MX Linux x86_64
- Installation Source: Both Discover and building from source

**Additional context**<br/>
libWallpaperEngineKde.so seems to be the problem, its the only file that is missing and the only error that is thrown at installation, downloaded a zip of the source and was unable to find the file, as far as I can tell it doesn't exist.

**Comment by catsout** [comment]
You need gcc 10+ to compile this lib.

**Comment by zcbxx** [comment]
I also encountered this problem, but I am the version of gcc13

**Comment by CryptoNyan** [comment]
I'm getting basically the same error as well, with some minor differences:

```
Install the project...
-- Install configuration: "RelWithDebInfo"
CMake Error at src/cmake_install.cmake:62 (file):
  file INSTALL cannot find
  "/home/username/Documents/wallpaper-engine-kde-plugin/build/src/libWallpaperEngineKde.so":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)
```

**System Info**
- GCC: 13.1.1-1 
- KDE Plasma: 5.27.5
- QT: 5.15.9
- OS: EndeavourOS x86_64

**Comment by zcbxx** [comment]
finally，i got a vesion of aur community，and you can try it
（yay -S plasma5-wallpapers-wallpaper-engine-git）
