### ISSUE TITLE
Can't install Lib for plugin

### ISSUE THREAD

**Issue by Wicctory** [catsout/wallpaper-engine-kde-plugin#216]
**Describe the bug**<br/>
Plugin asks me to install lib, but when i try to install them in terminal i spits some errors and i cant install it. Am i doing something wrong? 

**System Information**
- Kde: e.g. 5.25.3
- Qt: e.g. 5.15.5
- OS: e.g. KDE Neon
- Installation Source: KDE Plugins

**Additional context**<br/>
Logs:
wicctory@LINUXKUWA123:~$ git clone https://github.com/catsout/wallpaper-engine-kde-plugin.git
Cloning into 'wallpaper-engine-kde-plugin'...
remote: Enumerating objects: 7081, done.
remote: Counting objects: 100% (1128/1128), done.
remote: Compressing objects: 100% (388/388), done.
remote: Total 7081 (delta 734), reused 1026 (delta 711), pack-reused 5953
Receiving objects: 100% (7081/7081), 5.21 MiB | 7.57 MiB/s, done.
Resolving deltas: 100% (4395/4395), done.
wicctory@LINUXKUWA123:~$ cd wallpaper-engine-kde-plugin
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin$ mkdir build && cd build
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ cmake .. -DUSE_PLASMAPKG=ON
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Found KF5Package: /usr/lib/x86_64-linux-gnu/cmake/KF5Package/KF5PackageConfig.cmake (found version "5.96.0") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found KF5Plasma: /usr/lib/x86_64-linux-gnu/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.96.0") 
-- Found KF5: success (found suitable version "5.96.0", minimum required is "5.68.0") found components: Package Plasma 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'mpv'
--   Found mpv, version 1.107.0
CMake Error at src/backend_scene/third_party/CMakeLists.txt:11 (add_subdirectory):
  The source directory

    /home/wicctory/wallpaper-engine-kde-plugin/src/backend_scene/third_party/glslang

  does not contain a CMakeLists.txt file.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for module 'liblz4'
--   Found liblz4, version 1.9.2
-- Found Vulkan: /usr/lib/x86_64-linux-gnu/libvulkan.so  
-- Configuring incomplete, errors occurred!
See also "/home/wicctory/wallpaper-engine-kde-plugin/build/CMakeFiles/CMakeOutput.log".
See also "/home/wicctory/wallpaper-engine-kde-plugin/build/CMakeFiles/CMakeError.log".
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ cd ~
wicctory@LINUXKUWA123:~$ # Download source
wicctory@LINUXKUWA123:~$ git clone https://github.com/catsout/wallpaper-engine-kde-plugin.git
Cloning into 'wallpaper-engine-kde-plugin'...
remote: Enumerating objects: 7081, done.
remote: Counting objects: 100% (1128/1128), done.
remote: Compressing objects: 100% (388/388), done.
remote: Total 7081 (delta 734), reused 1026 (delta 711), pack-reused 5953
Receiving objects: 100% (7081/7081), 5.21 MiB | 7.65 MiB/s, done.
Resolving deltas: 100% (4395/4395), done.
wicctory@LINUXKUWA123:~$ cd wallpaper-engine-kde-plugin
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin$ 
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin$ # Download submodule (glslang)
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin$ git submodule update --init
Submodule 'src/backend_scene/third_party/glslang' (https://github.com/KhronosGroup/glslang.git) registered for path 'src/backend_scene/third_party/glslang'
Cloning into '/home/wicctory/wallpaper-engine-kde-plugin/src/backend_scene/third_party/glslang'...
Submodule path 'src/backend_scene/third_party/glslang': checked out 'c34bb3b6c55f6ab084124ad964be95a699700d34'
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin$ 
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin$ # Configure
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin$ # 'USE_PLASMAPKG=ON': using plasmapkg2 tool to install plugin
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin$ mkdir build && cd build
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ cmake .. -DUSE_PLASMAPKG=ON
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Found KF5Package: /usr/lib/x86_64-linux-gnu/cmake/KF5Package/KF5PackageConfig.cmake (found version "5.96.0") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found KF5Plasma: /usr/lib/x86_64-linux-gnu/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.96.0") 
-- Found KF5: success (found suitable version "5.96.0", minimum required is "5.68.0") found components: Package Plasma 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'mpv'
--   Found mpv, version 1.107.0
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Google Mock was not found - tests based on that will not build
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Checking for module 'liblz4'
--   Found liblz4, version 1.9.2
-- Found Vulkan: /usr/lib/x86_64-linux-gnu/libvulkan.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wicctory/wallpaper-engine-kde-plugin/build
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ 
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ # Build
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ make
[  1%] Building CXX object src/backend_scene/src/Utils/CMakeFiles/wpUtils.dir/Logging.cpp.o
In file included from /home/wicctory/wallpaper-engine-kde-plugin/src/backend_scene/src/Utils/Logging.cpp:1:
/home/wicctory/wallpaper-engine-kde-plugin/src/backend_scene/src/Utils/include/Utils/Logging.h:4:10: fatal error: span: No such file or directory
    4 | #include <span>
      |          ^~~~~~
compilation terminated.
make[2]: *** [src/backend_scene/src/Utils/CMakeFiles/wpUtils.dir/build.make:76: src/backend_scene/src/Utils/CMakeFiles/wpUtils.dir/Logging.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1927: src/backend_scene/src/Utils/CMakeFiles/wpUtils.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ 
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ # Install package (ignore if USE_PLASMAPKG=OFF for system-wide installation)
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ make install_pkg
Uaktualnianie pakietu z pliku: /home/wicctory/wallpaper-engine-kde-plugin/plugin
Pomyślnie unowocześniono /home/wicctory/wallpaper-engine-kde-plugin/plugin
Built target install_pkg
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ # install lib
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ sudo make install
[sudo] password for wicctory: 
Install the project...
-- Install configuration: "Release"
CMake Error at src/cmake_install.cmake:62 (file):
  file INSTALL cannot find
  "/home/wicctory/wallpaper-engine-kde-plugin/build/src/libWallpaperEngineKde.so":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)

make: *** [Makefile:100: install] Error 1
wicctory@LINUXKUWA123:~/wallpaper-engine-kde-plugin/build$ 

PS: I don't know i managed screw up even copying console output but ok

**Comment by Jelgnum** [comment]
Try running `gcc --version` and post your output, I suspect it might be to old of a version to compile this plugin

**Comment by catsout** [comment]
@Wicctory 
Please run `git submodule update --init` before cmake.
