### ISSUE TITLE
Can't get past cmake .. -DUSE_PLASMAPKG=ON

### ISSUE THREAD

**Issue by SkookyDoong** [catsout/wallpaper-engine-kde-plugin#217]
Linux and Arch noob here. When I try to execute the build entirely this happens

1)(deck@steamdeck ~)$ # Download source
git clone https://github.com/catsout/wallpaper-engine-kde-plugin.git
cd wallpaper-engine-kde-plugin

# Download submodule (glslang)
git submodule update --init

# Configure
# 'USE_PLASMAPKG=ON': using plasmapkg2 tool to install plugin
mkdir build && cd build
cmake .. -DUSE_PLASMAPKG=ON

# Build
make

# Install package (ignore if USE_PLASMAPKG=OFF for system-wide installation)
make install_pkg
# install lib
sudo make install
Cloning into 'wallpaper-engine-kde-plugin'...
remote: Enumerating objects: 7081, done.
remote: Counting objects: 100% (1128/1128), done.
remote: Compressing objects: 100% (388/388), done.
remote: Total 7081 (delta 734), reused 1026 (delta 711), pack-reused 5953
Receiving objects: 100% (7081/7081), 5.21 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (4395/4395), done.
Submodule 'src/backend_scene/third_party/glslang' (https://github.com/KhronosGroup/glslang.git) registered for path 'src/backend_scene/third_party/glslang'
Cloning into '/home/deck/wallpaper-engine-kde-plugin/src/backend_scene/third_party/glslang'...
Submodule path 'src/backend_scene/third_party/glslang': checked out 'c34bb3b6c55f6ab084124ad964be95a699700d34'
cmake: error while loading shared libraries: libjsoncpp.so.25: cannot open shared object file: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install_pkg'.  Stop.
[sudo] password for deck: 
make: *** No rule to make target 'install'.  Stop.
(2)(deck@steamdeck build)$

I'm assuming I can't get past the configure stage due to the cmake error, What do I do?
I'm also fairly certain that this might also be the reason why plugin lib remains unchecked on my lib checking list, as everything else is checked off from previous failed installs. However I can't be certain since I am fairly new to this.

**Comment by catsout** [comment]
steam deck is not supported.  
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/177
