### ISSUE TITLE
Error: source is empty. The config may be broken.

### ISSUE THREAD

**Issue by blake0812** [catsout/wallpaper-engine-kde-plugin#22]
**Describe the bug**
I directed to where my wallpapers are in the plugin but the plugin does not recognize any of it.

**Workshop link**
[e.g. 1139304621](https://steamcommunity.com/sharedfiles/filedetails/?id=1139304621)

**Kde version**
- Kde: 5.21.4
- Qt: 5.15.2
- OS: Kubuntu

**Additional context**

**Comment by catsout** [comment]
Where you select?
Do you have "qt-labs-folderlistmodel"(use apt search to find) installed?
Could you give me a screenshot of wallpaper setting window?

**Comment by blake0812** [comment]
Yes, it shows that it's installed. Here's a picture of the wallpaper setting window. https://imgur.com/c8AjJiH

**Comment by catsout** [comment]
There some thing wrong  
The `shopid` should be numbers, not `Desktop`  
The second wallpaper get wrong preview  

The plugin will go the folder `<steam library(you selected)>/steamapps/workshop/content/431960`  
and read `<folder>/*/project.json` to get each wallpaper info  

Please give me the log with [this](https://community.kde.org/Plasma/Debugging#Check_widgets_dynamically) or run `kquitapp5 plasmashell && kstart5 plasmashell`  
Note you should use the plugin to get useful log

**Comment by blake0812** [comment]
Nothing comes up in the log, says no errors. I pointed it back to my workshop folder but now nothing comes up.  https://imgur.com/a/eg6DhN9

**Comment by catsout** [comment]
Try the second way.  
Need to select steam library dir, not workshop dir.

**Comment by blake0812** [comment]
Yep, that did it. Turns out I was looking in the wrong directory, thanks so much!
