### ISSUE TITLE
Python error message when selecting plugin from dropdown in the settings

### ISSUE THREAD

**Issue by voltumna** [catsout/wallpaper-engine-kde-plugin#221]
**Describe the bug**<br/>
I have followed the instructions to the letter on a newly installed and updated kubuntu 22.04 LTS, then I logged out of KDE and logged in again.
I went to the "right-click"-> "configure desktop and background" and I selected the Wallpaper Engine for KDE and the screenshotted error appears. I tried to copy paste it but it does not allow me to select the error as text, sorry

**Workshop link**<br/>
[e.g. 1139304621](https://steamcommunity.com/sharedfiles/filedetails/?id=1139304621)

**System Information**
- Kde: 5.24.4
- Qt: 5.15.3
- OS: Kubuntu 22.04
- Installation Source: git

**Additional context**<br/>
![image](https://user-images.githubusercontent.com/1274922/184978238-4b373925-d66f-42f9-8bc1-554e0f9cf9f1.png)

I hope you can help and that it is just something that I missed,

thanks
Maurizio

**Comment by cpufreak** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/162

**Comment by voltumna** [comment]
Thank you, it worked!
