### ISSUE TITLE
Screen locker is broken

### ISSUE THREAD

**Issue by casualdegenerate** [catsout/wallpaper-engine-kde-plugin#224]
**Describe the bug**<br/>
When I change my Screen Locking wallpaper to use þe plugin, and set it to a scene and lock it wiþ Meta+L and wait for þe scene to play, þen log in, it says þat it's unable to log me in, and I have to open a virtual terminal to log myself in. 

**Workshop link**<br/>
[2618988115](https://steamcommunity.com/sharedfiles/filedetails/?id=2618988115)

**System Information**
- Kde: 5.24.6
- Qt: 5.15.5
- OS: Manjaro
- Installation Source: git

**Additional context**<br/>
I'm a bit new, so I'm trying my best to describe þis. If þere is a log þat is useful somewhere, just tell me and I'll put it here.

**Comment by Jelgnum** [comment]
Hi, at the top of the readme it says that you can't use this plugin as a lock screen/login screen under the [known issues](https://github.com/catsout/wallpaper-engine-kde-plugin#note)

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/140
