### ISSUE TITLE
Unable to "make" the plugin. No such file or directory

### ISSUE THREAD

**Issue by FumoVite** [catsout/wallpaper-engine-kde-plugin#228]
Hello, i am unable to "make" the plugin. Everything works up to that command, where it tells me "fatal error: span: no such file or directory". I already reinstalled all dependencies and updated cmake to version 3.24.

- Kde: 5.25.24
- Qt: 5.15.5
- OS: KDE neon 5.25
- Installation Source: git

Screenshots of the error message and neofetch:

![Screenshot_20220830_170555](https://user-images.githubusercontent.com/112498835/187474587-566e2098-363a-477f-bc29-267274b90b8b.png)
![Screenshot_20220830_170612](https://user-images.githubusercontent.com/112498835/187474593-af35aad5-ebc0-4eb7-a6ad-c9e1cec6df66.png)

**Comment by catsout** [comment]
Please install gcc 10+.

**Comment by FumoVite** [comment]
I believe i got it to work, had to use the command sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10.
gcc 10 was already installed but 9 was used in the command line

**Comment by FumoVite** [comment]
Nevermind now i get this error message when using the sudo make install command. make install-pkg didn't show any error messages.
![Screenshot_20220831_073048](https://user-images.githubusercontent.com/112498835/187599499-c5b067c9-7d0b-4451-a339-7c86b86b6478.png)
