### ISSUE TITLE
Kubuntu 20.04 is incompatible with this plugin

### ISSUE THREAD

**Issue by Zlendy** [catsout/wallpaper-engine-kde-plugin#23]
**Describe the bug**
This plugin needs QtMultimedia 5.13 but the latest version available in the repos is 5.12
![image](https://user-images.githubusercontent.com/22578704/117225218-1b900600-ae12-11eb-8e10-3219097dbf4b.png)
![image](https://user-images.githubusercontent.com/22578704/117225246-2a76b880-ae12-11eb-87a1-eb6a5f5a5e19.png)

**Kde version**
- Kde: 5.18.5
- Qt: 5.12.8
- OS: (k)Ubuntu 20.04

**Comment by catsout** [comment]
Sadly, QtMultimedia require 5.13 to play video looply without black screen.  
Try mpv instead.

**Comment by catsout** [comment]
Please go https://github.com/catsout/wallpaper-engine-kde-plugin/issues/125 to continue.
