### ISSUE TITLE
Fresh install doesn't work on kubuntu 22.04 lts

### ISSUE THREAD

**Issue by xescure** [catsout/wallpaper-engine-kde-plugin#239]
**Describe the bug**<br/>
Fresh install of the plugin throws a python error.

[screenshot](https://imgur.com/a/kp3WaUE)

**System Information**
- Kde: 5.24.4
- Qt: 5.15.3
- OS: Kubuntu 22.04 lts
- Installation Source: git (tried store as well)

**Additional context**<br/>
I have gotten this error on a laptop and a desktop as well. Both running this version of kubuntu.

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/162
