### ISSUE TITLE
cmake failure arch linux

### ISSUE THREAD

**Issue by notabot27** [catsout/wallpaper-engine-kde-plugin#24]
**Describe the bug**
CmakeSystem.cmake fails to execute (LOG FILE OUTPUT: The system is: Linux - 5.12.1-arch1-1 - x86_64)

**Workshop link**
n/a

**Kde version**
- Kde: [5.20]
- Qt: [5.15.2]
- OS: [Arch]

**Additional context**
[CMakeOutput.log](https://github.com/catsout/wallpaper-engine-kde-plugin/files/6445261/CMakeOutput.log)

**Comment by catsout** [comment]
Could you put the full output of `cmake ..`

**Comment by notabot27** [comment]
so cmake works after I tried again. but now im getting this error running the make command...

from /home/overlord/wallpaper-engine-kde-plugin/build/src/backend/mpv/mpvbackend_autogen/mocs_compilation.cpp:2:
/home/overlord/wallpaper-engine-kde-plugin/build/src/backend/mpv/mpvbackend_autogen/EWIEGA46WW/../../../../../../src/backend/mpv/mpvbackend.h:6:10: fatal error: mpv/client.h: No such file or directory
    6 | #include <mpv/client.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/backend/mpv/CMakeFiles/mpvbackend.dir/build.make:76: src/backend/mpv/CMakeFiles/mpvbackend.dir/mpvbackend_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:231: src/backend/mpv/CMakeFiles/mpvbackend.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by notabot27** [comment]
I managed to fix it myself. Sorry to waste your time.
