### ISSUE TITLE
Python helper run failed

### ISSUE THREAD

**Issue by huynp1999** [catsout/wallpaper-engine-kde-plugin#240]
**Describe the bug**<br/>
I installed from kde plugin, and this happened. I tried to upgrade python3-websocket to > 10.0, but nothing change
![image](https://user-images.githubusercontent.com/83684068/193380032-7fae6547-a522-4a9c-92c7-b7efd0f7dd53.png)

**System Information**
- Kde: 5.18.8
- Qt: 5.1
- OS: Ubuntu 20.04
- Installation Source: KDE Plugins

**Comment by catsout** [comment]
Please update the plugin to 0.5.4 or master branch.

**Comment by huynp1999** [comment]
> Please update the plugin to 0.5.4 or master branch.

Yes, I already at the master branch. After update to Ubuntu 22, the issue is gone.
