### ISSUE TITLE
package is marginal trust or corrupted 

### ISSUE THREAD

**Issue by TheFeri** [catsout/wallpaper-engine-kde-plugin#241]
**System Information**
Steam deck
- Installation Source: [KDE Plugins]

**Additional context**<br/>
So I installed it with the plugin thing and came here to get the dependecies and stuff copied the arch command but all I get is a key error that says

>  (48/48) checking package integrity                 [##################] 100% error: mujs: signature from "Daniel Bermond [danielbermond@gmail.com](mailto:danielbermond@gmail.com)" is marginal trust :: File /var/cache/pacman/pkg/mujs-1.2.0-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)). Do you want to delete it? [Y/n]

no matter what I choose because either way it doesn't installs anything so I can't get it to work. How can I fix this? I already tried to refresh the keys but I get the same thing either way.

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/177
