### ISSUE TITLE
Uninstallation of plugin lib

### ISSUE THREAD

**Issue by SubZeroNexii** [catsout/wallpaper-engine-kde-plugin#25]
I have installed the kde plugin and plugin lib to test it and I now want to uninstall everything from my system.
The kde plugin uninstalled fine through the kde plugin manager but I can't seem to find a way to uninstall plugin lib.
"sudo make uninstall" doesn't work. How am I supposed to do a clean uninstall?
Thanks

**Comment by catsout** [comment]
Cmake does not provide uninstall.
https://stackoverflow.com/questions/41471620/cmake-support-make-uninstall
