### ISSUE TITLE
Wallpapers broken after mpv update 0.35.0-2

### ISSUE THREAD

**Issue by Copysiper** [catsout/wallpaper-engine-kde-plugin#253]
**Describe the bug**<br/>
All scene wallpapers now showing text "Plugin lib not found. To support scene, please compile and install it."

**Workshop link**<br/>
Not wallpaper-specific

**System Information**
- Kde: 5.26.3
- Qt: 5.15.7
- OS: Arch Linux
- Installation Source: AUR

**Additional context**<br/>
Got this error just after reboot on the next day after updating mpv, also it is not displayed as an option in wallpaper settings anymore. Pretty sure it's mpv because i had the same error a few months ago when accidentally deleted mpv(installing mpv back fixed it, but that's not the case here i guess)

UPD: Got some info on "About" page, so i guess it's confirmed now

![image](https://user-images.githubusercontent.com/36638457/201986213-638d2c63-fedf-4311-9407-c86aab9cf533.png)

**Comment by Galcian79** [comment]
Same here.

**Comment by ETCHKILI** [comment]
same here

**Comment by ETCHKILI** [comment]
Everything work after **reinstalling**, hope it works for you

**Comment by Galcian79** [comment]
> Everything work after **reinstalling**, hope it works for you

Reinstalled both MPV and the plugin.
Same issue.

**Comment by Copysiper** [comment]
After reinstalling both mpv and rebuilding AUR package everything now seems to work

**Comment by Redbyte1** [comment]
I was unable to get mpv lib to work at all, I found that uninstalling the plugin didn't seem to remove it. I had files stuck under /usr/local/share/plasma and /usr/local/share/metainfo
Once these files were removed and I reinstalled from AUR (previously had been self compiling) it started working fine again.

**Comment by StonyTark1117** [comment]
Had the same issue after rebooting after updating. Fully removing the plugin and mpv and reinstalling worked for me.

**Comment by forggy0113** [comment]
after downgrade mpv to `0.34.1-5` works for me

**Comment by Galcian79** [comment]
> Had the same issue after rebooting after updating. Fully removing the plugin and mpv and reinstalling worked for me.

chaotic-AUR ships binary packages though. So uninstalling and reinstalling will do nothing.

**Comment by StonyTark1117** [comment]
> > Had the same issue after rebooting after updating. Fully removing the plugin and mpv and reinstalling worked for me.
> 
> chaotic-AUR ships binary packages though. So uninstalling and reinstalling will do nothing.

I don't use chaotic-AUR, I built the plugin from source and got mpv from the usual repos, chaotic-AUR used to give me lots of problems like this so I long since removed it from my system.

**Comment by dr460nf1r3** [comment]
The package has been rebuilt on Chaotic-AUR, so this should be fixed after an update! 😊

**Comment by Copysiper** [comment]
I guess this particular issue is "fixed" now(people got everything rebuilt and package in chaotic-aur got updated) so no reason to keep this issue in the list
