### ISSUE TITLE
wallpaper previews are replaced with python code 

### ISSUE THREAD

**Issue by mytricker0** [catsout/wallpaper-engine-kde-plugin#254]
I installed everything and that is the error I encounter:
![image](https://user-images.githubusercontent.com/58003204/202796879-9aec6abd-bb13-41e9-b434-2732bec2f3e3.png)

**Comment by Jelgnum** [comment]
Can you show the about tab?

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/162
