### ISSUE TITLE
Could we get a dependency command for Arch based distros?

### ISSUE THREAD

**Issue by TibixDev** [catsout/wallpaper-engine-kde-plugin#26]

**Comment by catsout** [comment]
I don't use arch based distro.  So I'm not sure about it.  
From https://github.com/catsout/wallpaper-engine-kde-plugin/issues/9, seems like `base-devel mpv qt5-declarative` are needed.   
If you figure out it, could you please make a pull request to add the dependency command on arch, or put the command here?

**Comment by ZerominerBR** [comment]
I run Arch Linux with KDE and to compile Plugin lib it is necessary to install mpv.
When you try to compile it without mpv:
```
In file included from /home/user/Downloads/wallpaper-engine-kde-plugin/build/src/backend/mpv/mpvbackend_autogen/EWIEGA46WW/moc_mpvbackend.cpp:10,
                 from /home/user/Downloads/wallpaper-engine-kde-plugin/build/src/backend/mpv/mpvbackend_autogen/mocs_compilation.cpp:2:
/home/user/Downloads/wallpaper-engine-kde-plugin/build/src/backend/mpv/mpvbackend_autogen/EWIEGA46WW/../../../../../../src/backend/mpv/mpvbackend.h:6:10: fatal error: mpv/client.h: No such file or directory
    6 | #include <mpv/client.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/backend/mpv/CMakeFiles/mpvbackend.dir/build.make:76: src/backend/mpv/CMakeFiles/mpvbackend.dir/mpvbackend_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:231: src/backend/mpv/CMakeFiles/mpvbackend.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by ZerominerBR** [comment]
> I don't use arch based distro. So I'm not sure about it.
> From #9, seems like `base-devel mpv qt5-declarative` are needed.
> If you figure out it, could you please make a pull request to add the dependency command on arch, or put the command here?

To install packages on Arch you use `pacman`:
`sudo pacman -S base-devel mpv qt5-declarative`
Sorry if I make any mistake on this, I'm not an expert by any means.

**Comment by catsout** [comment]
Thanks.
