### ISSUE TITLE
KDE crash when using 2 monitors

### ISSUE THREAD

**Issue by xerhaxs** [catsout/wallpaper-engine-kde-plugin#27]
Hi,
I have a problem with the wallpaper engine for KDE.
I can play and display all my wallpapers by itself. Everything runs without problem. However, I have 2 monitors. As soon as I select a background on one and want to do that on the other monitor, KDE crashes. I have tried all my wallpapers and with some it works and with others not. 
The common thing I have noticed is that if I use wallpapers that both use "scene.pkg", KDE crashes. However, if I use a wallpaper with "scene.pkg" and a wallpaper with e.g. "mp4" or "mkv" KDE does not crash.
I don't know exactly what the reason is. KDE outputs the following in the terminal as soon as I select the 2nd wallpaper with "scene.pkg": 

> qml: load backend: backend/Scene.qml
pkg version: PKGV0001
Warning read json: FromJson(27): cameraparallax not a key
Warning read json: FromJson(28): cameraparallaxamount not a key
Warning read json: FromJson(29): cameraparallaxdelay not a key
Warning read json: FromJson(30): cameraparallaxmouseinfluence not a key
Warning read json: FromJson(31): zoom not a key
3
Load tex RGBA8 masks/waterflow_mask_ee0d9bbc6d0516b8583c8fb3e841485c0b7ec4e8
Load tex RGBA8 effects/waterflowphase
Load tex RGBA8 util/noise
Load tex RGBA8 util/white
Load tex RGBA8 3
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
qrc:/plasma/plasmoids/org.kde.plasma.volume/contents/ui/ListItemBase.qml:231: TypeError: Cannot read property 'visible' of null
KCrash: Attempting to start /usr/bin/plasmashell
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = plasmashell path = /usr/bin pid = 17785
KCrash: Arguments: /usr/bin/plasmashell
kf.plasma.quick: Applet preload policy set to 1
qml: load backend: backend/Scene.qml
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
qml: load backend: backend/Scene.qml
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
pkg version: PKGV0001
Warning read json: FromJson(27): cameraparallax not a key
Warning read json: FromJson(28): cameraparallaxamount not a key
Warning read json: FromJson(29): cameraparallaxdelay not a key
Warning read json: FromJson(30): cameraparallaxmouseinfluence not a key
Warning read json: FromJson(31): zoom not a key
3
Load tex RGBA8 masks/waterflow_mask_ee0d9bbc6d0516b8583c8fb3e841485c0b7ec4e8
Load tex RGBA8 effects/waterflowphase
Load tex RGBA8 util/noise
Load tex RGBA8 util/white
Load tex RGBA8 3
Plasma Shell startup completed
Plasma Shell startup completed
Plasma Shell startup completed
pkg version: PKGV0002
Warning read json: FromJson(31): zoom not a key
wallhaven-205411
Load tex RGBA8 masks/shake_mask_ee0d9bbc6d0516b8583c8fb3e841485c0b7ec4e8
Load tex RGBA8 util/white
Load tex RGBA8 masks/shake_mask_681d95af21112ea41fc4cd51aa49d9c553ef1173
Load tex PNG wallhaven-205411
Error: cannot change the containment to AppletsLayout
Error: cannot change the containment to AppletsLayout
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

System info:
OS: Manjaro Linux
Kernel: 5.10.36
DE: Plasma 5.21.5
Qt: 5.12.2

On Kubunut I have the same problem - so it does not only apply to Arch-based distros.

**Comment by xerhaxs** [comment]
Sorry, I accidentally clicked on close. The problem still exists.

**Comment by catsout** [comment]
Seems like the commit message close this issue.  
Just reopen it, if the problem is still there.

**Comment by tonehrk** [comment]
I have the same problem. 
Yesterday everything was fine, in fact today in the morning everything was still fine ... until I tried to change the background and now I can't put any background type "scene" (not even the same as i had before). Only video and web type backgrounds. 

Crash info:
```
qml: load backend: backend/Scene.qml
pkg version: PKGV0002
Warning read json: FromJson(31): zoom not a key
Grass Lands
Warning read json: ParseWPShader(125): material not a key
Warning read json: ParseWPShader(125): material not a key
Warning read json: ParseWPShader(125): material not a key
Warning read json: ParseWPShader(125): material not a key
Warning read json: ParseWPShader(125): material not a key
Error at LoadMaterial(278): empty texture name
Error at LoadMaterial(278): empty texture name
_rt_MipMappedFrameBuffer
Load tex PNG masks/waterripple_mask_ee0d9bbc6d0516b8583c8fb3e841485c0b7ec4e8
Load tex RGBA8 effects/waterripplenormal
Load tex PNG masks/waterwaves_mask_681d95af21112ea41fc4cd51aa49d9c553ef1173
Load tex PNG masks/waterwaves_mask_843377ec5689457129ad9ee2dd9c051f084db05d
Load tex PNG masks/waterwaves_mask_bdbea347ab7838b0661ae6af118d7d24d301b354
Load tex PNG masks/waterwaves_mask_7bfb13f51be22746c08466c9bb8b3d1e108682d4
Load tex JPEG 3075_upscaled_illustartion_x2
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
KCrash: Attempting to start /usr/bin/plasmashell
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = plasmashell path = /usr/bin pid = 12118
KCrash: Arguments: /usr/bin/plasmashell 
kf.plasma.quick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:433:13: QML ToolButton: Binding loop detected for property "icon.height"
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:419:13: QML ToolButton: Binding loop detected for property "icon.height"
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:399:17: QML ToolButton: Binding loop detected for property "icon.height"
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:386:17: QML ToolButton: Binding loop detected for property "icon.height"
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:373:17: QML ToolButton: Binding loop detected for property "icon.height"
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:360:17: QML ToolButton: Binding loop detected for property "icon.height"
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:148:13: QML TextArea: Binding loop detected for property "implicitWidth"
qml: load backend: backend/Scene.qml
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
pkg version: PKGV0002
Warning read json: FromJson(31): zoom not a key
Grass Lands
Warning read json: ParseWPShader(125): material not a key
Warning read json: ParseWPShader(125): material not a key
Warning read json: ParseWPShader(125): material not a key
Warning read json: ParseWPShader(125): material not a key
Warning read json: ParseWPShader(125): material not a key
Error at LoadMaterial(278): empty texture name
Error at LoadMaterial(278): empty texture name
_rt_MipMappedFrameBuffer
Load tex PNG masks/waterripple_mask_ee0d9bbc6d0516b8583c8fb3e841485c0b7ec4e8
Load tex RGBA8 effects/waterripplenormal
Load tex PNG masks/waterwaves_mask_681d95af21112ea41fc4cd51aa49d9c553ef1173
Load tex PNG masks/waterwaves_mask_843377ec5689457129ad9ee2dd9c051f084db05d
Load tex PNG masks/waterwaves_mask_bdbea347ab7838b0661ae6af118d7d24d301b354
Load tex PNG masks/waterwaves_mask_7bfb13f51be22746c08466c9bb8b3d1e108682d4
Load tex JPEG 3075_upscaled_illustartion_x2
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

```

System info:
OS: Manjaro 21.0.6
Kernel: Linux 5.12.8-1
DE: Plasma 5.21.5
Qt: 5.15.2
Kde wallpaper engine: last commit.

**Comment by catsout** [comment]
> I have the same problem.
Yesterday everything was fine, in fact today in the morning everything was still fine ... until I tried to change the background and now I can't put any background type "scene" (not even the same as i had before). Only video and web type backgrounds.

Fixed. 
Need recompile and install.  
WallpaperEngine get a new version update which breaks this plugin.

**Comment by xerhaxs** [comment]
Hi,

I had the same bug. Thanks to your quick update it is fixed again. But now there is a new problem with scene backgrounds, for which I unfortunately have no logs, because nothing crashes.
The background is now upside down and also slipping and glitching around. (see screenshot)
Maybe you can fix this bug too.

Nothing has changed on the system.

Thanks.
![Screenshot 1](https://user-images.githubusercontent.com/82902107/121803535-70f5d900-cc42-11eb-9e9b-3efe07ab9951.png)
![Screenshot 2](https://user-images.githubusercontent.com/82902107/121803538-718e6f80-cc42-11eb-9feb-bc2c17b8cde3.png)

**Comment by catsout** [comment]
> The background is now upside down and also slipping and glitching around. (see screenshot)

I think you may need a reboot.

**Comment by xerhaxs** [comment]
Good idea, but I have already tried several times. Have also uninstalled, re-downloaded, compiled and installed. Did not help.
The bug occurs with all my scene wallpapers.
Graphics driver has not been changed or updated.

**Comment by catsout** [comment]
I don't get this problem. 
I think you can try set 1080p resolution with only one monitor and use steam to `Verify Integrity of Game Files` for WallpaperEngine.

**Comment by xerhaxs** [comment]
I tried it, but it does not help. I even just restored my system from an old backup and then updated - the bug remains. I continue to search for a solution. If I find one, I will post it here.

**Comment by catsout** [comment]
Should be fixed by new commit.

**Comment by xerhaxs** [comment]
Thanks, you fixed the bug.

**Comment by kreezxil** [comment]
the bug is back, what do you need from me to verify it?

**Comment by kreezxil** [comment]
hmm, doesn't appear to be wallpaper engine tho, simply activating picture of the day causes the problem too.

**Comment by Aikufurr** [comment]
Having `Wallpaper Engine for KDE` selected for multiple monitors causes a crash, in my case I have 2 1080p monitors with the same ratio.

Having one monitor set to WE type and one set to Stock Image type it doesn't crash but when they are both set to the WE type they crash upon plasmashell restart.

The crash doesn't occur when applying it but when plasmashell restarts (--replace, reboot, etc). 

Arch Linux 6.4.3-arch1-1
Plasma 5.27.6
AMD ATI Radeon RX 6700
