### ISSUE TITLE
No wallpapers available

### ISSUE THREAD

**Issue by Bubzzzz** [catsout/wallpaper-engine-kde-plugin#275]
I have installed the wallpaper engine for kde on endeavour os, however upon selecting the library folder it still says no wallpaper available. I have tried using the directory /.local/share/Steam and also /.steam/steam for the library folder. I have multiple wallpapers subscribed onto as i have been using it on windows for quite some time, so it should have atleast detected it. Kindly help me out if you can

**System Information**
- Kde: [e.g. 5.20] 5.26.5
- Qt: [e.g. 5.15] 5.15.8
- OS: [e.g. Debian] EndeavourOS (arch)
- Installation Source: [e.g. KDE Plugins or git] git

**Additional context**<br/>
![image](https://user-images.githubusercontent.com/72307002/213243184-f2704177-6f07-46cd-80d5-8893988f9c61.png)

**Comment by Jelgnum** [comment]
did you install wallpaper engine from steam?

**Comment by Bubzzzz** [comment]
well on linux the install button is greyed out in my library since steam says the app is available for windows only,
however my current workaround was i copied the complete steam folder from my windows drive and pasted it onto my linux one, and then changing the path to where i copied it I now have all the wallpapers available 
Pretty sure thats not how im supposed to do it tho

**Comment by Jelgnum** [comment]
to get windows games to run on linux you need to use the proton game layer to activate this you
1. right click on the game you want to enable it for
2. open up properties
3. click on compatibility
4. check the box that says "force the use of a specific Steam Play compatibility tool
5. then choose the most recent proton version or proton next
this will allow you launch most windows games on linux

You can also enable it for all supported games by going to steam settings>steamplay and checking the Enable steam play for supported titles

**Comment by Bubzzzz** [comment]
okay cool thank you for helping me out with this issue
