### ISSUE TITLE
make -j$nproc error 

### ISSUE THREAD

**Issue by Pudashu** [catsout/wallpaper-engine-kde-plugin#278]
**Describe the bug**<br/>
I've just updated my gcc version to 12.2 however when I do
`make -j$nproc`
There's a fatal error : span : No such a directory..
saying can't recognize `include <span>`
I think my gcc version is updated but still can't fix it. So what's the problem.

**System Information**
- Kde: [e.g. 5.18.8]
- Qt:5.12.8
- OS: Debian
- Installation Source: git

**Comment by Jelgnum** [comment]
you can run ```make```without the ```-j$nproc``` it will be slower but should still work

**Comment by Pudashu** [comment]
It still occurs however. I guess it's cuz my make setting wrong?

**Comment by Jelgnum** [comment]
ah I didn't notice but your qt version is also too old to run this, for this to work your qt needs to be 5.13 or newer

**Comment by Pudashu** [comment]
thx and I'll try it~
