### ISSUE TITLE
Cannot load module QtWebEngine on KDE 5.27

### ISSUE THREAD

**Issue by zany130** [catsout/wallpaper-engine-kde-plugin#280]
**Describe the bug**<br/>
Ever since I updated to kde 5.27 some wallpapers fail with attached error
**Workshop link**<br/>
https://steamcommunity.com/sharedfiles/filedetails/?id=2681264792

**System Information**
Operating System: Garuda Linux 
KDE Plasma Version: 5.27.2
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.2.1-273-tkg-bmq (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT
- Installation Source: [e.g. KDE Plugins or git]
AUR git package
**Additional context**<br/>
Add any other context about the problem here. [e.g. screenshots/logs]
![image](https://user-images.githubusercontent.com/25832539/222288702-a7f6c929-517e-4d88-8bde-57c1f1a29987.png)

```
sudo pacman -S  --needed extra-cmake-modules plasma-framework gst-libav \
           base-devel mpv python-websockets qt5-declarative qt5-websockets qt5-webchannel vulkan-headers cmake
warning: extra-cmake-modules-5.103.0-1 is up to date -- skipping
warning: plasma-framework-5.103.0-1 is up to date -- skipping
warning: gst-libav-1.22.0-4 is up to date -- skipping
warning: base-devel-1-1 is up to date -- skipping
warning: mpv-1:0.35.1-2 is up to date -- skipping
warning: python-websockets-10.4-1 is up to date -- skipping
warning: qt5-declarative-5.15.8+kde+r24-2 is up to date -- skipping
warning: qt5-websockets-5.15.8+kde+r3-1 is up to date -- skipping
warning: qt5-webchannel-5.15.8+kde+r3-1 is up to date -- skipping
warning: vulkan-headers-1:1.3.240-1 is up to date -- skipping
warning: cmake-3.25.2-1 is up to date -- skipping
 there is nothing to do
```
![image](https://user-images.githubusercontent.com/25832539/222290970-b901d0b1-0042-4350-935e-bd2bd9c76ca1.png)

Seems I am also running into https://github.com/catsout/wallpaper-engine-kde-plugin/issues/266

I tried installing and reinstalling from git and the aur several times

**Comment by haudiweg** [comment]
i have the same problem(s)
Arch linux

**Comment by Puqns67** [comment]
please try to update package `qt5-webengine` (recommended fully upgrade the system) and rebuild the package

I'm using `plasma5-wallpapers-wallpaper-engine-git`, it doesn't have "Plugin lib not found" issues

![image](https://user-images.githubusercontent.com/57405236/223409350-008de812-87e6-4d24-a803-1daa46319516.png)

**Comment by zany130** [comment]
I can't reproduce this as of a few days ago so it seems and update somewhere fixed it.
