### ISSUE TITLE
Can't build on TW

### ISSUE THREAD

**Issue by Kagaminator** [catsout/wallpaper-engine-kde-plugin#286]
When I run make -j$nproc it just fails with:

[ 60%] Built target glslang
[ 67%] Built target SPIRV
[ 67%] Building CXX object src/backend_scene/src/Vulkan/CMakeFiles/wpVulkan.dir/Vma.cpp.o
In file included from /home/bagration/wallpaper-engine-kde-plugin/src/backend_scene/src/Vulkan/Vma.cpp:2:
/home/bagration/wallpaper-engine-kde-plugin/src/backend_scene/third_party/vk_mem_alloc.h: In function ‘void VmaUint32ToStr(char*, size_t, uint32_t)’:
/home/bagration/wallpaper-engine-kde-plugin/src/backend_scene/third_party/vk_mem_alloc.h:2723:9: error: ‘snprintf’ was not declared in this scope
 2723 |         snprintf(outStr, strLen, "%u", static_cast<unsigned int>(num));
      |         ^~~~~~~~
/home/bagration/wallpaper-engine-kde-plugin/src/backend_scene/third_party/vk_mem_alloc.h:2562:1: note: ‘snprintf’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
 2561 |     #include <mutex>
  +++ |+#include <cstdio>
 2562 | #else
/home/bagration/wallpaper-engine-kde-plugin/src/backend_scene/third_party/vk_mem_alloc.h: In function ‘void VmaUint64ToStr(char*, size_t, uint64_t)’:
/home/bagration/wallpaper-engine-kde-plugin/src/backend_scene/third_party/vk_mem_alloc.h:2727:9: error: ‘snprintf’ was not declared in this scope
 2727 |         snprintf(outStr, strLen, "%llu", static_cast<unsigned long long>(num));
      |         ^~~~~~~~
/home/bagration/wallpaper-engine-kde-plugin/src/backend_scene/third_party/vk_mem_alloc.h:2727:9: note: ‘snprintf’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
/home/bagration/wallpaper-engine-kde-plugin/src/backend_scene/third_party/vk_mem_alloc.h: In function ‘void VmaPtrToStr(char*, size_t, const void*)’:
/home/bagration/wallpaper-engine-kde-plugin/src/backend_scene/third_party/vk_mem_alloc.h:2731:9: error: ‘snprintf’ was not declared in this scope
 2731 |         snprintf(outStr, strLen, "%p", ptr);
      |         ^~~~~~~~
/home/bagration/wallpaper-engine-kde-plugin/src/backend_scene/third_party/vk_mem_alloc.h:2731:9: note: ‘snprintf’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
make[2]: *** [src/backend_scene/src/Vulkan/CMakeFiles/wpVulkan.dir/build.make:188: src/backend_scene/src/Vulkan/CMakeFiles/wpVulkan.dir/Vma.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1924: src/backend_scene/src/Vulkan/CMakeFiles/wpVulkan.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Thanks in advance for any help

**Comment by Jelgnum** [comment]
can you specify what TW is?

**Comment by Kagaminator** [comment]
> can you specify what TW is?

Sorry, it meant Tumbleweed. However, this is now useless since that installation when nuts when I changed DE so I'm now back at Arch. Tried to delete the issue but I cant, if any admin can do it I'd appreciate it, in the meantime I'll be closing this.

**Comment by TheM1Stery** [comment]
I'm on  openSUSE Tumbleweed right now and have the same exact error. Is there a way to fix it? This plugin worked great on Kubuntu 22.10

**Comment by TheM1Stery** [comment]
Ok, the plugin built nicely after i added the necessary include in vk_mem_alloc.h.
