### ISSUE TITLE
All of my scenes are broken :(

### ISSUE THREAD

**Issue by Quittime** [catsout/wallpaper-engine-kde-plugin#29]
I've just downloaded the latest version of this plugin after the recent Wallpaper Engine update, and while it doesn't crash anymore, the scenes are all broken (although videos appear to be working fine). Also, along with updating Wallpaper Engine, I've also updated my Manjaro installation, so my Plasma desktop was updated as well. I will attach screenshots of some of my scenes so you know what I'm talking about. 

- Kde: 5.21.5
- Qt: 5.15.2
- OS: Manjaro 21.0.6

Also, thank you so much for making this plugin. I can't imaging how much skill, time, and dedication it must have taken. I really admire it and am very grateful for your work :)

![broken](https://user-images.githubusercontent.com/53710466/121822002-8398fe00-cc94-11eb-9957-d048173587d1.png)
![creepy](https://user-images.githubusercontent.com/53710466/121822005-84319480-cc94-11eb-9370-77b05a5dd71d.png)
![mini](https://user-images.githubusercontent.com/53710466/121822006-84ca2b00-cc94-11eb-8780-6535e2b8fcea.png)

**Comment by catsout** [comment]
Try new commit.

**Comment by Quittime** [comment]
Works fine now. Thanks
