### ISSUE TITLE
Python helper run failed: ... SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Arcticzomb** [catsout/wallpaper-engine-kde-plugin#290]
**Describe the bug**<br/>
This started happening out of nowhere and now even on fresh installs. I am consistently running into the error:

`Python helper run failed:
File "/home/me/.local/share/plasma/wallpapers/com.github.catsout.wallpaperEngineKde/contents/pyext.py", line 21
self.config_dir:Path = self.config_dir()
                                           ^
SyntaxError: invalid syntax`

**Workshop link**<br/>
[e.g. 1139304621](https://steamcommunity.com/sharedfiles/filedetails/?id=1139304621)
NA

**System Information**
- Kde: [5.27.4]
- Qt: [5.15.8]
- OS: [6.1.23-1-MANJARO (64-bit)]
- Installation Source: [git & kde plugins]

**Additional context**<br/>
Add any other context about the problem here. [e.g. screenshots/logs]

The wallpaper that has already been selected work just fine. I cannot select any new wallpapers through WallpaperEngine KDE

I have tried looking into the file and having a friend somewhat fluent in Python check it out. So far no luck on anything.
https://imgur.com/xZysMWQ

**Comment by Arcticzomb** [comment]
For extra detail, this still happens after a fresh install of the plugin

**Comment by burn2705** [comment]
same stuff here with plugin installed from kde plugins
is there still no solution for that error?

OS: Linux Mint 21.1 x86_64 
DE: Plasma 5.24.7 
installed from kde plugins

https://imgur.com/a/pml77VG

**Comment by burn2705** [comment]
> My error seems much different than yours. Since then, I’ve moved to arch and the problem resolved itself.

oh nvm, i found another one thread here that seems literally like mine,somehow github suggested it for me
