### ISSUE TITLE
Wallpaper seems to leak memory?

### ISSUE THREAD

**Issue by CorneliusCornbread** [catsout/wallpaper-engine-kde-plugin#293]
**Describe the bug**<br/>
Upon enabling this wallpaper after a while it becomes impossible to run anything through Krunner or the task manager giving the error:
"Resource error (fork failure): cannot allocate memory"

Happens regardless of QtMultimedia or MPV backend

**Workshop link**<br/>
[2477602742](https://steamcommunity.com/sharedfiles/filedetails/?id=2477602742)

**System Information**
- Kde: 5.27.4
- Qt: 5.15.9
- OS: Nobara (Fedora)
- Installation Source: git

**Comment by Jelgnum** [comment]
I tried replicating it on my machine (Arch, Let it run for 30 min and memory didn't change) with no success, sadly if it needs more time than what I tested tell me
the mpv/qt backend don't affect scene type wallpapers so we can rule them out of the equation

**Comment by CorneliusCornbread** [comment]
> I tried replicating it on my machine (Arch, Let it run for 30 min and memory didn't change) with no success, sadly if it needs more time than what I tested tell me the mpv/qt backend don't affect scene type wallpapers so we can rule them out of the equation

Something I noticed is that it didn't happen on my vertical 2k monitor, but it did on my landscape 2k monitor. What resolution and aspect ratio are you using?

**Comment by Jelgnum** [comment]
> What resolution and aspect ratio are you using?

I am also using 2k landscape 16:9, here's the settings page for my monitor maybe this can help narrow down if it is screen related
![image](https://user-images.githubusercontent.com/86729439/235180280-403b36e3-8d39-42a4-adcf-956dfdce71ad.png)

**Comment by CorneliusCornbread** [comment]
> > What resolution and aspect ratio are you using?
> 
> I am also using 2k landscape 16:9, here's the settings page for my monitor maybe this can help narrow down if it is screen related
> ![image](https://user-images.githubusercontent.com/86729439/235180280-403b36e3-8d39-42a4-adcf-956dfdce71ad.png)
> 

So you have display sync disabled. I assume you're on Wayland, I have it set to auto and I have a compatible display. I wonder if it's yet another bug in kwin

**Comment by Jelgnum** [comment]
Yeah, I am using wayland and left adaptive sync off because it use to mess with youtube videos and I haven't tested recently to see if that was fixed.

I just tested with Adaptive sync set to auto and still no real change in memory usage (500-600 mb for plasmashell)

The other difference with our systems is that I'm running an AMD gpu, but the creator of this plugin uses an Nvidia card.

So I think the issue probably lies between KDE and the gpu drivers if I had to guess

**Comment by CorneliusCornbread** [comment]
> Yeah, I am using wayland and left adaptive sync off because it use to mess with youtube videos and I haven't tested recently to see if that was fixed.
> 
> I just tested with Adaptive sync set to auto and still no real change in memory usage (500-600 mb for plasmashell)
> 
> The other difference with our systems is that I'm running an AMD gpu, but the creator of this plugin uses an Nvidia card.
> 
> So I think the issue probably lies between KDE and the gpu drivers if I had to guess

It's a possibility it has something to do with Mesa 23, as Nobara is using Mesa 23 drivers currently. Could be a regression, I could see if I can try to reproduce it on my NVIDIA/AMD(iGPU) hybrid graphics laptop but I have doubts if it would use the dGPU for desktop rendering.

**Comment by CorneliusCornbread** [comment]
Unable to reproduce this on my new installation of Fedora with the same wallpaper, though this wallpaper _does_ have issues with some audio not playing I'm assuming its due to not yet implemented features for audio. Closing this issue
