### ISSUE TITLE
Noise on the wallpaper

### ISSUE THREAD

**Issue by MrKamikazee** [catsout/wallpaper-engine-kde-plugin#295]
**Describe the bug**<br/>
I have noise on almost all wallpaper i have

**Workshop link**<br/>
https://steamcommunity.com/sharedfiles/filedetails/?id=1305429812
https://steamcommunity.com/sharedfiles/filedetails/?id=1607205505
https://steamcommunity.com/sharedfiles/filedetails/?id=1279921067

**System Information**
- Kde: 5.25.5
- Qt: 5.15.6
- OS: Feren OS (Debian)
- Installation Source: GitHub

**Additional context**<br/>
 Some images of my bug.

![Screenshot_20230502_234212](https://user-images.githubusercontent.com/64284557/235828870-2486dc6f-6092-4d58-831d-7a0e40ac8d32.png)
![Screenshot_20230502_234448](https://user-images.githubusercontent.com/64284557/235829083-d4801155-d497-4e16-8737-6c1eca080e20.png)
![Screenshot_20230502_234413](https://user-images.githubusercontent.com/64284557/235829088-86219324-22ee-4a48-a0eb-40879ef41586.png)

**Comment by Jelgnum** [comment]
which Nvidia driver are you using?

**Comment by MrKamikazee** [comment]
Correct, i downloaded all debian dependencies

**Comment by MrKamikazee** [comment]
I tried in on another PC with the same SO but different hardware and it worked, so i think the problem is the nvidia drives maybe.
Anyway, thanks.
