### ISSUE TITLE
Build error due to "#include <cstdio>" not being in the vk_mem_alloc.h file

### ISSUE THREAD

**Issue by Almos18** [catsout/wallpaper-engine-kde-plugin#299]
The error states 'snprintf' was not declared in this scope and suggests to include cstdio.

Including it in the file fixes this issue and builds normally, otherwise it wouldn't build for me. 

This happened on Opensuse Tumbleweed with all dependencies up to date in Packman.

**Comment by Redhawk18** [comment]
I have this issue on arch

**Comment by Almos18** [comment]
Did including cstdio fix it on Arch as well?

**Comment by TheM1Stery** [comment]
Use my fork https://github.com/TheM1Stery/wallpaper-engine-kde-plugin. I added the header file or you can add it yourself

**Comment by scrubborn** [comment]
I'm on Garuda and got the same error, and including cstdio in the file fixes it for me as well.

**Comment by SiyangShao** [comment]
On Arch Linux, include cstdio in the file fix it

**Comment by Almos18** [comment]
I'll close when the main branch gets updated with the include, unless there are other problems associated with doing this.

**Comment by Mariocraft95** [comment]
I don’t believe scene wallpapers work, but if you want a fix to this issue,

clone this GitHub instead; https://github.com/TheM1Stery/wallpaper-engine-kde-plugin

**Comment by SunRed** [comment]
I ran into this issue as well when I wanted to install this package on another machine. Since I maintain the (non-git) arch AUR package it would be really nice to just write there if such issues occur or even just write me an email or a message otherwise as this issue seemed to exist for some time now. I included the patch there now though.

**Comment by IgnacioRosas172** [comment]
I had the same problem, I fixed it, I added the library ` #include <cstdio>` in **vk_mem_alloc.h**, line 2721, **after** `#if VMA_STATS_STRING_ENABLED` and **before** `static inline void VmaUint32ToStr(char* VMA_NOT_NULL, after that I did -j$nproc again`.
That worked for me.

**Comment by AlphaCraft9658** [comment]
> I had the same problem, I fixed it, I added the library ` #include <cstdio>` in **vk_mem_alloc.h**, line 2721, **after** `#if VMA_STATS_STRING_ENABLED` and **before** `static inline void VmaUint32ToStr(char* VMA_NOT_NULL, after that I did -j$nproc again`.
> That worked for me.

I have cloned the fork with the fix applied in a comment above.
