### ISSUE TITLE
Automatically change in random order 

### ISSUE THREAD

**Issue by Naotomo2** [catsout/wallpaper-engine-kde-plugin#3]
Hello, I selected a folder "/home/naotomo/.local/share/Steam/steamapps/workshop/" and nothing happened. Then when I clicked on update and apply, the message "Error: source is empty. The config may broken." appeared on the desktop. But I am sure that the folder 431960 is not empty and it has video wallpapers (but not only them). Also i don't have "/steamapps/workshop/content/431960/" folder, but i have "/steamapps/workshop/downloads/431960/" folder. I tried to rename it, but it didn't help.
System: https://pastebin.com/y8Ji9Cnv   (it's arch-based)
Log: https://pastebin.com/DHBRLSEm

**Comment by catsout** [comment]
Seems like you have a broken `workshow/content/431960` dir.  
You may need clean your steam download cache, and reinstall wallpaper engine to download wallpaper correctly.  
Also I update the plugin to show unknown items in your case.

**Comment by Naotomo2** [comment]
Thank you! It's working now! Btw, are you planning to add a feature to automatically change the wallpaper in random order?

**Comment by unsatisfactory212** [comment]
Hello i am having the exact same error however it doesnt even save the directory after i input it, also i cant seem to get cmake to compile the code either (i have tried following your instruction and also tried using the cmake app to compile it but neither worked) also i am on manjaro

**Comment by catsout** [comment]
@unsatisfactory212  
What's your kde version?  
You need `qml-module-qt-labs-folderlistmodel`(may not be this name in manjaro) to use this plugin.  

You can use `journalctl /usr/bin/plasmashell` to get log especially after you select the steam library dir.  
If there is no log try `killall plasmashell && kstart5 plasmashell`, this will put log on you console   

Cmake part also need some packages to compile, you need to put the cmake or make error here.

**Comment by catsout** [comment]
By the way, better to open a new issue.

**Comment by dhruvrathod2000** [comment]
> @unsatisfactory212
> What's your kde version?
> You need `qml-module-qt-labs-folderlistmodel`(may not be this name in manjaro) to use this plugin.
> 
> You can use `journalctl /usr/bin/plasmashell` to get log especially after you select the steam library dir.
> If there is no log try `killall plasmashell && kstart5 plasmashell`, this will put log on you console
> 
> Cmake part also need some packages to compile, you need to put the cmake or make error here.

For arch kde users, 
1) just install the plugin from the tab 'Get new plugins..'  
2) sudo pacman -S base-devel mpv qt5-declarative
3) and then you can install the plugin lib using the normal method
```
cd wallpaper-engine-kde-plugin
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install
```

Atleast this worked for me :)
