### ISSUE TITLE
Desktop goes black when waking from sleep.

### ISSUE THREAD

**Issue by nick123456789025** [catsout/wallpaper-engine-kde-plugin#309]
**Describe the bug**<br/>
I am consistently seeing an issue where I close the lid of my laptop and that puts the laptop to sleep, when I reopen the laptop there is a 50% chance of the wallpaper being black and not working properly. I have tried multiple different wallpapers (scene wallpapers, MP4 looping wallpapers, and different effects).

When I reboot the laptop or log out and back in again it will usually spring back to life but it gets annoying to have to log out if I just want to open up my laptop and not have a black screen as my wallpaper, this issue doesn't seem to affect the performance of my laptop. I've tried installing it from git but I always end up with an error (Is there something that I'm missing?). I have successfully downloaded it from GitHub once I don't remember how, but I ended up with a error where plugin-lib would not show up even after a reboot, so I installed the one from the AUR. The plugin from the store fails to install for some reason.

Minor bug/Question:

Is there a way to get it to automatically switch between my GTX 1650 and my Intel UHD graphics or is it stuck on one or the other. If it is stuck on one of the other how can I configure it. 

**Workshop link**<br/>

https://steamcommunity.com/sharedfiles/filedetails/?id=1782924366

**System Information**

 Specs:

OS: Arch Linux

KDE Plasma Version: 5.27.6

KDE Frameworks Version: 5.107.0

Qt Version: 5.15.10

Kernel Version: 6.3.9-arch1-1 (64-bit)

Graphics Platform: X11

Hardware:

Processors: 8 x Intel® Core™ i5-10300H CPU @ 2.50GHz

Memory: 11.5 GiB of RAM

Graphics Processor: NVIDIA GeForce GTX 1650/PCIe/SSE2

Manufacturer: Acer 

Product Name: Nitro AN515-55

System Version: V2.06

Installation Source: KDE plugin (90% sure it's from the Chaotic AUR)

**Additional context**<br/>

I have tried a different video backend it results in the same bug. I also noticed one time when I opened my laptop and woke it from sleep, that there was a application crash and I think it was [something...] plasma but it disappeared before I could see what it was and I haven't seen it since. (it could be unrelated)

Let me know if there are any logs/screenshots you need and I'll provide them if I can. thx.

**Comment by jj11235** [comment]
Have you tried plasmashell --replace? It worked for me.
Maybe make a script and have it called on resume from suspend using kde settings.

**Comment by nick123456789025** [comment]
Where is that option located in KDE settings? I've looked and I can't seem to find it.

**Comment by nick123456789025** [comment]
Which option in here should I select? Because when I enter configure for application specific settings, there isn't any option for sleep. The closest thing I can find is in screensaver settings where you can add a script when you unlock from screensaver.

**Comment by jj11235** [comment]
When you click on configure for application settings, go to kwin window manager. Select configure events. Click on graphics reset and enter path to script you have created in 'run command' section.

**Comment by nick123456789025** [comment]
It worked. Thank you!

**Comment by jj11235** [comment]
No problem. Glad it worked
