### ISSUE TITLE
Plugin lib not found on arch shop id : 2420502639

### ISSUE THREAD

**Issue by Tbs116** [catsout/wallpaper-engine-kde-plugin#312]
Plugin lib not found on arch shop id : 2420502639
![2023-07-09_09-35](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/63025838/33b47c90-6ebe-4cd5-b805-3eab076f46ac)

**Comment by TheM1Stery** [comment]
Have you compiled the lib? If not, then clone this repo and install it. If you've installed it, then can you show me your installed libs?

Looks like this:
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/87154668/46f0ccff-3afd-45c9-96b4-4207c856808f)

**Comment by Tbs116** [comment]
您好，我会在看到邮件的第一时间回复您的，感谢您的理解！

    
        Hello, I will reply to you as soon as I see the email. Thank you for your understanding!

**Comment by Tbs116** [comment]
![2023-07-20_08-19](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/63025838/af48c301-1eb0-4134-9f52-1fada9a0683c)
wallpaper-engine-kde-plugin/src/backend_scene/third_party/vk_mem_alloc.h
This file of yours is missing a "#include <stdio.h>"?My problem has been solved.
You can see if this problem is an exception to rule him out.
Thank you.
