### ISSUE TITLE
Plugin lib not found

### ISSUE THREAD

**Issue by scgm0** [catsout/wallpaper-engine-kde-plugin#322]
**Describe the bug**<br/>
Plugin lib not found.

**Workshop link**<br/>
N/A

**System Information**
- Kde: 5.27.8
- Qt: 5.15
- OS: Arch
- Installation Source: KDE and git

**Additional context**<br/>
![图片](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/52148221/8fc28524-d253-4b1e-9bac-07d2c9897869)
![图片](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/52148221/4808da3c-d66b-491d-aa0c-0d4247808c2a)

**Comment by SolitaryAnimal** [comment]
The same is true for me. The Log shows `qml: ---check lib 'com.github.catsout.wallpaperEngineKde' failed---
` But my plug-in library is already installed
```
MiWiFi-CR5508-srv:/usr/lib64/qml/com/github/catsout/wallpaperEngineKde # ls -la
总计 104496
drwxr-xr-x 1 root root        60  9月22日 19:17 .
drwxr-xr-x 1 root root        36  9月22日 19:15 ..
-rwxr-xr-x 1 root root 106995752  9月22日 19:17 libWallpaperEngineKde.so
-rw-r--r-- 1 root root       151  9月22日 19:17 qmldir
```

**Comment by scgm0** [comment]
> The same is true for me. The Log shows `qml: ---check lib 'com.github.catsout.wallpaperEngineKde' failed--- ` But my plug-in library is already installed
> 
> ```
> MiWiFi-CR5508-srv:/usr/lib64/qml/com/github/catsout/wallpaperEngineKde # ls -la
> 总计 104496
> drwxr-xr-x 1 root root        60  9月22日 19:17 .
> drwxr-xr-x 1 root root        36  9月22日 19:15 ..
> -rwxr-xr-x 1 root root 106995752  9月22日 19:17 libWallpaperEngineKde.so
> -rw-r--r-- 1 root root       151  9月22日 19:17 qmldir
> ```

It's a problem with the latest mpv repository from the official repository, mpv-git on aur doesn't work either, I switched to mpv-build-git and it worked fine.
![图片](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/52148221/bf163102-5dc1-4f79-bf54-cdd9b8bea08d)
