### ISSUE TITLE
Ignore this

### ISSUE THREAD

**Issue by paul-hansen** [catsout/wallpaper-engine-kde-plugin#325]
# Please stop posting "me too" comments!
This is affecting everyone, additional "me too" comments will just make it hard to see any progress. Use the thumbs up on this post instead to indicate you are affected.

**Describe the bug**<br/>
New version of wallpaper engine that I just got today breaks most wallpapers. Switching to "previous - old release" in steam betas makes them work again.

**Workshop link**<br/>
Broken Visuals:
[2986110249](https://steamcommunity.com/sharedfiles/filedetails/?id=2986110249)
[3019953777](https://steamcommunity.com/sharedfiles/filedetails/?id=3019953777)
[2999751447](https://steamcommunity.com/sharedfiles/filedetails/?id=2999751447)
and many more

Found a few that do still work with new version [some need mpv player in settings]:
[916349467](https://steamcommunity.com/sharedfiles/filedetails/?id=916349467)
[2665358406](https://steamcommunity.com/sharedfiles/filedetails/?id=2665358406)
[1590968469](https://steamcommunity.com/sharedfiles/filedetails/?id=1590968469)

**System Information**
- Kde: `5.27.8`
- Qt: `5.15.10`
- OS: `EndeavorOS`
- Installation Source: [Arch aur](https://aur.archlinux.org/packages/plasma5-wallpapers-wallpaper-engine)

**Additional context**<br/>
Possible this is the same issue as https://github.com/catsout/wallpaper-engine-kde-plugin/issues/308 as it looks the same, effects work but background image/video is just light gray. The new version of wallpaper engine causing it for me doesn't exactly line up though because it just happened 2 hours ago according to https://steamdb.info/app/431960/

Thanks for making this! It's been working great!

**Comment by Edward-EH-Holmes** [comment]
Hey guy. you are right. And I found: after the wallpaper engine is updated, the scene wallpaper can no longer be used. So I have no choice but tu use video paper.
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/124123303/a4efe0bf-acbb-453f-b227-72c8395cdf6b)

**Comment by hydridity** [comment]
Confirming the issue too on following system:
```
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.10
Kernel Version: 6.1.55 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600G with Radeon Graphics
Memory: 31,2 GiB of RAM
Graphics Processor: AMD Radeon RX 6800 XT
```

Before this latest wallpaper engine update (2.3) scenes and also other types both video and web worked flawlessly, after wallpaper engine update scenes are rendering particles only and everything else is gray
Video and web types still do work.

**Comment by nullptroma** [comment]
+
same

Operating System: openSUSE Tumbleweed 20230926
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.4-1-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × 11th Gen Intel® Core™ i7-11700F @ 2.50GHz
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B560M AORUS ELITE

**Comment by hydridity** [comment]
I've tried running the standalone sceneviewer against wallpaper engine assets from 2.2.18 version with combination of scene files of 2.3 and scene renders correctly
Using assets from 2.3 update does not work

There has been probably some change in wallpaper engine assets.

**Comment by Impasse52** [comment]
Same here. Particles and rays of light (?) are being rendered but everything else is just gray (#B2B2B2).

Operating System: Fedora Linux 38
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.5.5-200.fc38.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series
Manufacturer: Micro-Star International Co., Ltd
Product Name: MS-7C02
System Version: 1.0

**Comment by VanoMajukin** [comment]
Same here.

Operating System: Alt linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.5-un-def-alt1
Graphics Platform: X11
Processors: AMD Ryzen 5 2600 (12) @ 3.400GHz 
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2060 SUPER and NVIDIA GeForce GTX 1050 Ti
Manufacturer: Asrock
Product Name: b450 pro4

**Comment by nullptroma** [comment]
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/64524860/79b6f03b-0f7b-4120-ac18-7c5a6c9aeb10)
Rolling back to the previous version fixes everything. But a fix is still needed

**Comment by paul-hansen** [comment]
Thanks to everyone for confirming! I think it's safe to say it's due to the Wallpaper Engine update and is affecting everyone. Probably don't need more confirmations at this point. Thumbs up the original post to show support.

I made a diff of the changes in my `~/.local/share/Steam/steamapps/common/wallpaper_engine` directory when I switch from `previous` to `none` in the betas on Steam. It might help someone see what's changed that needs supported.
[patch_we.txt](https://github.com/catsout/wallpaper-engine-kde-plugin/files/12771264/patch_we.txt)
This was made using `git diff --cached > patch_we.txt` and can be viewed as text or using `cat > delta` if you have [Delta](https://github.com/dandavison/delta) installed (allows side by side viewing and searching/highlighting).

**Comment by hydridity** [comment]
Difference I immediately notices, is in the genericimage2 color handling

```
Wallpaper engine 2.2.18
---
uniform float g_Alpha;
uniform vec3 g_Color;

vs

Wallpaper Engine 2.3
---
uniform vec4 g_Color4;
```

and then

```
Wallpaper engine 2.2.18
---
#ifndef VERSION
	color.rgb *= g_Brightness;
	color.a *= g_UserAlpha;
#else
	color.rgb *= g_Color;
	color.a *= g_Alpha;
#endif

vs

Wallpaper Engine 2.3
---
#ifndef VERSION
	color.rgb *= g_Brightness;
	color.a *= g_UserAlpha;
#else
	color *= g_Color4;
#endif
```

**Comment by AgentLoneStar007** [comment]
I have the same issue. Just a light gray image when trying to use scenes.

Operating System: Arch Linux
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.5.arch1-1
Graphics Platform: X11
Processors: AMD Ryzen 7 5800x
Memory: 32 GB
GPU: AMD Radeon 7800 XT

**Comment by Amaderis** [comment]
Exactly the same problem. All the wallpaper has turned gray.

**Comment by 96jaco96** [comment]
i want to add to this: it's more than just gray screens and such: KDE completely crashes.
At least the plasmashell.
And also if you use it in the login screen it breaks that too.

**Comment by hydridity** [comment]
> i want to add to this: it's more than just gray screens and such: KDE completely crashes. At least the plasmashell. And also if you use it in the login screen it breaks that too.

Using it as login screen is listed as known issue and is not supported as per readme:
> Screen Locking is not supported, please not use this plugin in screen locking.

**Comment by paul-hansen** [comment]
@96jaco96 It has always crashed if I used it on the login screen. Just don't use it for the login screen in my experience. Consider opening a separate issue when you have a problem that doesn't match the description of the issue you are posting in.

**Comment by 96jaco96** [comment]
> > i want to add to this: it's more than just gray screens and such: KDE completely crashes. At least the plasmashell. And also if you use it in the login screen it breaks that too.
> 
> Using it as login screen is listed as known issue and is not supported as per readme:
> 
> > Screen Locking is not supported, please not use this plugin in screen locking.

ok but besides that: it crashes the whole plasma shell even when used normally.... 

the cursor works and i can even launch programs with ulauncher or open folders, but the background and panels are gone, all black.

**Comment by paul-hansen** [comment]
Sounds like not the same problem I reported? Why are you commenting about it here and not in a new issue?

I'm unsubscribing from this issue, all the notifications are getting annoying.
