### ISSUE TITLE
Wallpaper engine update 2.3 breaking change resulting in gray scene

### ISSUE THREAD

**Issue by hydridity** [catsout/wallpaper-engine-kde-plugin#327]
Latest wallpaper engine update 2.3 introduces breaking changes, scenes wont longer render properly and result in gray image

Web and Video wallpapers should be working as usual.

**All system variations affected**
**Do not post comments of type me too with your system configuration, yes it does affect everybody, if you want, do react on this post**

Some of the assets got updates, one change I've noticed is:

```
Wallpaper engine 2.2.18
---
uniform float g_Alpha;
uniform vec3 g_Color;

vs

Wallpaper Engine 2.3
---
uniform vec4 g_Color4;
```

and then

```
Wallpaper engine 2.2.18
---
#ifndef VERSION
	color.rgb *= g_Brightness;
	color.a *= g_UserAlpha;
#else
	color.rgb *= g_Color;
	color.a *= g_Alpha;
#endif

vs

Wallpaper Engine 2.3
---
#ifndef VERSION
	color.rgb *= g_Brightness;
	color.a *= g_UserAlpha;
#else
	color *= g_Color4;
#endif
```

Some changes in scene and assets parsing is needed.

**Current workaround is**:
Use older version of wallpaper engine
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/64524860/79b6f03b-0f7b-4120-ac18-7c5a6c9aeb10)

**Comment by Xnoahg** [comment]
thank you, i'd been messing around with everything i could think of trying to fix this

**Comment by kamikaze211** [comment]
Thank you very much, it works again!

**Comment by joshrandall8478** [comment]
Choosing previous beta version works for me, thank you :)

**Comment by kodatarule** [comment]
I've had similar experience, but my image went either gray or red depending on the wallpaper I chose ...

**Comment by hydridity** [comment]
Long term workaround would be to copy old version of wallpaper assets to separate folder and then point the plugin to that folder.

Folder has to follow steamapps structure, so copy entire steamapps folder somewhere, leave only subfolders: workshop and common

in workshop folder leave, content/431960
in common leave: wallpaper_engine

everything else can be deleted as for other apps from steam not to take unnecessary space

So final structure would be:

```
steamapps/common/wallpaper_engine/
├── assets
├── bin
├── config_backups
├── distribution
├── locale
├── plugins
├── projects
├── thirdparty
└── ui
steamapps/workshop/content
├── 241100
├── 250820
├── 410900
└── 431960
```

This way you can freeze your wallpaper engine assets on the old working version before this get's fixed.
I'm trying to fix this in my free time, but I have no estimate at all.

**Comment by mytricker0** [comment]
it worked thanks

**Comment by slynobody** [comment]
thus this plugin seems to be independent widely from the windows-package itself. thus updates to this package are complicating the kde-plugin process. you dont even need the bought app to be installed for the kde-plugin to work. just placing such a folder in a rudimentary mimicing folder-skeleton of a installation in your steam library should get the kde-plugin also to work.

**Comment by fililip** [comment]
I think we can close this now (can someone other than me try it out to see if it works for them?)

**Comment by hydridity** [comment]
> I think we can close this now (can someone other than me try it out to see if it works for them?)

After building backend against commit: 08dad16f5cbf0de423b85edda313597c273a887e

I do confirm functionality on my end too.
**Scenes should now be rendering properly against Wallpaper Engine 2.3.x assets**

I pointed the plugin workshop library back to the steam "upstream", let wallpaper engine to update it's assets and scenes, and I've tested running wallpaper scenes I had previously downloaded and I've also tried to download random scene that was added to workshop recently, in both cases scenes rendered properly.

Thank you @fililip for solving this out.

**Comment by kamikaze211** [comment]
> I think we can close this now (can someone other than me try it out to see if it works for them?)

Yep, many thanks.
I recompiled, now everything worked fine with my pc.

**Comment by fxzjshm** [comment]
Sorry to disturb, I've further changed the related code to set opacity correctly for some scenes, could you please check if this breaks your scenes? Thanks.

**Comment by hydridity** [comment]
@fxzjshm I'm running with latest commits, in my case it did not break any scenes.

I've discovered some scenes are not rendered properly, shortly after I closed this issue and after running them with your last changes it did not fix them either, there are probably some other assets still in need of updating

I'll do further investigation later.
