### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by Miyazono1** [catsout/wallpaper-engine-kde-plugin#33]
**Describe the bug**
none of the wallpapers actually apply and show. the plugin lib is installed, but scene wallpapers still say it's not installed, but web and video wallpapers don't work either, they only show a black screen.

**Kde version**
- Kde: 5.22.3
- Qt: 5.15.3
- OS: Neon

**Comment by catsout** [comment]
Try:  
`journalctl /usr/bin/plasmashell` or 
`kquitapp5 plasmashell && kstart5 plasmashell`  
to get log.

**Comment by Miyazono1** [comment]
> Try:
> `journalctl /usr/bin/plasmashell` or
> `kquitapp5 plasmashell && kstart5 plasmashell`
> to get log.

the first just outputs to the console, and i'm not sure how to get the file so i can send it here.

**Comment by no95typem** [comment]
> > Try:
> > `journalctl /usr/bin/plasmashell` or
> > `kquitapp5 plasmashell && kstart5 plasmashell`
> > to get log.
> 
> the first just outputs to the console, and i'm not sure how to get the file so i can send it here.

For example:

```
journalctl /usr/bin/plasmashell > journalctl.log
kquitapp5 plasmashell && kstart5 plasmashell > plasma.log
```

If you execute this commands, two text files 'journalctl.log' and 'plasma.log' will be created in your home directory.

**Comment by Miyazono1** [comment]
ahh i got it. thanks!
[journalctl.log](https://github.com/catsout/wallpaper-engine-kde-plugin/files/6844853/journalctl.log)
[plasma.log](https://github.com/catsout/wallpaper-engine-kde-plugin/files/6844854/plasma.log)

**Comment by catsout** [comment]
It's sad that I can't figure out the key error.  
Could you do as the follow to get a clearer log:  

switch to another wallpaper plugin  
run `kquitapp5 plasmashell && kstart5 plasmashell > ~/plasma.log 2>&1`  
switch to this wallpaper plugin, select some thing, and apply.  
run `kquitapp5 plasmashell && kstart5 plasmashell` again.  
get the log

**Comment by catsout** [comment]
Close as no reply.
