### ISSUE TITLE
Latest Arch Linux plasma update broke Scene Wallpapers

### ISSUE THREAD

**Issue by AlecHCodes** [catsout/wallpaper-engine-kde-plugin#334]
**Describe the bug**<br/>
Says it in the title

**Workshop link**<br/>
Ex.
[1892162386](https://steamcommunity.com/sharedfiles/filedetails/?id=1892162386)

**System Information**
- Kde: 5.27.9
- Qt: 5.15.11
- OS: Arch Linux
- Installation Source: git

**Additional context**<br/>
Don't think this is related to 2.3 update regarding scenes (#327) 
Here's a screenshot:
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/87393142/92ca93ad-5bd2-4a3e-8469-2074935cb8ba)

**Comment by fililip** [comment]
Strange, I can't seem to be able to reproduce this on Plasma/KWin Wayland 5.27.9.

Assuming you're already on WE 2.3, could you try removing all locally stored wallpapers and redownloading them?
