### ISSUE TITLE
The Plugin does not work with Plasma 6 alpha

### ISSUE THREAD

**Issue by RedStarITA** [catsout/wallpaper-engine-kde-plugin#339]
**Describe the bug**<br/>
Trying to install extension from the wallapaper extension store says it can't find the metadata file

**System Information**
- Kde: 6 alpha
- Qt: 5.15.11, 6.6.0
- OS: Arch Linux
- Installation Source: KDE Plugins, AUR

**Additional context**<br/>
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/84195953/9b50ed42-d820-4df2-9980-e4abdb51807b)

**Comment by kamikaze211** [comment]
A lot of thing in Plasma 6 alpha cannot work.
Such as applets, widgets themes, etc.
Maybe we need to wait Plasma 6 to fix theme.
