### ISSUE TITLE
Doesn't work when Wallpaper Engine is installed on separate hard drive

### ISSUE THREAD

**Issue by OneSons** [catsout/wallpaper-engine-kde-plugin#37]
**Describe the bug**
I installed Wallpaper Engine to my 2nd drive and pointed the plugin to the directory, but no wallpapers show up.

**Kde version**
- Kde: 5.21.4
- Qt: 5.15.2
- OS: Pop_OS 21.04

**Comment by catsout** [comment]
This plugin will load the wallpaper in `<your steam library>/steamapps/workshop/content/431960` directory.  
Make sure your wallpaper is installed

**Comment by zhairuiyao15** [comment]
Hi @OneSons 

Also installed Wallpaper Engine to my 2nd driver `/dev/sda1`:

```
文件系统        容量  已用  可用 已用% 挂载点
dev              16G     0   16G    0% /dev
run              16G  1.6M   16G    1% /run
/dev/nvme0n1p4   97G   42G   51G   45% /
tmpfs            16G   39M   16G    1% /dev/shm
tmpfs            16G  520K   16G    1% /tmp
tmpfs           3.2G   56K  3.2G    1% /run/user/1000
/dev/sda1       1.9T  721G  1.2T   39% /mnt
```

`mount` `/dev/sda1` to `/mnt`.  Then selected steam library directory:

![Screenshot_20210728_095017](https://user-images.githubusercontent.com/68763952/127251165-c52f0faf-378c-4eef-827b-9e240f543011.png)

Subscribed some wallpapers:

![Screenshot_20210728_095756](https://user-images.githubusercontent.com/68763952/127251824-b8789f6e-408a-451a-a76f-92fd37ff3e3c.png)

Chose your KDE wallpaper:

![Screenshot_20210728_095832](https://user-images.githubusercontent.com/68763952/127251989-2411d833-32fa-446d-9dcb-1735b1bbd0f2.png)

Cheers,
Ray Zhai

**Comment by OneSons** [comment]
@zhairuiyao15 Ahh, I was selecting the steamapps folder itself instead of its parent folder. It works now! Thank you very much!

And thank you @catsout for this plugin! It is a godsend 👍
