### ISSUE TITLE
"Newer" wallpapers apparently don't work well

### ISSUE THREAD

**Issue by tonehrk** [catsout/wallpaper-engine-kde-plugin#378]
Apparently the wallpapers added to the workshop after the Wallpaper Engine update 2.4 do not work. I tried several and all the "scenes" result in gray screen, But the other effects such as lighting do work. 

I tested WpE 2.3 and later updated to 2.4 with the same result.

**System Information**
- Kde: 5.27.10
- Qt: 5.15.12
- OS: Manjaro 
- Installation Source: Git
- Wallpaper Engine version: 2.3 / 2.4

**Additional context**<br/>
Outputs:
```
INFO source: /home/tony/.steam/steam/steamapps/workshop/content/431960/3184420117/scene.json
INFO loading scene: /home/tony/.steam/steam/steamapps/workshop/content/431960/3184420117/scene.json
INFO muted, not init sound device
INFO pkg version: PKGV0020
INFO cache folder: /home/tony/.cache/wescene-renderer
INFO read json "angles" not a key at FromJson(WPImageObject.cpp:126)
INFO read json "scale" not a key at FromJson(WPImageObject.cpp:127)
INFO read json "scale" not a key at FromJson(WPImageObject.cpp:127)
INFO read json "angles" not a key at FromJson(WPParticleObject.cpp:187)
INFO read json "type" not a key at FromJson(WPParticleObject.cpp:11)
INFO read json "angles" not a key at FromJson(WPImageObject.cpp:126)
INFO read json "scale" not a key at FromJson(WPImageObject.cpp:127)
ERROR WPSceneParser.cpp:244 unknown tex "_rt_shadowAtlas"
ERROR WPSceneParser.cpp:340 _rt_shadowAtlas not found in render targes
ERROR VFS.h:71 not found "/assets/materials/_alias_lightCookie.tex" in vfs
ERROR Shader.cpp:424 glslang(link): ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point


ERROR WPSceneParser.cpp:624 load imageobj '스크린샷 2024-03-15 150447' material faild
ERROR WPSceneParser.cpp:244 unknown tex "_rt_shadowAtlas"
ERROR WPSceneParser.cpp:340 _rt_shadowAtlas not found in render targes
ERROR VFS.h:71 not found "/assets/materials/_alias_lightCookie.tex" in vfs
ERROR Shader.cpp:424 glslang(link): ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point


ERROR WPSceneParser.cpp:624 load imageobj '1346622_fg' material faild
INFO new buffer block(0x7f0ba0024810), size: 2097152, index: 0 / 1
INFO new buffer block(0x7f0ba002cee0), size: 2097152, index: 0 / 1
INFO new buffer block(0x7f0ba002cee0), size: 2560000, index: 1 / 2
INFO increase buffer size: 2560000
qml: backend scene first frame
```

```
INFO source: /home/tony/.steam/steam/steamapps/workshop/content/431960/3184934786/scene.json
INFO loading scene: /home/tony/.steam/steam/steamapps/workshop/content/431960/3184934786/scene.json
INFO muted, not init sound device
INFO pkg version: PKGV0020
INFO cache folder: /home/tony/.cache/wescene-renderer
INFO read json "angles" not a key at FromJson(WPImageObject.cpp:126)
INFO read json "scale" not a key at FromJson(WPImageObject.cpp:127)
INFO read json "scale" not a key at FromJson(WPParticleObject.cpp:188)
INFO read json "angles" not a key at FromJson(WPParticleObject.cpp:187)
INFO read json "scale" not a key at FromJson(WPParticleObject.cpp:188)
INFO read json "angles" not a key at FromJson(WPParticleObject.cpp:187)
INFO read json "scale" not a key at FromJson(WPParticleObject.cpp:188)
INFO read json "angles" not a key at FromJson(WPParticleObject.cpp:187)
INFO read json "type" not a key at FromJson(WPParticleObject.cpp:11)
INFO read json "angles" not a key at FromJson(WPParticleObject.cpp:187)
INFO read json "scale" not a key at FromJson(WPParticleObject.cpp:188)
INFO read json "angles" not a key at FromJson(WPParticleObject.cpp:187)
INFO read json "scale" not a key at FromJson(WPParticleObject.cpp:188)
INFO read json "angles" not a key at FromJson(WPParticleObject.cpp:187)
INFO read json "scale" not a key at FromJson(WPParticleObject.cpp:188)
INFO read json "angles" not a key at FromJson(WPParticleObject.cpp:187)
INFO read json "scale" not a key at FromJson(WPParticleObject.cpp:188)
ERROR WPSceneParser.cpp:244 unknown tex "_rt_shadowAtlas"
ERROR WPSceneParser.cpp:340 _rt_shadowAtlas not found in render targes
ERROR VFS.h:71 not found "/assets/materials/_alias_lightCookie.tex" in vfs
ERROR Shader.cpp:424 glslang(link): ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point


ERROR WPSceneParser.cpp:624 load imageobj 'gojo-satoru-and-night-scene-k9iiafgr6qy0e0ej' material faild
INFO new buffer block(0x7f0ba0024810), size: 2097152, index: 0 / 1
INFO new buffer block(0x7f0ba002cee0), size: 2097152, index: 0 / 1
qml: backend scene first frame
```

**Comment by hydridity** [comment]
Probably the same issue as previous update from 2.2 to 2.3 - #327

Shaders must have undergone another change and references have to be updated in code

**Comment by tonehrk** [comment]
If I remember correctly, that error caused all the wallpapers to not work correctly.
  I think I didn't understand myself well. The issue I am reporting is about the Wallpapers that have been uploaded to the workshop since update 2.4, that is, since February 15 of the current year.
Wallpapers prior to those dates works correctly.

ex. 
[Link 1]( https://steamcommunity.com/sharedfiles/filedetails/?id=3160780162)  <- 14 February.. works
[Link 2]( https://steamcommunity.com/sharedfiles/filedetails/?id=3163635099)  <- Uploaded 18/February doesn't works correctly. 

I think I mistakenly deleted a part of my original post. The lighting effects (mostly) and other things work, what doesn't work are the wallpaper backgrounds.

I noticed this while maintaining WpE version 2.3, I updated to 2.4 to see if that helped, but no change.
And to include I have the most recent version of the KDE plugin

**Comment by hydridity** [comment]
That's correct it affected most scenes or all of them, I haven't been able to look more in depth into the current issue, I'm just suspecting that 2.4 scenes are using some new shader schema (according to errors) which is not parsed correctly in this plugin, so scenes before 2.4 are using older schema that plugin can parse and after 2.4 it just breaks

**Comment by tonehrk** [comment]
> That's correct it affected most scenes or all of them, I haven't been able to look more in depth into the current issue, I'm just suspecting that 2.4 scenes are using some new shader schema (according to errors) which is not parsed correctly in this plugin, so scenes before 2.4 are using older schema that plugin can parse and after 2.4 it just breaks

I think I found the origin "error", the recent wallpapers use the shader "genericimage4" while the previous ones use "genericimage3". Your guess was correct.

The only solution I found for now is to unzip the "scene.pkg" edit the ".json" and replace the shader line with genericimage3 instead of 4... and add it to the WpE "myprojects" path.

**Comment by fililip** [comment]
I can confirm the patch fixes previously grey genericimage4 scene wallpapers. Is the new renderer going to be merged into the repo? Compiling from AUR doesn't yield the fix, I have to manually copy the scene backend's files and compile again to get it working.

**Comment by tonehrk** [comment]
> I can confirm the patch fixes previously grey genericimage4 scene wallpapers. Is the new renderer going to be merged into the repo? Compiling from AUR doesn't yield the fix, I have to manually copy the scene backend's files and compile again to get it working.

it was already merged to repo. 
AUR hasn't been updated since last year.

**Comment by tonehrk** [comment]
> I can confirm the patch fixes previously grey genericimage4 scene wallpapers. Is the new renderer going to be merged into the repo? Compiling from AUR doesn't yield the fix, I have to manually copy the scene backend's files and compile again to get it working.

it was already merged to repo.
however AUR hasn't been updated since last year.
