### ISSUE TITLE
Scenes not working even though plugin was installed

### ISSUE THREAD

**Issue by TECHNOFAB11** [catsout/wallpaper-engine-kde-plugin#38]
**Describe the bug**
Installed the plugin to be able to use scenes, but it always says that it can't find it. Restarted plasmashell and even rebooted. 
If i had to guess, its because the plugin gets installed to a weird folder? (See additional context)

**Workshop link**
Any scene

**Kde version**
- Kde: 5.22.4
- Qt: 5.15.2
- OS: Opensuse Tumbleweed [5.13.4-1-default 

**Additional context**
Weird install location.
```
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/**Unknown**/com/github/catsout/wallpaperEngineKde/libWallpaperEngineKde.so
-- Installing: /usr/local/**Unknown**/com/github/catsout/wallpaperEngineKde/qmldir
```

**Comment by catsout** [comment]
What's the output of:  
`qmake -query QT_INSTALL_QM`

**Comment by TECHNOFAB11** [comment]
`**Unknown**`

Sorry for the late reply, didn't get any notification from Github... :D

**Comment by catsout** [comment]
It's strange.  
Please do again with `qmake -query`, that will output all available.

**Comment by TECHNOFAB11** [comment]
```
QT_INSTALL_PREFIX:/usr
QT_INSTALL_DATA:/usr/share/qt4/
QT_INSTALL_DOCS:/usr/share/doc/packages/libqt4
QT_INSTALL_HEADERS:/usr/include
QT_INSTALL_LIBS:/usr/lib64
QT_INSTALL_BINS:/usr/bin
QT_INSTALL_PLUGINS:/usr/lib64/qt4/plugins
QT_INSTALL_IMPORTS:/usr/lib64/qt4/plugins/imports
QT_INSTALL_TRANSLATIONS:/usr/share/qt4/translations
QT_INSTALL_CONFIGURATION:/etc/settings
QT_INSTALL_EXAMPLES:/usr/lib64/qt4/examples
QT_INSTALL_DEMOS:/usr/lib64/qt4/demos
QMAKE_MKSPECS:/usr/share/qt4//mkspecs
QMAKE_VERSION:2.01a
QT_VERSION:4.8.7
```

**Comment by catsout** [comment]
I think you need to find some thing like `qmake-qt5` or `qmake5`  
Run `qmake-qt5 -query QT_INSTALL_QM` to get <qml_path>  
And manually move `libWallpaperEngineKde.so`,`qmldir` to <qml_path>/com/github/catsout/wallpaperEngineKde/

**Comment by catsout** [comment]
`QT_INSTALL_QM` -> `QT_INSTALL_QML`

**Comment by TECHNOFAB11** [comment]
That worked, thanks a lot!
