### ISSUE TITLE
Some wallpapers dont work or crash mid-way with all plugins installed

### ISSUE THREAD

**Issue by PedroSilva8** [catsout/wallpaper-engine-kde-plugin#39]
**Describe the bug**
To run workshop some items with Quicktime you need gst-plugins-good (arch).

after sometime running it stops with the "Error: plugin lib not found, to support scene, compile and install it." error giving the following error on console
qrc:/plasma/plasmoids/org.kde.plasma.volume/contents/ui/ListItemBase.qml:233: TypeError: Cannot read property 'visible' of null

I have all plugins installed and then running some items they simply give the "Error: plugin lib not found, to support scene, compile and install it." with the following console error
file:///home/pantsu/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/config.qml:207: Error: Cannot assign [undefined] to QUrl (When Selecting)
qml: load backend: backend/InfoShow.qml (When Applying)

**Workshop link**
[2561891463](https://steamcommunity.com/sharedfiles/filedetails/?id=2561891463) (Quicktime and crash after some time)
[1938719410](https://steamcommunity.com/sharedfiles/filedetails/?id=1938719410&searchtext=Yumeko) (Doesn't work just gives error mentioned before)
[1977984395](https://steamcommunity.com/sharedfiles/filedetails/?id=1977984395&searchtext=Yumeko) (Doesn't work just gives error mentioned before)
[1977325069](https://steamcommunity.com/sharedfiles/filedetails/?id=1977325069&searchtext=Yumeko) (Doesn't work just gives error mentioned before)

**Kde version**
- Kde: 5.22.4
- Qt: 5.15.2
- OS: Arch 5.13.6

**Comment by catsout** [comment]
Do you have **[plugin lib](https://github.com/catsout/wallpaper-engine-kde-plugin#plugin-lib)** installed?  
Also what's the output of the `qmake -query QT_INSTALL_QML`

**Comment by PedroSilva8** [comment]
I forgot to run the "sudo make install" command sorry.
Anyways here are some bugs:

- after some time the wallpaper changes to another
- wallpapers with clocks work but don't show the clock

If you need any information just tell me

**Comment by catsout** [comment]
1. random change has been fixed
2. this is because *text layer* is not supported yet(clock also require unsupported *scene script*)
3. just check it with new commit
4. `[h264 @ 0x7faa7c00aa00] Requested frame threading ...` not related

**Comment by PedroSilva8** [comment]
Updated and tested, everything seems to be working fine, thank you for your work
