### ISSUE TITLE
Scenes do not properly display on KDE 6. Scene wallpapers installed prior seem to work just fine.

### ISSUE THREAD

**Issue by joshrandall8478** [catsout/wallpaper-engine-kde-plugin#397]
**Describe the bug**<br/>
Scenes installed before either wallpaper engine or kde 6 seem to display just fine, but wallpapers installed afterwards seem to be completely "grayed out". Video wallpapers installed work just fine.

**Workshop link**<br/>
[3251624641](https://steamcommunity.com/sharedfiles/filedetails/?id=3251624641)

**System Information**
- Kde: 6.0.4
- Qt: 6.7.0
- OS: Arch Linux
- Installation Source: [AUR package](https://aur.archlinux.org/packages/plasma6-wallpapers-wallpaper-engine-git)
- Wallpaper Engine version: 2.4

**Additional context**<br/>
Wallpaper installed before KDE 6: 
![Screenshot_20240526_123517](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/39863829/477e3885-15e1-40c8-8d84-ceaee4ea9803)
Wallpaper installed after KDE 6:
![Screenshot_20240526_123530](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/39863829/26c0bc47-b74b-44ab-bef9-9ec75869e123)

**Comment by fxzjshm** [comment]
This seems not related to KDE 6 but Wallpaper Engine 2.4, and should have been fixed by <https://github.com/catsout/wallpaper-scene-renderer/pull/2>. I forget to update submodule in this repo and here is #399 .

**Comment by joshrandall8478** [comment]
thanks for the reply. how can i get this merged in, or is it already in the main branch? i installed this using AUR since compilation for me wasn't working on KDE 6.

**Comment by joshrandall8478** [comment]
ohh i just saw your merge request, mb!

**Comment by krgrabowski** [comment]
how did you get it installed form AUR?
For me its getting compile errors all over the place and of course pacman fails to install the package because of that

**Comment by krgrabowski** [comment]
nvm needed to delete com.github.catsout.wallpaperEngineKde.appdata.xml in /usr/share/metainfo/ which was placed probbably by my previous install attempts.
Now most video and web wallpapers work perfectly fine, scene on the other hand only blackscreen, dont know if that related to your issue, about tab says everything is fine.

**Comment by joshrandall8478** [comment]
> nvm needed to delete com.github.catsout.wallpaperEngineKde.appdata.xml in /usr/share/metainfo/ which was placed probbably by my previous install attempts. Now most video and web wallpapers work perfectly fine, scene on the other hand only blackscreen, dont know if that related to your issue, about tab says everything is fine.

Hey, sorry I've been busy with family related matters and work. Yeah that is related to my issue. Are there other dependencies i should have installed, or is there anything i can personally do to have most/all scene wallpapers working? I can move away from the AUR version if necessary, I just would like to know how I can get this compiled for KDE with your fixes/merge

**Comment by joshrandall8478** [comment]
Compiled with the latest merge / build of branch `qt6`, my issues were solved. Most scenes are now rendering correctly, and none are crashing. Thank you so much!
