### ISSUE TITLE
Cannot use scene resource.

### ISSUE THREAD

**Issue by tohsaka888** [catsout/wallpaper-engine-kde-plugin#4]
I can’t use the scene resource, I have installed the C++ plugin, so I try to reinstall the component. After I reinstall, I cannot select the folder in the plugin(the folder is refreshed and empty), when I switch to another plugin When switching back, it can only open the /home directory.

**Comment by tohsaka888** [comment]
I just tried to select the directory again, it can work normally again, but some scene resources are still unavailable, which caused you trouble, sorry

**Comment by catsout** [comment]
>  some scene resources are still unavailable
What's unavailable meaning?
It's can't apply, or get a back screen?
