### ISSUE TITLE
Misplaced particles

### ISSUE THREAD

**Issue by UltraBlackLinux** [catsout/wallpaper-engine-kde-plugin#40]
**Describe the bug**
The particle system seems to misplace particles quite a bit - I have tried two wallpapers and the particles really seem like they are supposed to be moved to right

**Workshop link**
https://steamcommunity.com/sharedfiles/filedetails/?id=2346737947

Operating System: Garuda Linux
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.13.9-zen1-1-zen (64-bit)
Graphics Platform: X11

**Additional context**
![Screenshot_77](https://user-images.githubusercontent.com/62404294/129337952-507a7d2c-9718-4868-b720-03f0ece7e9a7.png)

**Comment by catsout** [comment]
Yeah, the particle system has some parameters not parse rightly.  
But I'm working on refactoring renderer and sound support, this will be delayed.

**Comment by catsout** [comment]
Fixed.
