### ISSUE TITLE
Scene wallpaper not working even after plugin lib is installed.

### ISSUE THREAD

**Issue by sonicjhon1** [catsout/wallpaper-engine-kde-plugin#41]
**Describe the bug**
I'm using Garuda Linux (Arch), I've compiled and installed the plugin lib but even after restarting plasmashell it will just show 
`Shop id: 2101805083
Type: scene
Message: Plugin lib not found. To support scene, please compile and install it.`
![image](https://user-images.githubusercontent.com/41381685/129533462-353313fb-6334-44ce-a00d-caa906cb867f.png)

**Workshop link**
[2101805083](https://steamcommunity.com/sharedfiles/filedetails/?id=2101805083)
[2190672855](https://steamcommunity.com/sharedfiles/filedetails/?id=2190672855)

**Kde version**
- Kde: 5.22.4
- KDE Frameworks Version: 5.85.0
- Qt: 5.15.2
- OS: Garuda KDE Dr460nized

**Additional context**
sudo make install:

> sudo make install
[sudo] password for sonicj:
Consolidate compiler generated dependencies of target glad
[  3%] Built target glad
Consolidate compiler generated dependencies of target wallpaper
[ 63%] Built target wallpaper
[ 65%] Automatic MOC and UIC for target scenebackend
[ 65%] Built target scenebackend_autogen
Consolidate compiler generated dependencies of target scenebackend
[ 71%] Built target scenebackend
[ 73%] Automatic MOC and UIC for target mpvbackend
[ 73%] Built target mpvbackend_autogen
Consolidate compiler generated dependencies of target mpvbackend
[ 78%] Built target mpvbackend
[ 80%] Automatic MOC and UIC for target WallpaperEngineKde
[ 80%] Built target WallpaperEngineKde_autogen
Consolidate compiler generated dependencies of target WallpaperEngineKde
[ 88%] Built target WallpaperEngineKde
[ 90%] Automatic MOC and UIC for target scenebackend-viewer-qml
[ 90%] Built target scenebackend-viewer-qml_autogen
Consolidate compiler generated dependencies of target scenebackend-viewer-qml
[100%] Built target scenebackend-viewer-qml
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/libWallpaperEngineKde.so
-- Installing: /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/qmldir

plasmashell's log:
> file:///home/sonicj/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/config.qml:12:1: QML Column: StackView has detected conflicting anchors. Transitions may not execute properly.
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:90:13: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
XMLHttpRequest: Using GET on a local file is dangerous and will be disabled by default in a future Qt version.Set QML_XHR_ALLOW_FILE_READ to 1 if you wish to continue using this feature.
XMLHttpRequest: Using GET on a local file is dangerous and will be disabled by default in a future Qt version.Set QML_XHR_ALLOW_FILE_READ to 1 if you wish to continue using this feature.
XMLHttpRequest: Using GET on a local file is dangerous and will be disabled by default in a future Qt version.Set QML_XHR_ALLOW_FILE_READ to 1 if you wish to continue using this feature.
XMLHttpRequest: Using GET on a local file is dangerous and will be disabled by default in a future Qt version.Set QML_XHR_ALLOW_FILE_READ to 1 if you wish to continue using this feature.
XMLHttpRequest: Using GET on a local file is dangerous and will be disabled by default in a future Qt version.Set QML_XHR_ALLOW_FILE_READ to 1 if you wish to continue using this feature.
qml: load backend: backend/InfoShow.qml

ls /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/:
> .rwxr-xr-x 1.6M root 16 Aug 15:08  libWallpaperEngineKde.so
.rw-r--r--  136 root 16 Aug 15:08  qmldir

**Comment by catsout** [comment]
Check https://github.com/catsout/wallpaper-engine-kde-plugin/issues/38

**Comment by sonicjhon1** [comment]
> Check #38

I have tried manually moving `libWallpaperEngineKde.so` and `qmldir` to `/usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde` and restarted plasmashell, it still doesn't work.
![image](https://user-images.githubusercontent.com/41381685/129538253-0bb3cf51-d376-4f18-b1b8-8da9cca666a8.png)



qmake-qt5 -query QT_INSTALL_QML:
 ```
/usr/lib/qt/qml
```

qmake -query QT_INSTALL_QML:
```
/usr/lib/qt/qml
```

**Comment by catsout** [comment]
Do you have `/usr/lib/qt/qml/org/kde/plasma/wallpapers/image` dir?

**Comment by sonicjhon1** [comment]
> Do you have `/usr/lib/qt/qml/org/kde/plasma/wallpapers/image` dir?

I do
![image](https://user-images.githubusercontent.com/41381685/129542850-a97ff2b8-3180-43e0-883d-087fc9576c5e.png)

**Comment by catsout** [comment]
Try new commit, I add log output for this.  
To get log: 
switch to another wallpaper plugin
run `kquitapp5 plasmashell && kstart5 plasmashell > ~/plasma.log 2>&1`
switch to this wallpaper plugin, select scene wallpaper, and apply.
run `kquitapp5 plasmashell && kstart5 plasmashell` again.
get `plasma.log`

**Comment by sonicjhon1** [comment]
[plasma.log](https://github.com/catsout/wallpaper-engine-kde-plugin/files/6991607/plasma.log)

**Comment by catsout** [comment]
```
qml: ---check lib 'com.github.catsout.wallpaperEngineKde 1.0' failed---
qml: Error: Qt.createQmlObject(): failed to create object: 
    file:///home/sonicj/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/inline:1:1: plugin cannot be loaded for module "com.github.catsout.wallpaperEngineKde": Cannot load library /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/libWallpaperEngineKde.so: (/usr/lib/libshaderc_shared.so.1: undefined symbol: _ZN8spvtools9Optimizer18RegisterSizePassesEv)
```

`(/usr/lib/libshaderc_shared.so.1: undefined symbol: _ZN8spvtools9Optimizer18RegisterSizePassesEv)`
This is used by mpv.  
It seems like a bug in your Garuda linux.  
I can't do any thing about this.
