### ISSUE TITLE
I cant compile: Kpacktool not found

### ISSUE THREAD

**Issue by MarkCersar123** [catsout/wallpaper-engine-kde-plugin#428]
**Describe the bug**<br/>
I can't compile the plugin, despite simply folllowing the guide. I'm always getting the error message 'kpackagetool not found', despite having the package installed.

**System Information**
- Kde: 5.27.11
- Qt: 5.15.13
- OS: Linux Mint 22
- Installation Source: git

**Console output**<br/>
Add any other context about the problem here. [e.g. screenshots/logs]
```
# Download source
git clone https://github.com/catsout/wallpaper-engine-kde-plugin.git
cd wallpaper-engine-kde-plugin

# Download submodule (glslang)
git submodule update --init

# Configure
# 'USE_PLASMAPKG=ON': using plasmapkg2 tool to install plugin
mkdir build && cd build
cmake .. -DUSE_PLASMAPKG=ON

# Build
make -j$nproc

# Install package (ignore if USE_PLASMAPKG=OFF for system-wide installation)
make install_pkg
# install lib
sudo make install
Cloning into 'wallpaper-engine-kde-plugin'...
remote: Enumerating objects: 7763, done.
remote: Counting objects: 100% (679/679), done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 7763 (delta 550), reused 575 (delta 511), pack-reused 7084 (from 1)
Receiving objects: 100% (7763/7763), 5.37 MiB | 12.16 MiB/s, done.
Resolving deltas: 100% (4857/4857), done.
Submodule 'src/backend_scene' (https://github.com/catsout/wallpaper-scene-renderer.git) registered for path 'src/backend_scene'
Cloning into '/home/marcelo/wallpaper-engine-kde-plugin/src/backend_scene'...
Submodule path 'src/backend_scene': checked out '11b1fa3fca6aa4b4b8b063435a428c74530afc48'
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Found KF5Package: /usr/lib/x86_64-linux-gnu/cmake/KF5Package/KF5PackageConfig.cmake (found version "5.115.0") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found KF5Plasma: /usr/lib/x86_64-linux-gnu/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.115.0") 
-- Found KF5: success (found suitable version "5.115.0", minimum required is "5.68.0") found components: Package Plasma 
CMake Error at CMakeLists.txt:61 (message):
  kpackagetool not found


-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install_pkg'.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

**Comment by joshrandall8478** [comment]
Are you attempting to install for KDE 5 or KDE 6? And if you’re installing for KDE 6, are you using the qt6 branch?

**Comment by MarkCersar123** [comment]
On KDE5, as I mention in the post. 
![qt5](https://github.com/user-attachments/assets/e94d3a0d-9b4c-4f80-85c1-21903a93665c)
But you did help me. The issue was that when I follow the guide for qt5 I still download the master branch. After changing the command 
`git clone https://github.com/catsout/wallpaper-engine-kde-plugin.git`
 to 
`git clone -b qt5 https://github.com/catsout/wallpaper-engine-kde-plugin.git`
I was able to compile it. Thanks

**Comment by joshrandall8478** [comment]
Apologies, dealing with a ton of personal life stuff atm. Glad you were able to compile 🙏

**Comment by MarkCersar123** [comment]
np bro thank you for trying and im glad to say it works now! :D

**Comment by joshrandall8478** [comment]
i'd recommend closing the issue, but i do want to see how linux mint with KDE looks tbh. send rice pics :)

**Comment by MarkCersar123** [comment]
Sure thing! Is this fine? fresh install! ;)
![2024-09-02_18-11](https://github.com/user-attachments/assets/e3f08d5e-210a-4769-8716-38b3b6a15ded)

**Comment by joshrandall8478** [comment]
ooo nice, here's mine
![IMG_2026](https://github.com/user-attachments/assets/ac2a3d77-5849-4230-afa9-3b04fa8e0a63)
![Screenshot_20240902_131533](https://github.com/user-attachments/assets/cce5356a-2be8-4766-aa28-a7369abb2710)

**Comment by MarkCersar123** [comment]
ahh awesome! you have two monitors?

**Comment by joshrandall8478** [comment]
I have three ✌🏼

**Comment by MarkCersar123** [comment]
damn thats nice! you have only one gpu running the monitors? must be one using hdmi and display ports for the others

**Comment by joshrandall8478** [comment]
yeah. main display runs displayport, and the spares use the other DP and HDMI. some require adapters

**Comment by MarkCersar123** [comment]
kickass!

**Comment by kub3let** [comment]
Had the same problem with Parrot OS, qt5 branch works just fine.

Upgraded the plugin and now the crash (plasma shell stack strace) on login is gone as well.

**Comment by TerrellAW** [comment]
I'm having this problem with kubuntu

**Comment by TerrellAW** [comment]
kpackagetool5 needs to be added to the CMakeLists.txt
