### ISSUE TITLE
Scene wallpapers not rendering properly

### ISSUE THREAD

**Issue by AmmoniumX** [catsout/wallpaper-engine-kde-plugin#431]
**Describe the bug**<br/>
When selecting any `Type: scene` wallpapers, the desktop just becomes a flashing light-blue light. Happens both on X11 and Wayland. "Web" and "video" wallpapers work fine.

**Workshop link**<br/>
Any scene wallpaper, such as [1817757506](https://steamcommunity.com/sharedfiles/filedetails/?id=1817757506)

**System Information**
- Kde: 6.1.5
- Qt: 6.7.2
- OS: Arch Linux
- Installation Source: this git
- Wallpaper Engine version: latest on Steam

**Additional context**<br/>
```
$ vulkaninfo | grep apiVersion
apiVersion        = 1.3.280 (4206872)
$ pacman -Q nvidia
nvidia 560.35.03-5
$ nvidia-smi
Fri Sep 13 11:46:22 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti     Off |   00000000:01:00.0 Off |                  N/A |
| N/A   72C    P5             N/A / ERR!  |      10MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     42801      G   /usr/lib/Xorg                                   4MiB |
+-----------------------------------------------------------------------------------------+
```

Example screenshot:
![Screenshot_20240913_113752](https://github.com/user-attachments/assets/d0bc00e2-0c31-4ead-b153-1e4b14ae202e)

**Comment by krgrabowski** [comment]
> I have the exact same issue, couldn't figure it out.
> 
> Kernel: Linux 6.10.10-arch1-1 Kde: 6.1.5 OS: Latest Arch Linux Installation Source: From store.kde.org Wallpaper Engine version: latest on Steam CPU: 11th Gen Intel(R) Core(TM) i3-1115G4 (4) @ 4.10 GPU: Intel UHD Graphics G4 @ 1.25 GHz [Integrated]
> 
> All scene wallpapers are either completly black, or, if I had a wallpaper before, it freezes with a red-ish or gray/black color. If it also seems to reverse the previous wallpaper before crashing

have you installed intel-vulcan drivers?
Did you set Mpv in the settings?

**Comment by AmmoniumX** [comment]
I found the solution. Turns out, KDE Plasma was running on my integrated graphics instead of my Nvidia GPU. Installing vulkan-intel solves the issue.
