### ISSUE TITLE
Fatal Error on cmake --build build

### ISSUE THREAD

**Issue by MushuMan** [catsout/wallpaper-engine-kde-plugin#451]
I have all the dependencies installed and was able to clone the git page. After that I was able to get all the submodules without issue. Using "cmake -B build -S . -GNinja -DUSE_PLASMAPKG=ON" works, but after trying "cmake --build build" I get a fatal error:

/home/usr/wallpaper-engine-kde-plugin/src/backend_mpv/MpvBackend.cpp:40:14: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   40 | #    include <qpa/qplatformnativeinterface.h> // IWYU pragma: keep
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I am unsure how to fix this. I am unable to find a fix online, and all suggestions for installing libqt5-qtbase-private-headers-devel, or its equivalent result in not being able to find the package in order to install it with "sudo dnf install libqt5-qtbase-private-headers-devel"

I am on Nobara Linux 40 with KDE Plasma.

**Comment by Sennaton** [comment]
Same issue here.

**Comment by pc-v2** [comment]
I have no issue here with nobara 40 kde, 

my steps is:
`sudo dnf install mpv`
 
`sudo dnf install vulkan-headers plasma-workspace-devel kf5-plasma-devel gstreamer1-libav lz4-devel mpv-libs-devel python3-websockets qt5-qtbase-private-devel libplasma-devel qt5-qtx11extras-devel qt5-qtwebchannel-devel qt5-qtwebsockets-devel cmake`

then

`git clone https://github.com/catsout/wallpaper-engine-kde-plugin.git`

`cd wallpaper-engine-kde-plugin`

`git submodule update --init --force --recursive`

`cmake -B build -S . -GNinja -DUSE_PLASMAPKG=ON`

`cmake --build build`

`sudo cmake --install build`

**Comment by MushuMan** [comment]
It still fails when I get to this "Building CXX object src/backend_mpv/CMakeFiles/mpvbackend.dir/MpvBackend.cpp.o" where it's missing the header file

**Comment by MushuMan** [comment]
I was finally able to find a fix for this. Try using these commands:

```
sudo dnf install qt6-qtbase-private-devel
sudo dnf install qt6-qtwebsockets-devel

```
Then 
```
# Download source
git clone https://github.com/catsout/wallpaper-engine-kde-plugin.git
cd wallpaper-engine-kde-plugin

# Download submodule
git submodule update --init --force --recursive

# Configure, build and install
# 'USE_PLASMAPKG=ON': using kpackagetool tool to install plugin
cmake -B build -S . -GNinja -DUSE_PLASMAPKG=ON
cmake --build build
cmake --install build

# Install package (ignore if USE_PLASMAPKG=OFF for system-wide installation)
cmake --build build --target install_pkg
```
And don't forget to point it to your wallpaper engine folder and to restart plasma:
This is for restarting plasma:
`systemctl --user restart plasma-plasmashell.service`
