### ISSUE TITLE
"Any Window" and "Maximized Window" always stop

### ISSUE THREAD

**Issue by Leplik500** [catsout/wallpaper-engine-kde-plugin#47]
"Any Window" and "Maximized Window" always stop wallpappers, even if there are no windows in current virtual desktop at all. But sometimes it works as it should and idk why.

**Comment by no95typem** [comment]
It should was fixed by #19 . It work's for me. Do you use the last version?

**Comment by Leplik500** [comment]
I used this list of commands

sudo rm -R ~/wallpaper-engine-kde-plugin;
git clone https://github.com/catsout/wallpaper-engine-kde-plugin.git;
plasmapkg2 -u wallpaper-engine-kde-plugin/plugin;
cd wallpaper-engine-kde-plugin;
mkdir build && cd build;
cmake -DCMAKE_BUILD_TYPE=Release ..;
make;
sudo make install;
kquitapp5 plasmashell && kstart5 plasmashell;

And restarted my pc.
It should be updated

**Comment by Leplik500** [comment]
And #19  fix is about multi-monitor setup, but not virtual desktops

**Comment by Leplik500** [comment]
Even if I minimize all my windows on all virtual desktops, it remains paused

**Comment by no95typem** [comment]
@Leplik500 Unfortunately, it is almost zero chance that someone can help you without any logs.

**Comment by Leplik500** [comment]
I know, but I don't know what exactly logs you need and how  to find them

**Comment by catsout** [comment]
@Leplik500 Please try new commit.

**Comment by catsout** [comment]
If it dose not work, 
Change value below to true, and reinstall to show log.  
https://github.com/catsout/wallpaper-engine-kde-plugin/blob/a91abd7e973dd0175f1090c294df1d78c762453f/plugin/contents/ui/WindowModel.qml#L13

**Comment by Leplik500** [comment]
Nothing changed. But I wrote xdotool script to do this https://github.com/catsout/wallpaper-engine-kde-plugin/issues/47#issuecomment-917372141 and I find it even more convenient to switch to empty desktop instead of minimizing all windows on current desktop. Now I happy with it. Close this issue  if you have nothing to say
