### ISSUE TITLE
(Question) Does this use Almamu/linux-wallpaperengine As a backend or is it completly different?

### ISSUE THREAD

**Issue by davigamer987** [catsout/wallpaper-engine-kde-plugin#49]
Does This Use https://github.com/Almamu/linux-wallpaperengine Or is it completely different?

**Comment by catsout** [comment]
No, It's completely different.  
The main code of scene support is at https://github.com/catsout/wallpaper-engine-kde-plugin/tree/main/src/backend/scene/src/wallpaper.

**Comment by davigamer987** [comment]
Ok thanks
