### ISSUE TITLE
Installation guide - KDE Neon

### ISSUE THREAD

**Issue by C0MODIN** [catsout/wallpaper-engine-kde-plugin#5]
Hi, this is a guide to install in KDE Neon.

Before to follow this [steps](https://github.com/catsout/wallpaper-engine-kde-plugin#install-kde-plugin), install these packages and a new version of cmake.

`sudo apt install libssl-dev liblz4-dev qtbase5-private-dev libglfw3 libglfw3-dev qtbase5-dev qtdeclarative5-dev libqt5x11extras5-dev libmpv-dev qml-module-qtwebchannel qml-module-qt-labs-folderlistmodel qt5-default libglm-dev nlohmann-json3-dev gstreamer1.0-vaapi`

This is the [link](https://cmake.org/download/) of Cmake, recommended version >>> 3.20 and follow this [steps](https://cmake.org/install/) to install it.

Now you can continue the [guide](https://github.com/catsout/wallpaper-engine-kde-plugin#install-kde-plugin).

**Comment by catsout** [comment]
Closed as already in readme.
