### ISSUE TITLE
Battery Drain on sleep

### ISSUE THREAD

**Issue by niksingh710** [catsout/wallpaper-engine-kde-plugin#50]
**Describe the bug**
When System is on sleep the wallpaper keeps running in the background and drains the battery overnight.

**Kde version**
- Kde: 5.22.5
- Qt: 5.15
- OS:  Kubuntu 21.04

**Additional context**
As The wallpaper has an option for full-screen apps it should also stop when the system is on sleep.

**Comment by catsout** [comment]
What's the meaning of 'sleep', It's `standby` or `suspend to RAM`?

**Comment by niksingh710** [comment]
> What's the meaning of 'sleep', It's `standby` or `suspend to RAM`?

in short, When I lid down my laptop it automatically turns off wifi and Bluetooth and then the battery does not drains.
I guess `suspend to RAM`.
I use the KDE sleep option if there is any way I can check and make it more sure in between these two tell me I will definitely try to check

**Comment by catsout** [comment]
If you system is actually `suspend to RAM`, the cpu is stopped, and there is no programs running.  
I think your computer may be waked up at night.

**Comment by niksingh710** [comment]
@catsout Okay, I will Observe and report as before using this when i lid down my battery never drained more than 5% in 10 hrs time period.

**Comment by catsout** [comment]
Or some thing stopped the system going into sleep when you lid down the laptop.

**Comment by niksingh710** [comment]
Hmm This could be a possibility I will investigate and report back btw u know any way to get the logs of this that that can may stop the system from going into sleep?
