### ISSUE TITLE
QT5-Default not found

### ISSUE THREAD

**Issue by GingerBobRoss** [catsout/wallpaper-engine-kde-plugin#51]
Im currently running Pop OS 21.04 with KDE Plasma 5.21.4
When running the terminal to install QT5-default i get the error
gonger@pop-os:~$ sudo apt install qt5-default
[sudo] password for gonger: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package qt5-default is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'qt5-default' has no installation candidate

**Comment by catsout** [comment]
I think you can just ignore `qt5-default`.

**Comment by PaliWasTakn** [comment]
You can ignore **qt5-default**, i did it and it worked.

**Comment by GingerBobRoss** [comment]
I managed to get it working, I was missing CmakeOn Sep 29, 2021 1:08 AM, PaliWasTakn ***@***.***> wrote:
You can ignore qt5-default, i did it and it worked.
