### ISSUE TITLE
It lags on Kubuntu 21.04

### ISSUE THREAD

**Issue by PaliWasTakn** [catsout/wallpaper-engine-kde-plugin#53]
I just installed kubuntu and this program exactly the same as i did on my other machine that runs linux mint 20.2 with kde plasma as desktop, but on linux mint it did not lag. All wallpapers lag. Please help me because i love this plugin and i use it for 6 months.

**Comment by catsout** [comment]
What's the meaning of 'lag'?

**Comment by PaliWasTakn** [comment]
My whole pc slows down and i cant move my cursor precisely.

**Comment by catsout** [comment]
All wallpapers include video and web wallpaper?

**Comment by catsout** [comment]
Test with a video wallpaper.
After applying, do `kquitapp5 plasmashell && kstart5 plasmashell`, check if still lag.

**Comment by PaliWasTakn** [comment]
> Test with a video wallpaper. After applying, do `kquitapp5 plasmashell && kstart5 plasmashell`, check if still lag.

it still lags but i got this **file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
**

**Comment by catsout** [comment]
Just not use mpv and do 
`kquitapp5 plasmashell && kstart5 plasmashell`  
And put the full log here.

**Comment by PaliWasTakn** [comment]
pali-was-taken@yes:~$  kquitapp5 plasmashell && kstart5 plasmashell
Omitting both --window and --windowclass arguments is not recommended
pali-was-taken@yes:~$ kf.coreaddons: Expected JSON property "X-Plasma-ContainmentCategories" to be a string list. Treating it as a list with a single entry: "panel" org.kde.plasma.desktop.defaultPanel
kf.coreaddons: Expected JSON property "X-Plasma-ContainmentCategories" to be a string list. Treating it as a list with a single entry: "panel" org.kde.plasma.desktop.emptyPanel
kf.coreaddons: Expected JSON property "X-Plasma-ContainmentCategories" to be a string list. Treating it as a list with a single entry: "panel" org.kde.plasma.desktop.appmenubar
kf.plasma.quick: Applet preload policy set to 1
qml: load backend: backend/Scene.qml
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
Plasma Shell startup completed
INFO  wallpaper.cpp:57: loading sound device
INFO  WPPkgFs.cpp:22: pkg version: PKGV0006
file:///usr/share/plasma/plasmoids/org.kde.plasma.panelspacer/contents/ui/main.qml:53:5: Unable to assign [undefined] to QQuickGridLayout*
file:///usr/share/plasma/plasmoids/org.kde.panel/contents/ui/main.qml:30:1: QML DropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
libkcups: CUPS-Get-Printers last error: 1030 No destinations added.
libkcups: Create-Printer-Subscriptions last error: 0 successful-ok
libkcups: Get-Jobs last error: 0 successful-ok
libkcups: Get-Jobs last error: 0 successful-ok
Cyclic dependency detected between "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml" and "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationHeader.qml"
file:///usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/CompactRepresentation.qml:75:17: Unable to assign [undefined] to int
libkcups: 0
libkcups: 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
qml: QQuickGridView_QML_203(0x55d713a2bc60)
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml:27:1: QML Panel: Binding loop detected for property "state"


and it got stuck here. You think it might be my gpu drivers?

**Comment by catsout** [comment]
Replace this line to `return; //background.hookMouse();`
https://github.com/catsout/wallpaper-engine-kde-plugin/blob/da4a87cce788dc14f1d7ab9b35617218c045f18f/plugin/contents/ui/main.qml#L58

Test with a video wallpaper without `Use mpv` checked.  
And do `kquitapp5 plasmashell && kstart5 plasmashell`  

If its still lags, there may be some other issues cause this problem, like gpu driver.

**Comment by PaliWasTakn** [comment]
Ok so it was my GPU drivers. Thank you so much for your help and sorry that i wasted your time. :D
