### ISSUE TITLE
Block highlighting and copying of text in backgrounds

### ISSUE THREAD

**Issue by jopejoe1** [catsout/wallpaper-engine-kde-plugin#55]
**Describe the bug**
When using this wallpaper I'm able to highlight the text from the wallpaper and copy it to my clipboard.

**Workshop link**
[1828698678](https://steamcommunity.com/sharedfiles/filedetails/?id=1828698678)

**Kde version**
- Kde: 5.22.5
- Qt: 5.15.2
- OS: Manjaro

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/42

**Comment by jopejoe1** [comment]
Thanks
