### ISSUE TITLE
Add "Sort by" in wallpaper selecting section

### ISSUE THREAD

**Issue by Weirdo1312** [catsout/wallpaper-engine-kde-plugin#59]
for example sort by install date, sort by alphabet, etc...

**Comment by catsout** [comment]
As this plugin can only get wallpaper info from the `project.json` file.  
There only two different way to sort by, `alphabet` and `workshop id`.

**Comment by barfin** [comment]
> As this plugin can only get wallpaper info from the `project.json` file. There are only two different ways to sort by, `alphabet` and `workshop id`.

there's more in that file though
like "contentrating" or "tags"
