### ISSUE TITLE
No Wallpapers are available to use.

### ISSUE THREAD

**Issue by TomBayne** [catsout/wallpaper-engine-kde-plugin#62]
**Describe the bug**
I have 2 wallpapers from the workshop, and neither of them are showing up in the picker menu.
I have set the path to the following:
- /home/tomba/.steam/steam/steamapps/
- /home/tomba/.steam/steam/steamapps/workshop/
- /home/tomba/.steam/steam/steamapps/workshop/content/
- /home/tomba/.steam/steam/steamapps/workshop/content/431960

and none of these have worked.

**Kde version**
- Kde: [e.g. 5.20] Plasma 5.22.5
- Qt: [e.g. 5.15] 5.15.2
- OS: [e.g. Debian] Manjaro

**Comment by catsout** [comment]
try `/home/tomba/.steam/steam`

**Comment by zany130** [comment]
![image](https://user-images.githubusercontent.com/25832539/138394028-fe2ded08-2d40-4d21-9fb4-03f9b91671e2.png)
I'm using the latest from  the git

**Comment by catsout** [comment]
get log: 
switch to another wallpaper plugin
run `kquitapp5 plasmashell && kstart5 plasmashell > ~/plasma.log 2>&1`
switch to this wallpaper plugin, select `/home/tomba/.steam/steam`, and apply.
run `kquitapp5 plasmashell && kstart5 plasmashell` again.
get plasma.log

**Comment by zany130** [comment]
`file:///usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxButton.qml:198: TypeError: Cannot read property 'ac
tion' of null
file:///usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxButton.qml:192: TypeError: Cannot read property 'ac
tion' of null
file:///usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxButton.qml:20: TypeError: Cannot read property 'edi
tMode' of null
file:///usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxButton.qml:33: TypeError: Cannot read property 'edi
tMode' of null
file:///usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxButton.qml:34: TypeError: Cannot read property 'edi
tMode' of null
trying to show an empty dialog
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:18: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:22: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:9: TypeError: Can
not read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:24: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:94: TypeError: Ca
nnot read property 'parent' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:95: TypeError: Ca
nnot read property 'parent' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/WindowModel.qml:69: TypeEr
ror: Cannot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:8: TypeError: Can
not read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:10: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:12: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:13: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:15: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:16: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:17: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:20: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:21: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/main.qml:33: TypeError: Ca
nnot read property 'configuration' of null
file:///home/zany130/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/Pyext.qml:51: TypeError: C
annot call method 'rejectUnfinished' of undefined
QProcess: Destroyed while process ("/bin/sh") is still running.`

**Comment by catsout** [comment]
Seems nothing useful.  
Could you run `kquitapp5 plasmashell && kstart5 plasmashell`, and show the log after you open `Configure Desktop and Wallpaper`?

**Comment by zany130** [comment]
wdym? to run `kquitapp5 plasmashell && kstart5 plasmashell > ~/plasma.log 2>&1` and then open configure desktop and wallpaper?
that gives this 
```
Omitting both --window and --windowclass arguments is not recommended
Icon theme "gnome" not found.
Icon theme "gnome" not found.
kf.plasma.quick: Applet preload policy set to 1
file:///home/zany130/.local/share/plasma/plasmoids/org.kde.simpleMonitor/contents/ui/skins/DefaultSkin.qml:55:9: QML ColumnLayout (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
XMLHttpRequest: Using GET on a local file is dangerous and will be disabled by default in a future Qt version.Set QML_XHR_ALLOW_FILE_READ to 1 if you wish to continue using this feature.
XMLHttpRequest: Using GET on a local file is dangerous and will be disabled by default in a future Qt version.Set QML_XHR_ALLOW_FILE_READ to 1 if you wish to continue using this feature.
qml: JSON.parse: Parse error
qml: JSON.parse: Parse error
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:134:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:134:19: QML Loader: Binding loop detected for property "height"
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:134:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:134:19: QML Loader: Binding loop detected for property "height"
Plasma Shell startup completed
QProcess: Destroyed while process ("/bin/sh") is still running.
libpng warning: iCCP: known incorrect sRGB profile
Plasma Shell startup completed
Plasma Shell startup completed
file:///home/zany130/.local/share/plasma/plasmoids/org.kde.simpleMonitor/contents/ui/main.qml:114: Error: Cannot assign [undefined] to QString
QQmlEngine::setContextForObject(): Object already has a QQmlContext
QQmlEngine::setContextForObject(): Object already has a QQmlContext
kf.kirigami: Units.devicePixelRatio is deprecated (since 5.86 ): This returns 1 when using Qt HiDPI scaling.
file:///usr/lib/qt/qml/org/kde/kirigami.2/templates/OverlaySheet.qml:220:38: QML FocusScope: Binding loop detected for property "contentItemMaximumWidth"
QCoreApplication::postEvent: Unexpected null receiver
kf.coreaddons: "Could not load plugin from "
Error loading KCM: ""
kf.coreaddons: "Could not load plugin from "
Error loading KCM: ""
kf.coreaddons: "Could not load plugin from "
Error loading KCM: ""
kf.coreaddons: "Could not load plugin from "
Error loading KCM: ""
qml: JSON.parse: Parse error
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:78:13: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
file:///usr/lib/qt/qml/org/kde/kirigami.2/AbstractApplicationItem.qml:94: TypeError: Cannot read property 'position' of null
file:///usr/lib/qt/qml/org/kde/kirigami.2/AbstractApplicationItem.qml:93: TypeError: Cannot read property 'background' of null
file:///usr/lib/qt/qml/org/kde/newstuff/qml/Page.qml:155: TypeError: Cannot read property 'useLabel' of null
file:///usr/lib/qt/qml/org/kde/newstuff/qml/Dialog.qml:129: TypeError: Cannot read property 'uploadEnabled' of null
qml: JSON.parse: Parse error
Error: cannot change the containment to AppletsLayout
Error: cannot change the containment to AppletsLayout
file:///usr/lib/qt/qml/org/kde/kirigami.2/private/globaltoolbar/ToolBarPageHeader.qml:15:1: QML ToolBarPageHeader: Binding loop detected for property "implicitWidth"
file:///usr/lib/qt/qml/org/kde/kirigami.2/AbstractApplicationItem.qml:94: TypeError: Cannot read property 'position' of null
file:///usr/lib/qt/qml/org/kde/kirigami.2/AbstractApplicationItem.qml:93: TypeError: Cannot read property 'background' of null
file:///usr/lib/qt/qml/org/kde/newstuff/qml/Page.qml:155: TypeError: Cannot read property 'useLabel' of null
file:///usr/lib/qt/qml/org/kde/newstuff/qml/Dialog.qml:129: TypeError: Cannot read property 'uploadEnabled' of null
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:78:13: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
QProcess: Destroyed while process ("/bin/sh") is still running.
```
