### ISSUE TITLE
Favorite items will disappear after reboot

### ISSUE THREAD

**Issue by Klairm** [catsout/wallpaper-engine-kde-plugin#63]
**Describe the bug**
Wallpapers added as favorite will get removed after reboot, and it will needed to re-add as favorite those

![imagen](https://user-images.githubusercontent.com/40839469/137582413-2bc0a791-dcda-4fee-8ca1-43dee2fb9889.png)

**Kde version**
- Kde: 5.22.5
- Qt: 5.15.2
- OS: EndeavourOS  5.14.12

**Comment by catsout** [comment]
Try to do: 
```
cat .config/plasma-org.kde.plasma.desktop-appletsrc | grep CustomConf
cat .config/plasma-org.kde.plasma.desktop-appletsrc | grep CustomConf | cut -b 12- | base64 -d
```
And put the log here. 
BTY, please use the newest code, this bug may already be fixed.

**Comment by Klairm** [comment]
> Try to do:
> 
> ```
> cat ~/.config/plasma-org.kde.plasma.desktop-appletsrc | grep CustomConf
> cat ~/.config/plasma-org.kde.plasma.desktop-appletsrc | grep CustomConf | cut -b 12- | base64 -d
> ```
> 
> And put the log here. BTY, please use the newest code, this bug may already be fixed.

I'm getting the dict with the full array so I guess now works for some reason I even rebooted 2 times to check and now it doesn't happens
```
{"favor":["1230116878","1290027759","1378401733","1410375043","1439106940","1471496897","1548057645","1557913676","1593284631","1710436562","1878103677","1808382068","1781466079","2199208757","2158749174","2208286695","2252219891","2269995549","2285020348","2401338983","2447928310","2523727314","2542493385"]}
```

So I can't reproduce the bug anymore xD and I haven't updated anything
