### ISSUE TITLE
It filters out all wallpapers without even using a filter

### ISSUE THREAD

**Issue by Weirdo1312** [catsout/wallpaper-engine-kde-plugin#66]
**Describe the bug**
It filters out all wallpapers without even using a filter

**Kde version**
- Kde: 5.23.1
- Qt: 5.15.2
- OS: Arch Linux

**Additional context**
![image](https://user-images.githubusercontent.com/37030489/138511883-f6955397-e687-4ed7-914a-57b5ad39cb08.png)

**Comment by shawnshyguy** [comment]
> @barfin Try new commit with AUR Better to switch to another plugin, and uninstall manual installation before install AUR.

switching to AUR build fixed it for me. Thanks!
