### ISSUE TITLE
KDE crashes regularly

### ISSUE THREAD

**Issue by Crylia** [catsout/wallpaper-engine-kde-plugin#76]
**Describe the bug**
KDE crashes regularly and second screen is not working half the time

**Workshop link**
Doesn't matter what kind of wallpaper.

**Kde version**
- Kde: 5.22.5
- Qt:  5.15.2
- OS: Pop!_OS 21.10

Recompiling doesnt help, I use lightdm as my dm

**Comment by Crylia** [comment]
I forgot to add my error from .xsession-errors:

`** (plasmashell:6596): CRITICAL **: 23:58:24.151: gst_gl_context_new_wrapped: assertion 'available_apis != GST_GL_API_ANY' failed
Could not create wrappped context for platform: 2
KCrash: Attempting to start /usr/bin/plasmashell
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = plasmashell path = /usr/bin pid = 6596
KCrash: Arguments: /usr/bin/plasmashell
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi
QSocketNotifier: Invalid socket 6 and type 'Read', disabling...
QSocketNotifier: Invalid socket 24 and type 'Read', disabling...
QSocketNotifier: Invalid socket 28 and type 'Read', disabling...
QSocketNotifier: Invalid socket 35 and type 'Read', disabling...
QSocketNotifier: Invalid socket 91 and type 'Exception', disabling...
QSocketNotifier: Invalid socket 92 and type 'Read', disabling...
QSocketNotifier: Invalid socket 29 and type 'Read', disabling...
QSocketNotifier: Invalid socket 38 and type 'Read', disabling...
QSocketNotifier: Invalid socket 27 and type 'Read', disabling...
QSocketNotifier: Invalid socket 31 and type 'Read', disabling...
QSocketNotifier: Invalid socket 87 and type 'Read', disabling...
QSocketNotifier: Invalid socket 104 and type 'Read', disabling...
QSocketNotifier: Invalid socket 108 and type 'Read', disabling...
QSocketNotifier: Invalid socket 42 and type 'Read', disabling...
QSocketNotifier: Invalid socket 109 and type 'Read', disabling...
QSocketNotifier: Invalid socket 120 and type 'Read', disabling...
QSocketNotifier: Invalid socket 60 and type 'Read', disabling...
QSocketNotifier: Invalid socket 112 and type 'Read', disabling...
QSocketNotifier: Invalid socket 117 and type 'Read', disabling...
QSocketNotifier: Invalid socket 128 and type 'Read', disabling...
QSocketNotifier: Invalid socket 88 and type 'Read', disabling...
QSocketNotifier: Invalid socket 115 and type 'Read', disabling...
QSocketNotifier: Invalid socket 126 and type 'Read', disabling...
QSocketNotifier: Invalid socket 63 and type 'Read', disabling...
QSocketNotifier: Invalid socket 66 and type 'Read', disabling...
QSocketNotifier: Invalid socket 139 and type 'Read', disabling...
QSocketNotifier: Invalid socket 148 and type 'Read', disabling...
QSocketNotifier: Invalid socket 152 and type 'Read', disabling...
QSocketNotifier: Invalid socket 141 and type 'Read', disabling...
Registering ":1.290/StatusNotifierItem" to system tray
Service  ":1.260" unregistered
QSocketNotifier: Invalid socket 8 and type 'Read', disabling...
QSocketNotifier: Invalid socket 26 and type 'Read', disabling...
QSocketNotifier: Invalid socket 47 and type 'Read', disabling...
Service  "org.kde.StatusNotifierHost-6596" unregistered
pa_write() failed while trying to wake up the mainloop: Ungültiger Dateideskriptor
pa_write() failed while trying to wake up the mainloop: Ungültiger Dateideskriptor
pa_write() failed while trying to wake up the mainloop: Ungültiger Dateideskriptor
Invalid write to eventfd: Ungültiger Dateideskriptor
Code should not be reached at ../src/pulsecore/fdsem.c:188, function pa_fdsem_post(). Aborting.
Unable to start Dr. Konqi
Re-raising signal for core dump handling.
org.kde.pim.akonadiserver: Subscriber "PlasmaEventModelMonitor - 94494840849952" disconnected
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3978, resource id: 41943054, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4020, resource id: 41943060, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4060, resource id: 41943072, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4100, resource id: 41943141, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4104, resource id: 41943141, major code: 25 (SendEvent), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4133, resource id: 16794372, major code: 18 (ChangeProperty), minor code: 0
kf.plasma.quick: Applet preload policy set to 1
qml: JSON.parse: Parse error
qml: load backend: backend/QtMultimedia.qml
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 11713, resource id: 41943049, major code: 18 (ChangeProperty), minor code: 0`

**Comment by catsout** [comment]
Does it crash when only use video wallpapers  
How does it crash, any reproduction steps  
`second screen is not working half the time`, what's the meaning of not working, it's black screen or paused unexpected

**Comment by Crylia** [comment]
@catsout 
The Wallpaper that caused the hard crash was 909999044, its a .mp4 file format.
The second problem was that i was using two different wallpapers, it seems like that 1394761872 (which is also .mp4) works but only sometimes. After some time(pretty random) it crashed half(?) of kde (the second monitor will act like kde crashed, but only on this monitor, the primary one still works just fine). It may have to do with the .mp4 format.

**Comment by catsout** [comment]
So, the scene or web wallpapers don't crash?  
Could you test the situation of only one screen?  
You can try mpv backend on the video wallpaper

**Comment by Crylia** [comment]
@catsout If I use it on one screen only It crashes with me unable to recover KDE (I have to switch the wallpaper in use to something else via the command line to restart KDE with alt+f2 and the command I forgot)
