### ISSUE TITLE
Error source is empty and cmake issues manjaro

### ISSUE THREAD

**Issue by unsatisfactory212** [catsout/wallpaper-engine-kde-plugin#8]
kde version: 5.21.2 
i wasnt able to figure out if qml-module-qt-labs-folderlistmodel is installed however i did find out that the plugin can detect the wallpapers as long as they are in my home folder, also after doing journalctl /usr/bin/plasmashell and killall plasmashell && kstart5 plasmashell multiple times whilst also trying to get the plugin to remember the path /home/unsatisfactory/.local/share/Steam/steamapps/workshop/content/431960/ no logs got created

The cmake error is: CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/unsatisfactory/wallpaper-engine-kde-plugin/build/CMakeFiles/CMakeOutput.log".

the cmakeoutput.log only contained: The system is: Linux - 5.11.2-1-MANJARO - x86_64

**Comment by catsout** [comment]
The folder path is changed, select `/home/unsatisfactory/.local/share/Steam` not `/home/unsatisfactory/.local/share/Steam/steamapps/workshop/content/431960/` at now.

You need to install `make` and `g++`

**Comment by unsatisfactory212** [comment]
i have installed gcc (g++) and make, also the directory issue is fixed however when i compile it i am now greeted with the following error 63 % of the waqy through the process : In file included from /home/unsatisfactory/wallpaper-engine-kde-plugin/build/src/backend/mpv/mpvbackend_autogen/EWIEGA46WW/moc_mpvbackend.cpp:10,
                 from /home/unsatisfactory/wallpaper-engine-kde-plugin/build/src/backend/mpv/mpvbackend_autogen/mocs_compilation.cpp:2:
/home/unsatisfactory/wallpaper-engine-kde-plugin/build/src/backend/mpv/mpvbackend_autogen/EWIEGA46WW/../../../../../../src/backend/mpv/mpvbackend.h:6:10: fatal error: mpv/client.h: No such file or directory
    6 | #include <mpv/client.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/backend/mpv/CMakeFiles/mpvbackend.dir/build.make:82: src/backend/mpv/CMakeFiles/mpvbackend.dir/mpvbackend_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:260: src/backend/mpv/CMakeFiles/mpvbackend.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by catsout** [comment]
You need may below package, 
liblz4-dev qtbase5-private-dev libqt5x11extras5-dev libmpv-dev

**Comment by unsatisfactory212** [comment]
i cant seem to find liblz4-dev qtbase5-private-dev libqt5x11extras5-dev libmpv-dev in the arch or arch user repositories so im wondering how @Naotomo2 got it to work on their arch based distro, by the way thanks for all the help its greatly appreciated

**Comment by unsatisfactory212** [comment]
Wait i just checked and i dont have opengl 3.2 installed could that be the issue ?

**Comment by catsout** [comment]
No, you should have opengl 3.2 support unless you use arm device.  
`libgl-dev` may needed, but it should be installed.  
You need to figure out what the exactly packages are in archlinux.

**Comment by unsatisfactory212** [comment]
after having to reinstall manjaro xD, i figure out how to get it all running so i will create a new post with a guide for manjaro
