### ISSUE TITLE
libmpvbackend.so not found with scene backgrounds in Arch Linux

### ISSUE THREAD

**Issue by MystikHub** [catsout/wallpaper-engine-kde-plugin#88]
**Describe the bug**
Some wallpapers don't load with an error message of "Plugin lib not found. To support scene, please compile and install it"

**Workshop link**
[Doesn't work: 1243346991](https://steamcommunity.com/sharedfiles/filedetails/?id=1243346991)
[Works: 1897614222](https://steamcommunity.com/sharedfiles/filedetails/?id=1897614222)

**Kde version**
- Kde: 5.23.3
- Qt: 5.15.2
- OS: Arch Linux

**Additional context**

Here's a screenshot of the error on the Nier Automata scene wallpaper:

![image](https://user-images.githubusercontent.com/13604102/142255256-610379a8-03d5-418e-a0b6-413c3b8465c1.png)

And the working Witcher 3 Snow Mountains wallpaper:

![image](https://i.imgur.com/XaRqois.jpg)

I installed the plugin using the [Install](https://github.com/catsout/wallpaper-engine-kde-plugin#install) instructions on the readme (and installed the packages needed for Arch Linux).

I've looked at some of the closed issues, but they haven't fixed the issue for me. I've also tried restarting the plasma shell and also restarted my system.

I noticed that this box is unchecked in the about tab, maybe that has something to do with it? Was there something else I had to install that wasn't mentioned in the readme?

![image](https://user-images.githubusercontent.com/13604102/142258575-c0522203-cdc6-4f7b-9e5f-7038ff23626f.png)

After restarting the plasma shell with `kquitapp5 plasmashell && kstart5 plasmashell > ~/plasma.log 2>&1` I get [this](https://pastebin.com/LwcBJvFf) log file. The first few lines caught my eye with an error message mentioning `libmpvbackend.so`:

```
Omitting both --window and --windowclass arguments is not recommended
kf.plasma.quick: Applet preload policy set to 1
qml: ---check lib 'com.github.catsout.wallpaperEngineKde 1.1' failed---
qml: Error: Qt.createQmlObject(): failed to create object: 
    file:///home/<my username>/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/inline:1:1: plugin cannot be loaded for module "com.github.catsout.wallpaperEngineKde": Cannot load library /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/libWallpaperEngineKde.so: (libmpvbackend.so: cannot open shared object file: No such file or directory)
qml: JSON.parse: Parse error
qml: load backend: backend/QtMultimedia.qml
...
```

I've searched the Arch packages for libmpv but only the mpv package comes up (and it's not on the aur either). 

Additionally here's the output from my `/usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde` directory:
```
libWallpaperEngineKde.so  qmldir
```

**Comment by catsout** [comment]
Fixed, please fellow the install steps again

**Comment by MystikHub** [comment]
That fixed it, thanks!
