### ISSUE TITLE
Installation guide - Manjaro KDE

### ISSUE THREAD

**Issue by unsatisfactory212** [catsout/wallpaper-engine-kde-plugin#9]
How to install Wallpaper-engine-kde-plugin on manjaro:
step 1: run `sudo pacman -Sy base-devel
`(choose the default option) this will install gcc and make which are required to compile the code in cmake
step 2: install cmake and mpv media player via the add and remove software app or command line (your choice)
step 3: follow catsout's instructions on the following github page https://github.com/catsout/wallpaper-engine-kde-plugin#install-kde-plugin

also on a side note i recommend exiting the plugin before restarting or shutting down manjaro because it may cause manjaro to completly break (happened after i spent ages installing many different packages to figure out how to get it to work on manjaro i will update this if it happens again on my fresh manjaro install or if i find out what caused it)

Edit: haven't experienced the issue since the fresh install so it was most likely unrelated to the plugin

**Comment by xihnik** [comment]
1. sudo pacman -Sy base-devel

**Comment by RealBlueVR** [comment]
Another note from me here:

When doing https://github.com/catsout/wallpaper-engine-kde-plugin#build-and-install-plugin-lib
I had to use `sudo` on all lines. Otherwise I would get a 'permission' denied.

**Comment by xihnik** [comment]
@unsatisfactory212 Can you provide a complete list of the commands you need to run in order to make this work?

**Comment by xihnik** [comment]
**Manjaro KDE**

Install:
1. Install "wallpaper-engine-kde-plugin" in modules for wallpaper.
2. Install package "qt5-declarative"
3. Choose folder ~/.local/share/Steam

*New walpapers install in workbench section wallpaper engine

**Comment by catsout** [comment]
Closed as this is in readme.
