### ISSUE TITLE
qtwebsockets installed but not found

### ISSUE THREAD

**Issue by duzhaokun123** [catsout/wallpaper-engine-kde-plugin#93]
**Describe the bug**
qtwebsockets (libqt5websockets5(5.15.2-2)) installed but not found

**Kde version**
- Kde: 5.80.0
- Qt: 5.15.2
- OS: kubuntu 21.04

**Additional context**
build from source code https://github.com/catsout/wallpaper-engine-kde-plugin/commit/f56a5691220ba03e7ee7bb5cb93b7b04de4b6cd0

**Comment by catsout** [comment]
Please install `qml-module-qtwebsockets`  
Seems I forgot to write it in the readme.

**Comment by duzhaokun123** [comment]
ok thinks
