### ISSUE TITLE
Add an option for pausing wallpaper when running Gamemode

### ISSUE THREAD

**Issue by HenrikDK2** [catsout/wallpaper-engine-kde-plugin#96]
I have quite a big monitor 49" and i usually don't play on fullscreen unless it's a racing game. That means that the wallpaper in the background is taking unnecessary resources that could be used on the game.

In Wallpaper Engine there is an option for pausing the wallpaper when a window is in focus, which is quite different from the option "any window", but that used to be my "work around" on windows. I think having the option to pause when Gamemode is running would be even better since i always run all my games with Feral Gamemode. So i could play any game in windowed or fullscreen mode without having to worry about disabling the wallpaper.

**Comment by NicBOMB** [comment]
> I have quite a big monitor 49" and i usually don't play on fullscreen unless it's a racing game. That means that the wallpaper in the background is taking unnecessary resources that could be used on the game.
> 
> In Wallpaper Engine there is an option for pausing the wallpaper when a window is in focus, which is quite different from the option "any window", but that used to be my "work around" on windows. I think having the option to pause when Gamemode is running would be even better since i always run all my games with Feral Gamemode. So i could play any game in windowed or fullscreen mode without having to worry about disabling the wallpaper.

I found this https://gist.github.com/krishraghuram/34df4f5f94ae6731a475f76bf479197c/ which might be able to apply a wallpaper when gamemode starts. When gamemode ends, a similar script could then change it back. I don't know how any of your saved settings may be changed from using this script. I won't take responsibility if something breaks, but you should be able to restore your desktop configuration if you backup your ~/.config/plasma-org.kde.plasma.desktop-appletsrc . You can see where the scripts discussed above are listed in Feral Interactive's example gamemode.ini https://github.com/FeralInteractive/gamemode/blob/master/example/gamemode.ini#L88-L97
Your feature request is probably beyond the scope of this plugin, though I would like it to be better integrated too.

**Comment by SqrHornet** [comment]
This is related to #104

**Comment by catsout** [comment]
There is a focus pause mode now.

**Comment by catsout** [comment]
As there is no something like `Gamemode` in linux, closed.  
Please go https://github.com/catsout/wallpaper-engine-kde-plugin/issues/104 to continue.
