### ISSUE TITLE
Wallpaper not filling the screen

### ISSUE THREAD

**Issue by linsyking** [catsout/wallpaper-engine-kde-plugin#98]
**Describe the bug**
This wallpaper can't fill the whole screen.

**Workshop link**
[2432579865](https://steamcommunity.com/sharedfiles/filedetails/?id=2432579865)

**Kde version**
- Kde: [5.23.3]
- Qt: [5.15.2]
- OS: [Manjaro]

**Additional context**

**Comment by Jelgnum** [comment]
Go to the settings tab and set your display to "Scale and Crop" and it fills the screen. I'm currently running the same setup and this only shows up when not in scale and crop

**Comment by linsyking** [comment]
Thanks,maybe this setting can
